### ISSUE TITLE
Demo workspaces and services need update to deegree 3.4.x

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1060]
Currently demo's running under https://www.deegree.org/demo/ are currently using outdated workspace's and runtime v3.3.20. 
Updated needed of workspace and services to v3.4.x.

Relates to:

- [x] #964 
- [x] #695

**Comment by tfr42** [comment]
Related to the posting https://sourceforge.net/p/deegree/mailman/message/36995300/

**Comment by tfr42** [comment]
The workspace from plaza for the 4 demo instances needs to be migrated to the configuration schema `configVersion="3.4.0"`.

**Comment by tfr42** [comment]
Migration will be done as part of issue #1130.

**Comment by tfr42** [comment]
Migration to deegree 3.4 web app completed with #1130. Links to current documentation updated for https://www.deegree.org/demo/.

**Comment by lgoltz** [comment]
Referenced issues are closed.
