### ISSUE TITLE
deegree 3.4.13 fails some tests of OGC CITE Test Suites

### ISSUE THREAD

**Issue by dstenger** [deegree/deegree3#1062]
Used instance of TEAM Engine: https://cite.opengeospatial.org/teamengine/

# WMS 1.3 and WMS 1.1

Some tests are failing which were not failing with 3.4.12:

WMS 1.3 test names:
* each-format 
* bbox-pixel-interpretation 
* blue-lake-sanity-check 
* layer-order 

WMS 1.1 test names:
No deep analysis has been done, yet. However, origin should be similar as for WMS 1.3.

# WFS 2.0

8 tests are failing which were no failing with 3.4.5.
For details please see https://github.com/deegree/deegree3/issues/1033#issuecomment-583398208.

**Comment by dstenger** [comment]
Example for same GetMap request using 3.4.12 and 3.4.13 (lake is missing in 3.4.13):
* http://cite.deegree.org/deegree-webservices-3.4.12/services/wms130?&VERSION=1.3.0&REQUEST=GetMap&LAYERS=cite%3AStreams,cite%3ALakes,cite%3APonds,cite%3ABridges,cite%3ARoadSegments,cite%3ADividedRoutes,cite%3ABuildings,cite%3AMapNeatline&STYLES=&CRS=CRS:84&BBOX=-0.005,-0.0025,.005,0.0025&WIDTH=400&HEIGHT=200&FORMAT=image%2Fpng
* http://cite.deegree.org/deegree-webservices-3.4.13/services/wms130?&VERSION=1.3.0&REQUEST=GetMap&LAYERS=cite%3AStreams,cite%3ALakes,cite%3APonds,cite%3ABridges,cite%3ARoadSegments,cite%3ADividedRoutes,cite%3ABuildings,cite%3AMapNeatline&STYLES=&CRS=CRS:84&BBOX=-0.005,-0.0025,.005,0.0025&WIDTH=400&HEIGHT=200&FORMAT=image%2Fpng

**Comment by dstenger** [comment]
Discussed during TMC meeting (2020-07-31):

We shall re-run the tests in an isolated setup where only one deegree WAR is installed on a Tomcat instance.
May be we can use the docker images per version and re-run the tests for each version.

**Comment by dstenger** [comment]
The WMS failures resulted from the fact that multiple deegree instances are using the same workspace on cite.deegree.org.
*.lock.db files are generated which prevent the second instance to access the data.
I will create a new issue for that.
However, if individual workspaces are used, the tests are passed with v3.4.13 again.

**Comment by dstenger** [comment]
Issue regarding lock files was created: https://github.com/deegree/deegree3/issues/1139

**Comment by tfr42** [comment]
deegree v.3.4.16 has successfully passed OGC compliance. 
Upgrade to v3.4.16.
