### ISSUE TITLE
Using 4-band GeoTIFF with GdalLayer is not supporting transparency 

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1065]
Using a 4-band (RGBA) GeoTIFF with GdalLayer is not supporting the alpha values. Instead background color is shown.

**Comment by tfr42** [comment]
The GDALTileStore and GdalLayerStore was implemented to support EZW resources and was not tested intensively with GeoTIFF.

**Comment by copierrj** [comment]
I'm not sure if we really want to just drop this transparency band stripping code to fix this issue. It was (most likely) added to solve another issue (probably related to handling requests with JPEG as output format). Are you sure we are not breaking something?
