### ISSUE TITLE
Drop and remove Oracle JDK from buildserver.deegree.org

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1077]
The motion is to uninstall Oracle JDK from plaza.deegree.org

**Comment by copierrj** [comment]
Rational: we are currently using an outdated Oracle JDK and cannot upgrade because of licensing costs.

**Comment by tfr42** [comment]
Release build job: http://buildserver.deegree.org/job/deegree-3.4-master/ and
Pipeline http://buildserver.deegree.org/job/deegree3.4-pipeline/ configured to use OpenJDK 8.
Site job also changed to OpenJDK 8 http://buildserver.deegree.org/job/deegree-3.4-site/.

**Comment by tfr42** [comment]
Oracle JDK not in use for building or running one of the services (see wiki https://github.com/deegree/deegree3/wiki/Infrastructure#services)
