### ISSUE TITLE
Improve error message when inserting empty geometry elements using WFS-T INSERT action

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1080]
WFS-T INSERT action fails with error message "InvalidParameterValue?: Cannot perform insert operation: Error inserting feature: Index: 0, Size: 0" when geometry element has no values such as:
```
<gml:geometry>
            <gml:MultiSurface></gml:MultiSurface>
</gml:geometry>
```

Exception shown in log (requires log level `log4j.logger.org.deegree.feature.persistence.sql.SQLFeatureStoreTransaction=TRACE`):
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
 	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
 	at java.util.LinkedList.get(LinkedList.java:476)
 	at org.deegree.geometry.standard.multi.DefaultMultiGeometry.getCoordinateDimension(DefaultMultiGeometry.java:85)
 	at org.deegree.geometry.io.WKBWriter.write(WKBWriter.java:70)
 	at org.deegree.sqldialect.postgis.PostGISGeometryConverter.setParticle(PostGISGeometryConverter.java:134)
 	... 37 more
```

Expected is a improved error message in log statement and better ExceptionMessage

**Comment by lgoltz** [comment]
Only MultiGeometries are concerned. Empty multi geometries are valid xml (GML 3.2). How to handle this empty geometries? See also the comment in https://github.com/deegree/deegree3/blob/master/deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/multi/DefaultMultiGeometry.java#L203

At least at two times the geometry at the first index are requested without check if the collection is empty:
 * https://github.com/deegree/deegree3/blob/master/deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/multi/DefaultMultiGeometry.java#L85
 * https://github.com/deegree/deegree3/blob/master/deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/multi/DefaultMultiGeometry.java#L204

**Comment by tfr42** [comment]
Interfaces to be checked
- HTTP/GML (WFS-T Insert) must support empty geometries 
- Database/WKB must be checked if the supported Databases (PostGIS, Oracle, MS SQL) support empty multi geometries 


Possible ways to deal with it:
- throw an exception
- define return values for empty multi geometries
- introduce NullValue type with 
- swallow the IOOB exception and return a appropriate WFS exception 
- improve the log anyway

**Comment by copierrj** [comment]
I would like to suggest the following
- explicit check for empty multi geometries while converting deegree Geometry into the corresponding native database type and deal with it appropriately for that particular database
- consider always raising an exception when a method of MultiGeometry is called what's not properly defined for multi geometries (like asking for it coordinateDimension)
