### ISSUE TITLE
Support of GML 3.2.2

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1088]
deegree WFS shall support most recent version 3.2.2

List of public schemas at ogc.org: http://schemas.opengis.net/gml/ReadMe.txt

**Comment by kad-broenm** [comment]
@tfr42 in the current version (3.4.13), GML 3.2.2 isn't supported yet. Will this be supported in the near future?

**Comment by tfr42** [comment]
Currently we have PR #1092 still open. Contributions are welcome as always.

**Comment by tfr42** [comment]
PR #1104 provides support for GML 3.2.2

**Comment by tfr42** [comment]
Fixed by PR #1092 and #1108
