### ISSUE TITLE
svg in PolygonSymbolizer is ignored

### ISSUE THREAD

**Issue by lgoltz** [deegree/deegree3#1093]
Example style configuration: 
```
          <se:PolygonSymbolizer>
            <se:Fill>
              <se:GraphicFill>
                <se:Graphic>
                  <se:ExternalGraphic>
                    <se:OnlineResource xlink:type="simple" xlink:href="test.svg"/>
                    <se:Format>image/svg</se:Format>
                  </se:ExternalGraphic>
                  <Size>40</Size>
                </se:Graphic>
              </se:GraphicFill>
            </se:Fill>
          </se:PolygonSymbolizer>
```

The configured svg is ignored and the default mark (square) is used for rendering. 
In https://github.com/deegree/deegree3/blob/14d357cbd7644f39ea1fe13cfffb71db3c160fcb/deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/Java2DFillRenderer.java#L78-L94 graphic.imageUrl is not handled.

**Comment by tfr42** [comment]
Relates to #1383
