### ISSUE TITLE
version reference in response headers

### ISSUE THREAD

**Issue by axza** [deegree/deegree3#1102]
Hello awesome People! 
even if I consider deegree as safe, I would like to have the possibility to suppress the output of the deegree-versions number in the response. 
Following is a line reference.

https://github.com/deegree/deegree3/blob/2bdd14a06f7b375fe1c5f7a8b34e2cfddd63070f/deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java#L306

Is there anything that speaks against it?

**Comment by copierrj** [comment]
Exposing information like this for everybody to see is indeed risky. Usually such information is filtered out by a reverse proxy but perhaps we should consider removing it altogether.

**Comment by tfr42** [comment]
Please post this as a feature request and if possible a related PR. See our [guidelines for working with PR](https://github.com/deegree/deegree3/wiki/Working-with-pull-requests) for further information.
