### ISSUE TITLE
Replace xml-matchers with XMLUnit

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1113]
[xml-matchers](https://github.com/davidehringer/xml-matchers) is used for testing XML in unit/integration tests. The extension to JUnit/Hamcrest is not maintained anymore (old website https://code.google.com/archive/p/xml-matchers/) and is not compatible with recent framework versions running on Java 11.

My proposal is to replace it with https://www.xmlunit.org/.

**Comment by lgoltz** [comment]
xml-matchers was replaced with XMLUnit with pull request https://github.com/deegree/deegree3/pull/1329

**Comment by tfr42** [comment]
XMLUnit is used starting from deegree version 3.4.31 (with PR #1329).
