### ISSUE TITLE
Preparing next release version (deegree web services 3.5)

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1120]
The [TMC has the notion to prepare a next minor (3.5)](https://github.com/deegree/deegree3/wiki/tmc-meeting-minutes-20210129) version which contains the [schema changing PR](https://github.com/deegree/deegree3/pulls?q=is%3Apr+label%3A%22schema+change%22+milestone%3A3.5+) and the upgrade of the runtime environment to support [JDK 11 and Tomcat 9.x](https://github.com/deegree/deegree3/issues/857).

Open Issues which should be resolved with next major release version:

- [x] Complete upgrade HOWTO in https://github.com/deegree/deegree3/wiki/Upgrading-deegree-webservices
- [x] Update https://github.com/deegree/deegree3/wiki/Releasing-deegree
- [x] Update https://github.com/deegree/deegree3/wiki/End-of-Life-and-Support-Matrix
- [x] Update build infrastructure: #1072, #1060, #851
- [x] [Update documentation](https://github.com/deegree/deegree3/blob/master/deegree-services/deegree-webservices-handbook/src/main/asciidoc/installation.adoc), #1358
- [x] #1322
- [x] #991 
- [x] #990 
- [x] #1124
- [x] #953 
- [x] merging all [schema changing PR](https://github.com/deegree/deegree3/pulls?q=is%3Aopen+is%3Apr+label%3A%22schema+change%22)
- [x] #857 
- [x] #1324
- [x] #963 
- [x] #976 
- [x] #1046
- [x] #1103
- [x] #1017
- [x] #1026
- [x] #1122
- [x] Move the obsolete module deegree-spring to the uncoupled section, see #1217

**Comment by tfr42** [comment]
Release build for 3.4-RC1 failed due to:
```
[ERROR] remote: Resolving deltas: 100% (115/115), completed with 91 local objects.        
[ERROR] remote: error: GH006: Protected branch update failed for refs/heads/main.        
[ERROR] remote: error: Changes must be made through a pull request.        
[ERROR] To github.com:deegree/deegree3.git
[ERROR]  ! [remote rejected]       main -> main (protected branch hook declined)
[ERROR] error: failed to push some refs to 'github.com:deegree/deegree3.git'
```

**Comment by tfr42** [comment]
Removed `deegree-ci` member from **Core** team.

**Comment by tfr42** [comment]
deegree webservices version 3.5-RC1 is available for download. Check http://www.deegree.org/download/ for more information how to get the artefact.
Direct download link: https://repo.deegree.org/repository/releases/org%2Fdeegree%2Fdeegree-webservices%2F3.5-RC1%2Fdeegree-webservices-3.5-RC1.war

**Comment by julianzz98** [comment]
Testing of the deegree 3.5-RC1 with the provided deegree workspaces was successful, furthermore INSPIRE data was published as WFS with a postgresql database as datasource.

**Comment by tfr42** [comment]
No blocking issue for 3.5 open 👍. We are ready to release 3.5.0. 🚀

**Comment by tfr42** [comment]
Release build completed sucessfully: https://buildserver.deegree.org/job/deegree-3.5-release-pipeline/12/

**Comment by tfr42** [comment]
Now we proceed with the publishing of the release as described in https://github.com/deegree/deegree3/wiki/Releasing-deegree

**Comment by tfr42** [comment]
- [ ] create new milestone on github https://github.com/deegree/deegree3/milestones/ 
- [ ] tag and label all merged PR for this milestone, use a query like [is:pr is:merged merged:>=2022-03-02](https://github.com/deegree/deegree3/pulls?q=is%3Apr+is%3Amerged+merged%3A%3E%3D2022-03-02+). Follow also [Update GitHub pull requests](#Update-GitHub-pull-requests)
- [ ] [run build job](#Run-Jenkins-jobs) **without perform release enabled** 
- [ ] _**Continue when no error occurred!**_
- [ ] [run build job](#Run-Jenkins-jobs) **with maven release perform enabled**
- [ ] verify that relevant artifacts have been uploaded to nexus: https://repo.deegree.org/repository/public/org/deegree/deegree-webservices/
- [ ] update Dockerfile to new version: https://github.com/deegree/deegree3-docker/blob/master/Dockerfile
- [ ] build docker image from Dockerfile
- [ ] locally test docker image as described in https://github.com/deegree/deegree3-docker/blob/master/README.md
- [ ] _**Continue when no fatal or unknown error occurred!**_
- [ ] create docker tag: https://github.com/deegree/deegree3-docker/tags
- [ ] push docker image to: https://hub.docker.com/r/deegree/deegree3-docker/
- [ ] create release from tag: https://github.com/deegree/deegree3-docker/releases
- [ ] publish documentation as described [here](#Publish-the-handbook) 
- [ ] create release from tag and upload [WAR](https://repo.deegree.org/#browse/search/maven=attributes.maven2.artifactId%3Ddeegree-webservices%20AND%20version%3D3.4.*%20AND%20assets.attributes.maven2.extension%3Dwar) and [PDF](https://repo.deegree.org/#browse/search/maven=attributes.maven2.artifactId%3Ddeegree-webservices-handbook%20AND%20version%3D3.4.*%20AND%20assets.attributes.maven2.extension%3Dzip) artifacts to https://github.com/deegree/deegree3/releases 
- [ ] publish tag and use "auto-generate release notes" 
- [ ] close milestone and add link to release tag
- [ ] update and publish website as described [here](#Update-homepage)
- [ ] update end-of-life matrix: https://github.com/deegree/deegree3/wiki/End-of-Life-and-Support-Matrix
- [ ] send email out to mailing lists as described [here](#Send-release-announcement)
- [ ] Send a tweet for #deegree_org at twitter: https://twitter.com/deegree_org
