### ISSUE TITLE
Editing resources in subfolder results in NPE

### ISSUE THREAD

**Issue by lgoltz** [deegree/deegree3#1133]
Editing resources in subfolders like "services/test/test.xml" results in a NullPointerException:
 * Edit resource via deegree console
 * Save resources (without changes)

`Fehler "null"` is shown in the console. A FileNotFoundException is logged:

  ```
deegree3_1  | java.io.FileNotFoundException: /root/.deegree/saar2loader/services/inspirewfs/inspirewfs/INS_SL_Building2D_ALKIS.xml (No such file or directory)
deegree3_1  | 	at java.io.FileInputStream.open0(Native Method)
deegree3_1  | 	at java.io.FileInputStream.open(FileInputStream.java:195)
deegree3_1  | 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
deegree3_1  | 	at org.deegree.workspace.standard.DefaultResourceLocation.getAsStream(DefaultResourceLocation.java:114)
deegree3_1  | 	at org.deegree.workspace.standard.DefaultResourceLocation.getNamespace(DefaultResourceLocation.java:84)
deegree3_1  | 	at org.deegree.workspace.standard.DefaultResourceManager.read(DefaultResourceManager.java:120)
deegree3_1  | 	at org.deegree.services.OwsManager.read(OwsManager.java:85)
deegree3_1  | 	at org.deegree.workspace.standard.DefaultResourceManager.add(DefaultResourceManager.java:152)
deegree3_1  | 	at org.deegree.workspace.standard.DefaultWorkspace.add(DefaultWorkspace.java:504)
deegree3_1  | 	at org.deegree.workspace.WorkspaceUtils.reinitializeChain(WorkspaceUtils.java:88)
deegree3_1  | 	at org.deegree.console.generic.XmlEditorBean.activate(XmlEditorBean.java:257)
deegree3_1  | 	at org.deegree.console.generic.XmlEditorBean.save(XmlEditorBean.java:210)
```

**Comment by lgoltz** [comment]
https://github.com/deegree/deegree3/blob/d9ccf38f6efbef8d3cf2b20c99137ae192581b57/deegree-core/deegree-core-workspace/src/main/java/org/deegree/workspace/standard/DefaultResourceLocation.java#L175-L179
 and 
https://github.com/deegree/deegree3/blob/d9ccf38f6efbef8d3cf2b20c99137ae192581b57/deegree-core/deegree-core-workspace/src/main/java/org/deegree/workspace/standard/DefaultResourceLocation.java#L168-L171

do not consider that resources could be stored in subfolders. This results in an invalid path to the resource (with duplicated subfolder in the path).

**Comment by julianzz98** [comment]
The fix was tested successfully and a PR was created.
