### ISSUE TITLE
Change maven build to access repo.deegree.org over https

### ISSUE THREAD

**Issue by copierrj** [deegree/deegree3#1138]
We would like to start using https for accessing repo.deegree.org in order to be able to build deegree using Maven 3.8.1.

Todo:
- [x] Change deegree pom.xml files: #1137
- [x] Release deegree using Maven 3.8.3

**Comment by tfr42** [comment]
deegree-maven plugin has been removed from build and thus a lot of work vanished 👍

**Comment by tfr42** [comment]
Release build for 3.4.19 shall use maven 3.8.3

**Comment by tfr42** [comment]
Release build for 3.4.19 using maven 3.8.3 and OpenJDK 8 (Temurin) completed successfully and all artifacts have been uploaded to nexus.
