### ISSUE TITLE
The "new theme" example configuration does not produce valid XML

### ISSUE THREAD

**Issue by tilmanb** [deegree/deegree3#1145]
The XML generated from the admin console for creating a new theme does not validate.

How to reproduce

1. deegree 3.4.16
2. create new empty workspace 
3. select "themes" in left menu
4. click "create new"
5. input identifier "ddd" or any other
6. select type Standard and XML config template "example"
7. click "create new"
8. click "validate" in top row

Result

Display of the following errors above the code editor

    Error near line 11, column 14: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.deegree.org/metadata/description":Title}'. One of '{"http://www.deegree.org/themes/standard":Layer, "http://www.deegree.org/themes/standard":Theme}' is expected.
    Error near line 17, column 16: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.deegree.org/metadata/description":Title}'. One of '{"http://www.deegree.org/themes/standard":Layer, "http://www.deegree.org/themes/standard":Theme}' is expected.

Expected result

The example configuration should produce valid XML.

**Comment by julianzz98** [comment]
Thank you for pointing out the bug @tilmanb!

In my local deegree version 3.4.23 as well as the (yet) unreleased 3.4.24 the bug is already fixed. 
So I would suggest we should close this issue now.

**Comment by tilmanb** [comment]
OK, closed as it works in current versions
