### ISSUE TITLE
Switch from freenode to libera chat

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1149]
Actual all TMC sessions and general chats about deegree are using the IRC chat at irc.freenode.net.
Due to changes at Freenode (see https://freenode.net/news/fosshost-partnership) a group of developers have started a new project (see https://libera.chat/news/welcome-to-libera-chat).
TMC shall decide if to stay with Freenode or to move to Libera chat.

If approved then chages to the following files and pages are needed:

- [x] https://github.com/deegree/deegree3/blob/327e7876b43c3885747840d5edc83df2940bc36a/CONTRIB.md
- [x] https://www.deegree.org/community/

**Comment by tfr42** [comment]
OSGeo has moved their lists to libera chat, see https://lists.osgeo.org/pipermail/sac/2021-June/013378.html

**Comment by stephanr** [comment]
The channel has been registered and a topic was set to:
```
Welcome to deegree, an OSGeo project. Visit the main project page at http://deegree.org and our wiki at http://wiki.deegree.org with lots of extra info. Check out a running system at http://demo.deegree.org and follow us on twitter @deegree_org.
```

**Comment by tfr42** [comment]
Announcement to the deegree mailing lists: https://sourceforge.net/p/deegree/mailman/message/37310036/

**Comment by stephanr** [comment]
Attempt to set the topic permanently:
```
/msg ChanServ INFO #deegree
/msg ChanServ TOPIC #deegree Welcome to deegree, an OSGeo project. Visit the main project page at https://www.deegree.org and our wiki at https://github.com/deegree/deegree3/wiki with lots of extra info. Check out a running system at https://www.deegree.org/demo/ and follow us on twitter @deegree_org.
/msg ChanServ SET #deegree KEEPTOPIC ON
/msg ChanServ SET #deegree URL https://www.deegree.org
```
