### ISSUE TITLE
Auto-generating a mapping configuration and tables

### ISSUE THREAD

**Issue by siplo** [deegree/deegree3#1175]
Hi, 

I tried to find way how to reach this functionality but it doesn't works  for me. I use version 3.4.16 - docker iamge.  When I try create new sql feature store - wizard doesn't show up. I can see just editor for xml files. I found out there are xhmtl files under directory: webapps/deegree-webservices/console/datastore/feature/sql/ and when I use this in my browser: http://localhost:8080/deegree-webservices/console/datastore/feature/sql/wizard2.xhtml  I can see wizard screen with xsd schemas. I choose xsd and click to next I got "Unable to find matching navigation case with from-view-id '/console/datastore/feature/sql/wizard2.xhtml' for action '#{mappingWizardSQL.analyzeSchema}' with outcome '/console/featurestore/sql/wizard3'

and I think this is a problem because I was not able find mapping or dirctory structure as it is mentioned in note:  /console/featurestore/sql/wizard3'

Please can you explain me how to use it or if this doesn't work at least fix user manual  ?

Thanks

Michal

**Comment by tfr42** [comment]
The releated issue is #471. The current workaround is to use the deegree CLI to generate a SQLFeatureStore mapping and SQL DDL script, see https://github.com/deegree/deegree3/blob/master/deegree-tools/deegree-tools-config/README.md for more information.

**Comment by tfr42** [comment]
Still contribution is welcome to make the deegree admin console complete. Currently the workaround is to use the [deegree GML tool](https://download.deegree.org/documentation/current/html/#deegree-gml-tools) (formerly known as deegree CLI).
