### ISSUE TITLE
(Re)move the deegree-spring module from main project 

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1217]
The TMC has the notion to move the https://github.com/deegree/deegree3/tree/master/deegree-spring module into https://github.com/deegree/deegree3/tree/master/uncoupled with the next major version.

**Comment by tfr42** [comment]
The Spring Framework version used in GmlTool #1222 is in conflict to the version used in the deegree-spring module.

**Comment by dstenger** [comment]
Pull request was created: https://github.com/deegree/deegree3/pull/1227
