### ISSUE TITLE
(Re)move of outdated tools modules 

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1223]
Remove of 
- https://github.com/deegree/deegree3/tree/master/deegree-tools/deegree-tools-alkis
- https://github.com/deegree/deegree3/tree/master/deegree-tools/deegree-tools-migration

To be archived in: https://github.com/deegree/deegree3/tree/main/uncoupled

**Comment by lgoltz** [comment]
Relates to #1386
