### ISSUE TITLE
Error loading Feature and services after importing VM from different server

### ISSUE THREAD

**Issue by ohili** [deegree/deegree3#1225]
we just imported a fully working VM running Deegree after restoring to a different SAN we keep getting the below issue.

The setup is totally identical and the VM has been totally moved.  

errors are:

Initialization of resource with id 'inspire_sr_GSA15' failed: Error setting up feature store from configuration: 'Severe error in schema document (systemId: http://www.w3.org/TR/html4/strict.dtd, line: 81, column: 5) The declaration for the entity "ContentType" must end with '>'.'. (The application server log may contain additional information.)

Strangely enough out of about 25 services only a few work and we tried to understand what is different but to no luck

Has anyone had similar issues?  the servers are joined to a local domain in a Governmental entity.

![image](https://user-images.githubusercontent.com/88651455/141469283-36e5cb12-3ece-480f-8714-1425f833914b.png)

**Comment by stempler** [comment]
Sounds like it gets some unexpected response when accessing a resource, maybe trying to access a schema?
Any more details available for the errors on the feature stores?

Which version of deegree are you using?
Maybe you are using `http://` access of INSPIRE schemas but have a version of deegree that can't deal with the redirects to `https`?

**Comment by ohili** [comment]
Thanks for the help.  Issue resolved. since we migrated from another domain we have had to take ownership of deegree and apache folders.

**Comment by tfr42** [comment]
Please see issue #1064 for more information about accessing INSPIRE schema files. We recommend to use tools like https://github.com/mfalaize/schema-fetcher to store those heavy schemas to your disk.
