### ISSUE TITLE
WMS 1.3: Requesting erroneous version in GetMap request leads to wrong exception

### ISSUE THREAD

**Issue by dstenger** [deegree/deegree3#1235]
When a GetMap request is sent against a WMS 1.3 service containing `VERSION=zzzz`, deegree responds with a ExceptionReport.
However, a ServiceExceptionReport is expected.

**Comment by Dnoack49** [comment]
The following request returns the wrong exception:

https://inspire.brandenburg.de/services/ef_sem_wms?SERVICE=WMS&REQUEST=GetMap&BBOX=228152.00000000%2C5690412.00000000%2C493382.00000000%2C5939023.00000000&CRS=EPSG%3A25833&FORMAT=image%2Fpng&HEIGHT=500&LAYERS=EF.EnvironmentalMonitoringProgrammes&STYLES=EF.EnvironmentalMonitoringProgrammes.Default.Point&WIDTH=500&VERSION=zzzz
