### ISSUE TITLE
deegree-tools-gml fails when compiling deegree without any profile enabled

### ISSUE THREAD

**Issue by dstenger** [deegree/deegree3#1268]
Failure: deegree/deegree3/deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/FeatureStoreConfigWriter.java:[52,37] package org.deegree.sqldialect.oracle does not exist

Possible solutions:
1. Enable build of deegree-tools-gml just when oracle profile is activated. 
1. Remove oracle dependency from deegree-tools-gml.

**Comment by stephanr** [comment]
Another option would be to update the Oracle driver to 19.3 or newer. 
From this version onwards, the libraries for the SQLDialect are freely available (unfortunately, non-public drivers are still required for GeoRaster, but this can be ignored here).

Either the driver update from the PR of the version update from PR #1206 could be included completely or partially, thus the SQLDialect can become a regular dependency.
