### ISSUE TITLE
Feature-Request: Endpoint for Console-Output

### ISSUE THREAD

**Issue by 4DFuchs** [deegree/deegree3#1269]
Hi, 
we are running Deegree in Kubernetes with a scalable Deployment (When there is high traffic, Kubernetes will start a second container/pod). Our problem is that the Container takes some time to start Deegree and load all our services. For Kubernetes it is not a problem to wait for the container, but we have to tell Kubernetes when the Container is fully started. (Otherwise it returns 404 service not found)
For that we could use the readinessProbe from Kubernetes, but  we need the information from deegree in a structured way via an api. Like this 
{ "services_configured": 15, "services_loaded": 10, "services_with_errors": 5} 

Is it possible to implement this feature into deegree?

**Comment by stempler** [comment]
Not sure if the existing action in the API to [list the workspaces](https://github.com/deegree/deegree3/blob/master/deegree-services/deegree-services-config/src/main/java/org/deegree/services/config/actions/ListWorkspaces.java) would be sufficient for your use case?

[Here](https://github.com/wetransform-os/deegree3/blob/deegree-3.4.3-we/deegree-services/deegree-services-config/src/main/java/org/deegree/services/config/actions/DependencyGraph.java) is also an action that yields information on the resources, though in an unstructured way as text. You could maybe adapt it to yield Json, or do something similar to get exactly the information you require.

**Comment by tfr42** [comment]
The deegree REST API is document in https://download.deegree.org/documentation/current/html/#anchor-configuration-restapi.
To request a new feature please read https://github.com/deegree/deegree3/wiki/Feature-Request-writing-Guidelines.
To get it implemented the easy path is to get funding, find a developer and get in contact with the TMC to discuss further.

**Comment by tfr42** [comment]
Please post this as a feature request and if possible a related PR. See our [guidelines for working with PR](https://github.com/deegree/deegree3/wiki/Working-with-pull-requests) for further information.
