### ISSUE TITLE
WMS 1.3, TEAM Engine Test "no-version" fails

### ISSUE THREAD

**Issue by julianzz98** [deegree/deegree3#1282]
### Testing enviroment:

TEAM Engine Docker Image used: ogccite/teamengine-production:latest (version 5.4.1)
Postgis Docker Image used: postgis/postgis:9.6-2.5
Deegree Docker Image used: deegree/deegree3-docker:v3.4.25

----

When executing a GetMap request without the mandatory parameter "VERSION=1.3.0", as in:
* http://192.168.178.93:8080/deegree-webservices/services/wms130?CRS=CRS%3A84&REQUEST=GetMap&FORMAT=image%2Fpng&BBOX=-0.00320000,-0.00220000,0.00290000,0.00220000&STYLES=&WIDTH=200&HEIGHT=200&LAYERS=cite%3AAutos

deegree webservices 3.4.25 delivers an image, seen below, instead of giving out an exception report.

----

The response right now:
![Screenshot from 2022-03-01 17-06-47](https://user-images.githubusercontent.com/74777462/156204617-d8d8993a-d83b-45b2-a7d8-f53ec53c64ed.png)

**Comment by dstenger** [comment]
Was already solved by https://github.com/deegree/deegree3/pull/1218.
When creating the bug, the strict parameter was not set in configuration. After setting this parameter, the TEAM Engine test is passed.
