### ISSUE TITLE
 Unable to build resource OWSProvider:wms_pf: null

### ISSUE THREAD

**Issue by joaotcordeiro** [deegree/deegree3#1295]
Hello,

Im having this issue "Unable to build resource OWSProvider:wms_pf: null" in a WMS service. I previously had no such issue but now without making any modifications to the configuration of deegree the WMS services are not Activating.

Is this a known issue?

Regards

**Comment by tfr42** [comment]
To evaluate if the problem is a bug please post the version and setup of your installation. See https://www.deegree.org/community/guidelines/ and https://github.com/deegree/deegree3/wiki/Bug-Report-writing-Guidelines for further information.

**Comment by tfr42** [comment]
Without further information it is not possible to replicate the problem locally. If you can provide more information like a complete workspace and a stack trace from the log output please re-open the issue.
