### ISSUE TITLE
Log4j configuration files do not exist in deegree 3.4.17+ versions

### ISSUE THREAD

**Issue by julianzz98** [deegree/deegree3#1306]
The Log4j configuration files of deegree versions 3.4.17 and higher do not exist. The path 'deegree-webservices/WEB-INF/classes of a deployed webapp' is therefore empty. Versions of 3.4.16 and lower still have the configuration files in the above mentioned filepath.

**Comment by tfr42** [comment]
Regression introduced with https://github.com/deegree/deegree3/pull/1169/files#diff-d45f91431643b00bc0348e6e21c9356d03750ab4b5d8a4084e7bb35eb778c80b.
