### ISSUE TITLE
Create ZIP file of the workspace "deegree-workspace-utah-light" from /deegree-workspaces

### ISSUE THREAD

**Issue by julianzz98** [deegree/deegree3#1356]
In order to use the mentioned workspace for the new release of OSGeoLive 15.0, it needs to be available through the deegree nexus in the ZIP file-format. Therefore a ZIP file needs to be created.
Instead of using a semantic version number, the use of the date (yyyymmdd) should be sufficient.

**Comment by tfr42** [comment]
Build job created:
https://buildserver.deegree.org/view/misc/job/internal/job/upload-workspace-zip/5/
@julianzz98 Please test the provided workspace artifacts.
Next step is uploading into Nexus, if OK.

**Comment by julianzz98** [comment]
The provided workspace artifacts were tested successfully on a local deegree 3.4.31 installation.
