### ISSUE TITLE
Example templates missing in deegree version 3.5.0

### ISSUE THREAD

**Issue by julianzz98** [deegree/deegree3#1361]
The current deegree version 3.5.0 is missing the example templates for all configurations, leading to the following error message:
`Creating resource failed: Internal error: Example template missing!?`

Because of this bug, creating configurations through the web console is currently not possible.

A screenshot of how the bug appears in the web inteface:
![Screenshot from 2022-07-25 16-51-36](https://user-images.githubusercontent.com/74777462/180833376-92480995-26c0-4e90-86be-2b1fa98961ca.png)

However, the functionality of the version is not restricted by the bug.

**Comment by julianzz98** [comment]
We should decide on the usage of the parameter "configVersion" in deegree version 3.5 and further.

Right now, some code examples include it and others don´t. Furthermore the updated documentation states that it is optional, even while it has no usage anymore. Because of this I suggest that we just get rid of it entirely and redo the updates regarding it on the documentation.

**Comment by tfr42** [comment]
The proposal is to remove the optional attribute `configVersion` from the examples and the code snippets in the documentation. Adding an explanation that this attribute is not used and evaluated by deegree v3.5 software but users can keep the attribute to document for which version of deegree the configuration file was created or is compatible to.

**Comment by tfr42** [comment]
Resolved with PR #1377.
