### ISSUE TITLE
Announcement for End of Community Support for deegree 3.4.x 

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1365]
It’s been 4 years since deegree 3.4.0 was released and it is time to announce some changes regarding the end of community support for OSGeo deegree 3.4 release line.

While users of deegree 3.4.x will continue to see releases for security and critical issues until the End of Life (EOL) date, all users are advised to upgrade to deegree 3.5 asap. 

Next actions:

- [x] [GitHub wiki](https://github.com/deegree/deegree3/wiki/End-of-Life-and-Support-Matrix) is updated
- [x] [GitHub Security Policy](https://github.com/deegree/deegree3/security/policy) is updated
- [x] TMC decides on a date for the official End of Community Support for deegree 3.4.
- [x] EOL is announced on mailing list and website
- [ ] branch [3.4-main](https://github.com/deegree/deegree3/tree/3.4-main) is set to archived (read-only protected)

**Comment by tfr42** [comment]
The EOL date of 3.4 line will be 3 months after general availibility of 3.5.0 release. (TMC meeting 2022-07-27)

**Comment by tfr42** [comment]
- Community support for 3.4 line ends with release of 3.5
- EOL for 3.4 is 3 months after community support ends

| Action |  Before end of community support | End of community support (Date TBD) | End of Life (Date TBD) |  After EOL | 
|-----|-----|-----|-----|-----|
|Community PRs reviewed and integrated | :white_check_mark: | :x: | :x: | :x: |
|Community triggered releases | :white_check_mark: | :x: | :x: | :x: |
|Severe bugs affecting only the `3.4-main` branch will be fixed | :white_check_mark: | :white_check_mark: | :x: | :x: |
|Security vulnerability reports will be checked against the `3.4-main` branch | :white_check_mark: | :white_check_mark: | :x: | :x: |
|Severe / security issues triggered releases | :white_check_mark: | :white_check_mark: | :x: | :x: |
|Nightly and release build jobs available and active on Jenkins | :white_check_mark: | :white_check_mark: | :x: | :x: |
|Download of 3.4.x releases available from website and Nexus repo | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
|Documentation of 3.4.x releases available from website | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
|XML schema files of 3.4.x config files available from website | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |

**Comment by stephanr** [comment]
A possible simplification would be to use the releases in a tabular version similar to Ubuntu, like:

| deegree Version | Java Version | Release Date | End of regular Releases | End of Life |
|-------|-----|-----|-----|-----|
| 3.4.x |  1.8 | xxxx-xx-xx | yyyy-yy-yyy | zzzz-zz-zz |
| 3.5.x | 11  | yyyy-yy-yy |              |           |

**Comment by tfr42** [comment]
With the release of version 3.5 we will end providing regular releases for the 3.4 line. Releases from the `3.4-main` branch are highly unlikely, and only security related issues might be fixed and a bug fix version provided.

**Comment by tfr42** [comment]
Tabel with EOL is added to [wiki](../wiki/End-of-Life-and-Support-Matrix).

**Comment by tfr42** [comment]
Announcement sent to mailing list https://sourceforge.net/p/deegree/mailman/message/37876475/

**Comment by tfr42** [comment]
EoL for version 3.4 reached: https://sourceforge.net/p/deegree/mailman/message/48496925/
