### ISSUE TITLE
Dysfunctional link to mailinglist post in documentation

### ISSUE THREAD

**Issue by JohannaOtt** [deegree/deegree3#1374]
In [section 12.6.1 of the documentation](https://download.deegree.org/documentation/3.4.32/html/#_use_of_ttf_files_as_mark_symbols), [this link](http://osgeo-org.1560.n6.nabble.com/SE-Styling-MarkIndex-glyph-index-tt5022210.html#a5026571) to a mailinglist post is provided.
It is not resolving.

**Comment by tfr42** [comment]
Link was introduced with https://github.com/deegree/deegree3/commit/8f77bd9fb42414976bd1a6fee6d934813f8bcb1c.
The OSGeo Mirror of the mailing list is down, and web.archive.org didn't capture this post. But it may refer to this topic 
https://sourceforge.net/p/deegree/mailman/deegree-users/thread/20130110115808.GB3576%40theologicum.occamlabs.local/#msg30332311, looking on the pattern how the link was build for http://osgeo-org.1560.n6.nabble.com mirror. 
Hope that helps.

**Comment by JohannaOtt** [comment]
Thank you for the link - that seems to be the right one.

BTW: This can also be done with Word if I am not wrong: https://support.esri.com/en/technical-article/000004293

**Comment by tfr42** [comment]
Good to know. The section needs an update for sure.
