### ISSUE TITLE
Support for Java 17 (LTS)

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1375]
As runtime environment deegree should support Java 17 and Tomcat 10.1.

- [x] add new build job or stage with JDK 17 to Jenkins CI
- [x] #1401 
- [x] #1457 - upgrade JAXB from 2.3 to 3.0 or 4.0 
- [x] #1364

To compile with JDK 17 the following PR have been merged already:
- #1373
- #1372
- #1371

References: 
- #857
- https://tomcat.apache.org/whichversion.html

**Comment by tfr42** [comment]
It is planned to work on this issue during the FOSS4G 2022 Codesprint in Florence. Everyone is invited to join. Read more about the code sprint here: https://wiki.osgeo.org/wiki/FOSS4G_2022/Community_sprint#deegree

**Comment by tfr42** [comment]
The outcome of the activities during the codesprint at FOSS4G 2022 in Florence and the community hackevent of the FOSSGIS at the LinuxHotel in September 2022 was, that starting up of deegree fails due to missing/incompatible Servlet API as documented in #1401.

**Comment by tfr42** [comment]
The [TMC has the notion](https://github.com/deegree/deegree3/wiki/tmc-meeting-minutes-20230112) to work on this issue during the planned code sprint in autum 2023.

**Comment by tfr42** [comment]
The need to move towards JDK 17 is triggered by the planned EOL for JDK 11 (dates taken from https://endoflife.date):
- OpenJDK: 2023-09-30 (!)
- Oracle: 2023-09-30 (!)
- Bellsoft Liberica: 2024-10-31
- Adoptium (used on Jenkins to build and test): Oct. 2024
- Azul Zulu: 2026-09-30
- Coretto: Sep. 2027

**Comment by tfr42** [comment]
Helpfull page showing the changes in Java Core API: https://javaalmanac.io/

**Comment by jruhe-adesso** [comment]
Time sands...

**Comment by tfr42** [comment]
@jruhe-adesso Please check out our wiki page about sponsoring opportunities in 2024 https://github.com/deegree/deegree3/wiki/deegree-budget-2024

**Comment by jruhe-adesso** [comment]
I work for an IT service provider. I'll forward your link to the person responsible for the geo topic. Of course, I cannot promise anything. Thank you.

**Comment by tfr42** [comment]
Build job for JDK 17 added to Jenkins CI and was successfully run: https://buildserver.deegree.org/view/All/job/deegree-3.6-release-pipeline/

**Comment by tfr42** [comment]
The support of Java 17 was fully implemented with the version 3.6 of deegree webservices, see https://github.com/deegree/deegree3/wiki/End-of-Life-and-Support-Matrix for more information.
