### ISSUE TITLE
Replace @Tool annotations and remove outdated tools

### ISSUE THREAD

**Issue by lgoltz** [deegree/deegree3#1386]
Currently the following tools are available:

- deegree-tools/deegree-tools-alkis/src/main/java/org/deegree/tools/alkis/BackReferenceFixer.java:
  - @Tool(value = "adds inversDientZurDarstellungVon properties for GeoInfoDok 6.0.1 files")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/crs/ConfigurationConverger.java:
  - @Tool("Export the CoordinateSystems from a given Input format to a given Output format and place the result into an output File.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/crs/CRSInfo.java:
  - @Tool("Retrieve information about the availability|definition of a certain crs in deegree")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/crs/XMLCoordinateTransform.java:
  - @Tool("Converts the GML geometries inside an XML document from one SRS to another.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/crs/CoordinateTransform.java:
  - @Tool("Convert a point or a list of points from one SRS to another.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/crs/EPSGDBSynchronizer.java:
  - @Tool("Connects to the EPSG database at //hurricane/epsg, and for all projections (other objects to be added!) that have no CRS codetype in the CRS database, the codes are fetched from the EPSG database.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/gridifier/RasterTreeGridifier.java:
  - @Tool("Converts a deegree 2 raster tree into a grid of regular, non-overlapping raster cells encoded as raw RGB blobs, suitable for the WPVS.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/RTBClient.java:
  - @Tool("Builds a raster tree from a given set of rasters.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/converter/RasterConverter.java:
  - @Tool("Converts a raster from one type into another.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/TransformRaster.java:
  - @Tool("Transforms a raster with the given crs into another crs")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/services/wms/FeatureTypesToLayerTree.java:
  - @Tool(value = "generates a WMS layer tree/configuration file from a feature type hierarchy")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/metadata/ISO19139Validator.java:
  - @Tool(value = "Validates single metadata records or metadata records from directory against the ISO Schema.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/metadata/Harvester.java:
  - @Tool(value = "harvest metadata records and insert them in a CSW")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/rendering/r2d/se/StyleChecker.java:
  - @Tool(value = "This tool can be used to check and remove faulty styles in a WMS style database (PostgreSQL).")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/rendering/r2d/se/PostgreSQLImporter.java:
  - @Tool(value = "This tool can be used to import SLD/SE files into a WMS styles database.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/feature/persistence/FeatureStoreLoader.java:
  - @Tool("Imports feature datasets into a feature store")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/feature/gml/GMLSchemaAnalyzer.java:
  - @Tool("Prints an analysis of the feature type hierarchy defined in a GML application schema as well as information on the geometry element hierarchy.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/feature/gml/SchemaAnalyzer.java:
  - @Tool("Prints an analysis of the global element declarations in an XML schema and their content models.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/feature/gml/MappingShortener.java:
  - @Tool("Helps creating readable short versions of feature type / property names for mapping to db.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/feature/gml/ApplicationSchemaTool.java:
  - @Tool("Swiss Army knife for GML/deegree application schemas.")
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/commons/utils/ScanEncoding.java:
  - @Tool(value = "scans the argument files and tries to guess their encoding, treats dbf files specially")
- deegree-tools/deegree-tools-3d/src/main/java/org/deegree/tools/rendering/dem/filtering/DEMRasterFilterer.java:
  - @Tool("Applies a filter to a dem, which is loaded from a raster.")
- deegree-tools/deegree-tools-3d/src/main/java/org/deegree/tools/rendering/dem/builder/DEMDatasetGenerator.java:
  - @Tool("Generates DEM multiresolution datasets from rasters, suitable for the WPVS.")
- deegree-tools/deegree-tools-3d/src/main/java/org/deegree/tools/rendering/InteractiveWPVS.java:
  - @Tool("Reads in a configuration document for the deegree WPVS and allows the user to interactively navigate through the scene.")
- deegree-tools/deegree-tools-3d/src/main/java/org/deegree/tools/rendering/manager/ModelGeneralizor.java:
  - @Tool("Generates a generalization of a building by projecting the boundaries on a 2d plane and calculating a convex hull from them.")
- deegree-tools/deegree-tools-3d/src/main/java/org/deegree/tools/rendering/manager/PrototypeAssigner.java:
  - @Tool("Interface to the WPVS backend for assigning prototypes to QualityLevel in a world object model.")
- deegree-tools/deegree-tools-3d/src/main/java/org/deegree/tools/rendering/manager/DataManager.java:
  - @Tool("The DataManager inserts, updates and deletes 3d-objects in/from the WPVS backend")
- deegree-tools/deegree-tools-migration/src/main/java/org/deegree/tools/migration/WMSMigrator.java:
  - @Tool(value = "Converts a 3.1 or earlier WMS configuration to 3.2 style configurations. Currently only works for feature layers.")

**Comment by stephanr** [comment]
I would suggest changing the loading of the sub-tools from reflections to `ServiceLoader`.
Each tool would have to implement an interface and a service file has to be created. 
Then the description could be converted into a method or the annotations of the class could be kept using regular API.

**Comment by stephanr** [comment]
The implementation of Tool discovery was changed in #1642 from `org.reflections` to Java `ServiceLoader`.
With this change, the `@Tool` annotation is still used to create the list of available tools on CLI.

* #1642
