### ISSUE TITLE
Overwrite legend graphics for RemoteWMS layers

### ISSUE THREAD

**Issue by lgoltz** [deegree/deegree3#1393]
If a legend graphic from the RemoteWMS is unusable the legend graphic for the RemoteWMS layer should be configurable in the deegree workspace configuration. 

**Example:**

A RemoteWMS provides the layer _vegetation_ with the styles _colorful_ and _blackwhite_. 
In the configuration of the RemoteWMS layer the legend graphics of the styles can be overwritten:
 - style  _colorful_ => LegendGraphic vegetation_legendGraphic.png
 - style  _blackwhite_ => LegendGraphic https://example.de/vegetation_legendGraphic.png

**Enhancement RemoteWMSLayers configuration (proposal):**
```
<?xml version="1.0" encoding="UTF-8"?>
<RemoteWMSLayers xmlns="http://www.deegree.org/layers/remotewms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.deegree.org/layers/remotewms http://schemas.deegree.org/layers/remotewms/3.4.0/remotewms.xsd" configVersion="3.4.0">
  
  <RemoteWMSId>vegetation_wms</RemoteWMSId>
   
  <Layer>
    <OriginalName>vegetation</OriginalName>
    <Name>vegetation</Name>
    <Style>
      <OriginalName>colorful</OriginalName> <!-- original name of the style -->
      <LegendGraphic>vegetation_legendGraphic.png</LegendGraphic> <!-- reference to the legend graphic as local file -->
    <Style>
    <Style>
      <OriginalName>blackwhite</OriginalName> <!-- original name of the style -->
      <LegendGraphic>https://example.de/vegetation_legendGraphic.png</LegendGraphic> <!-- reference to the legend graphic as remote URL -->
    <Style>
  </Layer>

</RemoteWMSLayers>
```

**Hints**
- The legend graphic can be referenced as local file, or remote URL.
- It is not possible to create new (pseudo) styles.

**Comment by tfr42** [comment]
The TMC members have seen the config example and consider this extension as reasonable.
