### ISSUE TITLE
Migrate Maven Jobs to Pipeline Jobs

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1416]
Migrate snapshot/nighly build and release build from Maven job to pipeline job.

See https://plugins.jenkins.io/maven-plugin/#plugin-content-risks

**Comment by tfr42** [comment]
We stick with the maven release plugin which shall run in a separate build step but without executing all tests (all profiles need to be enabled).

**Comment by lgoltz** [comment]
3.5 release pipeline: https://github.com/deegree/deegree3/pull/1513

**Comment by stephanr** [comment]
Created Job https://buildserver.deegree.org/job/deegree-3.5-release-pipeline/ as Copy from deegree-3.4-release-pipeline
Disabled Job https://buildserver.deegree.org/job/deegree-3.5-release/
