### ISSUE TITLE
GetMap request with WMS 1.1.1 and EPSG:4326 leads to erroneous image

### ISSUE THREAD

**Issue by dstenger** [deegree/deegree3#1455]
For example, a black image is returned when requesting GetMap with WMS 1.1.1 and EPSG:4326.
Same request with WMS 1.3.0 returns the expected image.

This problem just occurs when the style sets `uom` to `metre` (or `foot`).

The root cause of this problem seems to be related to the switched axis order. In WMS 1.3.0 the axis order is YX which corresponds to the specification of EPSG:4326. However, the WMS 1.1.1 switches the axis order (XY) which most likely leads to the unexpected returned image.

**Comment by dstenger** [comment]
This commit might already fix the problem: https://github.com/deegree/deegree3/blob/86bbe9165172fea0f1ef8c2e701d5eeebcdfa941/deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/RenderHelper.java#L316

We will do further testing and report back in this issue.

**Comment by lgoltz** [comment]
The described bug is fixed. Successfully tested with current 3.5.0-SNAPSHOT.
