### ISSUE TITLE
Current issues of the deegree 3.5 console

### ISSUE THREAD

**Issue by julianzz98** [deegree/deegree3#1470]
The following known issues for the console can be noted, categorized by component:

### Metadata stores:

* [x] The naming of type and example templates is inconsistent

### Tile stores:

* [x] The type 'MergingTileStore' does not have a schemaLocation specified

### Layers:

* [x] For the type 'CoverageLayer', the console uses the example template of a 'TileLayer' and vice versa

### Themes

* [x] The type 'RemoteWMS only has a local schemaLocation specified:
  * `xsi:schemaLocation="http://www.deegree.org/themes/remotewms remotewms.xsd"`

### Provider

* [x]  The type 'FME-Server' does not have a example template, results in an error

**Comment by julianzz98** [comment]
An initial commit was performed, fixing following issues:

### Metadata stores:

- [x] The naming of type and example templates is inconsistent

### Layers:

- [x] For the type 'CoverageLayer', the console uses the example template of a 'TileLayer' and vice versa

### Provider

- [x] The type 'FME-Server' does not have a example template, results in an error

**Comment by lgoltz** [comment]
Invalid example reported in  #1491

**Comment by lgoltz** [comment]
invalid link in RemoteWMTS moved to 1492
