### ISSUE TITLE
WFS sets namespace prefix in title of a FeatureType

### ISSUE THREAD

**Issue by dstenger** [deegree/deegree3#1481]
Is it really useful that the namespace prefix is set in title?
When reviewing the [spec](https://docs.ogc.org/is/09-025r2/09-025r2.html), I do not find any hint that the prefix must exist in title.
In some cases, users might prefer to omit the prefix to improve the readability of the title.

Relevant code:
https://github.com/deegree/deegree3/blob/275ffa93c99b75696ea96da9426d3c6069d92f7e/deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/GetCapabilitiesHandler.java#L273-L277

**Comment by copierrj** [comment]
We discussed this issue during a TMC meeting and there was consensus that titles are for humans (and not for machines) and therefore do not need a prefix.
