### ISSUE TITLE
Example template of type 'RemoteWMTS' contains invalid WMTS reference 

### ISSUE THREAD

**Issue by lgoltz** [deegree/deegree3#1492]
The example template of type 'RemoteWMTS' contains an invalid link:
`Error performing GET request on 'http://v2.suite.opengeo.org/geoserver/gwc/service/wmts?service=WMTS&version=1.0.0&request=GetCapabilities': Connect to v2.suite.opengeo.org:80 timed out`

**Comment by julianzz98** [comment]
An available example can be found here https://tpwd.texas.gov/gis/programs/landscape-ecology/web-map-tile-service-wmts

**Comment by tfr42** [comment]
I do propose one of the WMTS provided by BKG: http://gdz.bkg.bund.de/index.php/default/webdienste/basemap-webdienste.html

**Comment by copierrj** [comment]
Another suggestion: https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0?request=GetCapabilities&service=WMTS
