### ISSUE TITLE
Add APIKEY/Token authentication mechanism

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1494]
Currently deegree webservices WAR file comes with a security contraint enabled which protects access to the REST API of deegree by BASIC authentication. Users of deegree need to configure their servlet container to link to a realm with authorization information (such as `tomcat-users.xml`).

To harmonize the webapps of deegree webservices and deegree OGC API the webservices webapp shall support [APIKEY/Token based authentication](https://github.com/deegree/deegree3/pull/1180) as in deegree OGC API webapp (see https://github.com/deegree/deegree-ogcapi/issues/70).

Documentation needs to be improved how to setup and configure security.

**Comment by stephanr** [comment]
see
* #1498

**Comment by tfr42** [comment]
wiki page https://github.com/deegree/deegree3/wiki/Upgrading-deegree-webservices#changes-in-behavior updated

**Comment by tfr42** [comment]
Issue is resolved.
