### ISSUE TITLE
Create link for the deegree online user documentation with version = latest

### ISSUE THREAD

**Issue by julianzz98** [deegree/deegree3#1557]
The deegree online user documentation does not have an online where the version is latest. This therefore creates the problem that links in for example presentations and handouts are version specific and therefore misleading. 

A solution could be similar to the one that GeoServer uses: https://docs.geoserver.org/latest/en/user/introduction/index.html#introduction

**Comment by tfr42** [comment]
The documentation for the most recent version (latest) is published under the following link: https://download.deegree.org/documentation/current/html/

**Comment by tfr42** [comment]
See https://github.com/deegree/deegree3/wiki/Releasing-deegree#publish-the-handbook how it's created.
