### ISSUE TITLE
Add support for JAXB3 or higher

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1569]
Add support for JAXB 3 or higher

**Comment by tfr42** [comment]
Pull request #1457 needs rebase and rework.

**Comment by laurentschoelens** [comment]
Hi @tfr42 
V3 of jaxb-maven-plugin has been released yesterday and should be available soon on maven central
Regards

**Comment by laurentschoelens** [comment]
Hi @tfr42 : depending of targeted jaxb-ri (v3 or v4), you can use the v3 or v4 version of the jaxb-tools :)
See [migration guide](https://github.com/highsource/jaxb-tools/wiki/JAXB-Tools-Migration-Guide) for help
