### ISSUE TITLE
Can a gml:polygon contain an gml:arc? 

### ISSUE THREAD

**Issue by johan974** [deegree/deegree3#1574]
Deegree-core:

Deegree gives an error on processing a gml:Polygon with a gml:Arc. Is this correct? 

> "Cannot determine control points for ring, contains non-linear segments"?

Please have a look at https://gis.stackexchange.com/questions/466562/deegree-how-to-cope-with-gml-with-an-arc-cannot-determine-control-points-for?noredirect=1#comment762649_466562. 

Suggested is that poygons can only contain straight lines. Is this true? 

This is what I see: http://www.datypic.com/sc/niem21/e-gml32_Polygon.html. You can find a path from polygon > exterior > ring > curveMember > curve > segments > arc. 

I see in our system having strict XML/XSD checks that for many years files with gml:Polygons process arcs. 

We work most of the time with gml3.1. 

For 3.1 and 3.2?

An example is: 

```
<gml:Polygon>
  <gml:exterior>
    <gml:Ring>
      <gml:curveMember>
        <gml:Curve>
          <gml:segments>
            <gml:LineStringSegment>
              <gml:posList>44.605 773.516 40.806 775.320</gml:posList>
            </gml:LineStringSegment>
            <gml:LineStringSegment>
              <gml:posList>40.806 775.320 38.522 759.491</gml:posList>
            </gml:LineStringSegment>
            <gml:LineStringSegment>
              <gml:posList>38.522 759.491 45.178 773.702</gml:posList>
            </gml:LineStringSegment>
            <gml:Arc>
              <gml:posList>45.178 773.702 44.930 773.491 44.605 773.516</gml:posList>
            </gml:Arc>
          </gml:segments>
        </gml:Curve>
      </gml:curveMember>
    </gml:Ring>
  </gml:exterior>
</gml:Polygon>
```
What about other libraries? For example, the pdok/gml3-jts, processes the geometry.

**Comment by tfr42** [comment]
That questions looks more like one which the [OGC GML SWIG members](https://www.ogc.org/about-ogc/committees/swg/) would like to answer.
Did you checked also the spec https://www.ogc.org/standard/gml/ and related test suite https://github.com/opengeospatial/ets-gml32 for more information? 
If you would like to test yourself how deegree processes GML geometries like this, just add a valid GML file into the folder https://github.com/deegree/deegree3/tree/main/deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry and add a unit test to https://github.com/deegree/deegree3/blob/main/deegree-core/deegree-core-base/src/test/java/org/deegree/geometry/validation/GeometryValidatorTest.java. If this runs into an error and you consider this as an bug in deegree please re-open the ticket and describe the bug in detail.

And here a general remark, for inquires like this you found yourself already the right place at [https://gis.stackexchange.com/](https://gis.stackexchange.com/questions/tagged/deegree). See https://www.deegree.org/community/ and https://github.com/deegree/deegree3/wiki/Bug-Report-writing-Guidelines for further information. Thank you for your understanding.
