### ISSUE TITLE
Add support for Json output format to WMS GetFeatureInfo

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1582]
deegree WMS GetFeatureInfo operation shall support for Json/GeoJson as output format.

**Comment by lgoltz** [comment]
Any ideas how to enable GeoJSON as output format? GeoJSON does not require a File, XSLTFile and Serializer  [1]. Simple proposal:
```
<FeatureInfoFormats>
  <GetFeatureInfoFormat>
    <GeoJson>true</GeoJson>
    <Format>application/geo+json</Format>
  </GetFeatureInfoFormat>
</FeatureInfoFormats>
```

[1] https://schemas.deegree.org/services/wms/3.4.0/wms_configuration.xsd

**Comment by copierrj** [comment]
Looks great!

A few suggestions:
- perhaps better to use an empty element <GeoJson/> because it is only identifying the type of output and setting it to false doesn't seem to make sense. 
- would it be a good idea to be able to configure the output coordinate system?

**Comment by stephanr** [comment]
I think it might also make sense to align the configuration with the WFS configuration, as i think deegree supports also outputting geomtries as well, with a vendor-specific parameter.

https://github.com/deegree/deegree3/blob/1fbb5031ed99a65381a0e7ceb681b2fbb552c10d/deegree-services/deegree-services-wfs/src/main/resources/META-INF/schemas/services/wfs/wfs_configuration.xsd#L173
