### ISSUE TITLE
String.replaceAll and String.replaceFirst are known to be slow due to Pattern compiles. Prefer Pattern.matches().replaceAll()

### ISSUE THREAD

**Issue by kad-vetteh** [deegree/deegree3#1633]
String method  'replaceAll' is implemented as:
```
 public String replaceAll(String regex, String replacement) {
    return Pattern.compile(regex).matcher(this).replaceAll(replacement);
}
```

String method 'replaceFirst' is implemented as:
 ```
 public String replaceFirst(String regex, String replacement) {
      return Pattern.compile(regex).matcher(this).replaceFirst(replacement);
 }
```

These methods provide a convenience method for creating a Pattern using Pattern.compile(), The Pattern.compile() method is slow, and should be avoided. The best way to do this is to statically compile the Pattern, and use the matcher from the static compiled pattern. This could improve performance a lot when the String.replaceAll method or String.replaceFirst method is called in the wrong place. (i.e. in a for loop). The pattern will be compiled on every invocation of the replaceAll or replaceFirst method.

Find and replace the method replaceAll and replaceFirst and change them into static compiled Patterns.

replaceAll Before (slow)
```
public void method(String str)  {
     String output = str.replaceAll("regex", "replacement");
}  
```

replaceAll After (improved performance)
```
private final static Pattern PATTERN_NAME = Pattern.compile("regex");

public void method(String str)  {
     String output = PATTERN_NAME.matches(str).replaceAll("replacement");
}  
```

replaceFirst Before (slow)
```
public void method(String str)  {
     String output = str.replaceFirst("regex", "replacement");
}  
```

replaceFirst After (improved performance)
```
private final static Pattern PATTERN_NAME = Pattern.compile("regex");

public void method(String str)  {
     String output = PATTERN_NAME.matches(str).replaceFirst("replacement");
}  
```

**Comment by tfr42** [comment]
@kad-vetteh Thanks for the proposal. Can you tell us a little more about the context when this will effect deegree at runtime? And of course any source code and runtime improvement is welcome. So, we will be happy, if you are preparing a pull request.

**Comment by kad-vetteh** [comment]
@tfr42 I have attached a draft pull request: https://github.com/deegree/deegree3/pull/1639 
I was looking in the code recently, and noticed the methods, feel free to try if it makes some difference.
