### ISSUE TITLE
Unable to insert negative coordinate values in MS SQL Server

### ISSUE THREAD

**Issue by datsnew** [deegree/deegree3#1689]
Using deegree-webservices-3.5.7 and SQL Server version 16.0.4120.1, deegree outputs a UTF-16 encoded minus sign (0x2212) in WKT geometry which MS SQL Server is unable to parse.

The transaction sent into deegree has a regular minus sign (-) while the query executed by SQL Server contains a UTF-16 encoded minus sign  (0x2212) which SQL Server is unable to parse with the geometry::Parse function.

I have boiled down the query from the sql log to this(with the UTF-16 0x2212 minus character):

Select geometry::Parse(N'Point (123 −123)')    

Which leads to this error because it cannot recognize −123 as a negative number.
Msg 6522, Level 16, State 1, Line 5
A .NET Framework error occurred during execution of user-defined routine or aggregate "geometry": 
System.FormatException: 24141: A number is expected at position 15 of the input. The input has −123.
System.FormatException: 
   at Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeDouble()
   at Microsoft.SqlServer.Types.WellKnownTextReader.ParsePointText(Boolean parseParentheses)
   at Microsoft.SqlServer.Types.WellKnownTextReader.ParseTaggedText(OpenGisType type)
   at Microsoft.SqlServer.Types.WellKnownTextReader.Read(OpenGisType type, Int32 srid)
   at Microsoft.SqlServer.Types.SqlGeometry.GeometryFromText(OpenGisType type, SqlChars text, Int32 srid)
   at Microsoft.SqlServer.Types.SqlGeometry.Parse(SqlString s)

I have tried changing sql server collations, and also tried to set CharacterSet property in the JDBC connection string, but I cannot get SQL Server to parse the negative value.

Attached files to recreate the problem (create table in sql file, FeatureStore.xml and transaction in xml file)

[table.zip](https://github.com/deegree/deegree3/files/15499228/table.zip)

**Comment by larseggan** [comment]
Anyone looking at this bug? Very critical for the Norwegian use of deegree WFS-T.
@datsnew has tried fixing it locally without sucsess.

**Comment by larseggan** [comment]
@datsnew has fixed it locally now in mssqlgeometryconverter.java.
A pull request will be created.

 Override
	public void setParticle(PreparedStatement stmt, Geometry particle, int paramIndex) throws SQLException {
		if (particle == null) {
			stmt.setObject(paramIndex, null);
			return;
		}
		particle = getCompatibleGeometry(particle);
		if (is2d) {
			try {
				stmt.setBytes(paramIndex, WKBWriter.write(particle));
			}
			catch (Throwable e) {
				throw new SQLException(e);
			}
		}
		**_else {
            // Added Replace UTF minus sign with hyphen-minus in particle
			stmt.setString(paramIndex, WKTWriter.write(particle).replace('\u2212', '\u002D'));
		}_**
	}

**Comment by stephanr** [comment]
In today's TMC-Meeting we discussed this again and found that this issue seems to be related to the used locale of the system.

Could you try to test if this issue also occurs when your container (tomcat) runs with English as it default locale?
For example, adding the following parameters ` -Duser.country=GB -Duser.language=en`.

See also:
  * https://github.com/adoptium/adoptium-support/issues/709
  * https://bugs.openjdk.org/browse/JDK-8302552

**Comment by datsnew** [comment]
Thank you. I did a test with the suggested parameters and it worked. So it seams that the problem indeed is related to the default locale. The linked issues looks like this was introduced in JDK17, but we experiencing the same behavior with JDK 11.

Thank you for taking the time to look into and discuss this issue.
