### ISSUE TITLE
Migrate Spring, Spring Boot and Spring Batch

### ISSUE THREAD

**Issue by lgoltz** [deegree/deegree3#1690]
* Spring  5.3 -> 6,1
 * Spring Batch 4.3 -> 5.1
 * Spring Boot 2.7 -> 3.3
The upgrade to Spring Boot 3.x will require Java 17.

**Comment by stephanr** [comment]
From spring boot dependencies at https://search.maven.org/artifact/org.springframework.boot/spring-boot-dependencies/3.3.0/pom the supposed versions are:

spring-boot 3.3.0
spring-batch 5.1.2
spring-framework 6.1.8
