### ISSUE TITLE
Cannot find see layers button to view default layers in simple web client

### ISSUE THREAD

**Issue by Zia-** [deegree/deegree3#1750]
Hi there,

I'm using the exact tutorial explained here https://download.deegree.org/documentation/3.5.8/html/#anchor-configuration-restapi

However, it says I should see **see layers** button once _deegree-workspace-utah_ has been loaded; which I can't find in my GUI below. Kindly help me if I'm missing something. I'm using _docker.io/deegree/deegree3-docker:3.5_

![image](https://github.com/user-attachments/assets/a4a5e275-25f4-499c-bb09-cacf0f43796c)

It looks like all layers are loaded correctly. Wondering, what the wms url looks like for _layer_tile_utah_ortho_ layer.

Thanks a lot.

**Comment by julianzz98** [comment]
Hello @Zia-, thank you for getting into and using deegree! We always appreciate new users here!

You likely followed the documentation starting from chapter [3. Getting started](https://download.deegree.org/documentation/3.5.8/html/#anchor-lightly), and that’s a great and right approach. However, please note that the current documentation lags in some areas, particularly regarding the layer preview functionality in the GUI (or web console).

With the release of deegree 3.5, we removed the ability to preview layers and send requests within the GUI. Additionally, PR [#1607](https://github.com/deegree/deegree3/pull/1607) removed the corresponding buttons. Background for these changes is the age of the framework used to create the GUI as well as user feedback.

Unfortunately, the documentation is still largely based on version 3.4.x, especially in sections like the examples and getting started guide. We are aware of this issue and are working to update non-technical information as soon as we have the resources available.

Regarding your last question, here is an example request for the WMS of the Utah workspace serving the `layer_tile_utah_ortho` layer:
* http://localhost:8080/deegree-webservices/services/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=40.18441766000000115%2C-111.6917084100000039%2C40.24906967804347602%2C-111.6155697137130431&CRS=EPSG%3A4326&WIDTH=850&HEIGHT=721&LAYERS=orthophoto&STYLES=&FORMAT=image%2Fpng&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi%3A96&TRANSPARENT=TRUE 

The response will return the following orthophoto: 
![image](https://github.com/user-attachments/assets/9a517816-2070-48c3-9362-a5fa85d1f5d6)

To get this request, I added the WMS to QGIS and opened the selected layer:
![image](https://github.com/user-attachments/assets/0acd397a-15ba-4fb5-9bdb-70081f558511)

**Comment by tfr42** [comment]
Related issue #1543.

**Comment by Zia-** [comment]
@julianzz98 : That's exactly what I was looking for. Thanks a lot. 

Just more question: Do we have WCS support available/planned in deegree3?

**Comment by julianzz98** [comment]
@Zia- during our TMC meeting we stumbled upon issue https://github.com/deegree/deegree3/issues/597. 

I would conclude that while some functionality for WCS 1.0 support is available, there is no accompanying documentation. As mentioned in the referenced issue, alternative solutions are available.

**Comment by Zia-** [comment]
@julianzz98 : Thanks a lot. All help much appreciated.
