### ISSUE TITLE
WCS support in deegree

### ISSUE THREAD

**Issue by dstenger** [deegree/deegree3#1753]
The website of deegree https://www.deegree.org/ states on the home site that "Web Coverage Service (WCS)" is supported (see second paragraph right after Download button).

However, the documentation does not mention any WCS support: https://www.deegree.org/documentation/

**Comment by stephanr** [comment]
The pull request https://github.com/deegree/deegree.github.io/pull/5 was created to remove the misleading references on the homepage if the TMC decides to do so.

**Comment by copierrj** [comment]
The TMC decided to officially retire WCS support. There is no documentation and the implementation has not been properly maintained.
