### ISSUE TITLE
[v.3.4-pre15] Resource configuration file disappears after Deactivate/Activate

### ISSUE THREAD

**Issue by mmacata** [deegree/deegree3#330]
Expected behaviour:
After deactivation and activation the resource is still visible.

Current behaviour:
Reproduce with deegree-workspace-wps, click on webservices-services, then deactivate or activate
The resource disappears and a reload of the workspace is necessary to make it visible again.

Tested with Firefox (v.31.0) in Ubuntu 12.04

**Comment by lgoltz** [comment]
Bug cannot be reproduced with 3.4-RC3. Testes as described above with different resources.
