### ISSUE TITLE
[BUG] [v.3.4-pre15]  deegree-workspace-wps: Unable to find matching navigation case

### ISSUE THREAD

**Issue by NielsWalen** [deegree/deegree3#331]
Acctual behavior:
If you chose in deegree-workspace-wps the provider (processes) and click at one process on edit, followed by clicking on save the warning/ failure [1] appears.

Expected behavior:
If you edit an process provider you can save the process provider without failure/warning.

[1]
Unable to find matching navigation case with from-view-id '/console/generic/xmleditor.xhtml' for action '${xmlEditorBean.save}' with outcome 'null'

Tested with Firefox and Ubuntu 12.04

**Comment by tfr42** [comment]
Fixed in 3.4-pre16
