### ISSUE TITLE
[BUG] [v.3.4-pre15] deegree-workspace-inspire: java.lang.NullPointerException at GDALLayerStoreProvider

### ISSUE THREAD

**Issue by NielsWalen** [deegree/deegree3#332]
Actual behavior:

If I create a new layer by GUI with Type GDALLayerStoreProvider and an Identifier but without XML config template, the following screen message [1] appears.

[1]
An Error Occurred:
java.lang.NullPointerException
- Stack Trace
- Component Tree
- Scoped Variables

Expected behavior:

If I create a new layer by GUI with Type GDALLayerStoreProvider and an Identifier but without XML config template, I want to get a specific error message.

Hints:

As Identifier i have chosen: test2
If i chose any other type the message [2] appears.

[2]
j_idt78:j_idt87: Validation Error: Value is not valid

Tested with Firefox and Ubuntu 12.04

**Comment by lgoltz** [comment]
Tested with 3.4-RC3. It is not longer possible to create a  GDALLayerStoreProvider without template.   Resource could be created.
