### ISSUE TITLE
[v.3.4-pre15] WMS layer-overview shows less layers than in v.3.3.8

### ISSUE THREAD

**Issue by mmacata** [deegree/deegree3#334]
Expected behaviour:
Layer-overview shows all necessary layers

Current behaviour:
Reproduce with deegree-workspace-utah, got to 'see layers' and look at the 'overlays' with v.3.4 and v.3.3.8. In 3.3.8 there is one more layer listed ("springscascaded").

Tested with Firefox (v.31.0) in Ubuntu 12.04

**Comment by julianzz98** [comment]
As of deegree version 3.5.0 the functionality to see layers via the console (button 'see layers') was removed. Therefore I am closing this issue.
