### ISSUE TITLE
Edit of SQLFeatureStore failed

### ISSUE THREAD

**Issue by dbretschneider** [deegree/deegree3#335]
### Actual Behaviour

If I want to edit a configuration based on SQL FeatureStore, I get a [NullPointerException](https://gist.github.com/dbretschneider/da5be93ccd494c7a4bd5).
### Expected Behaviour

If I want to edit a configuration based on SQL FeatureStore, I will get into the XML editing mode.
### Additional information

I have set the log4j level of _log4j.logger.org.deegree.feature_ to _TRACE_. Tested with deegree 3.4-pre14. You will find the log on GIST:
- https://gist.github.com/dbretschneider/da5be93ccd494c7a4bd5

**Comment by lgoltz** [comment]
Fixed by #335 (in https://github.com/deegree/deegree3/issues/335#issuecomment-51484404  the building of deegree-webservices is missing).
