### ISSUE TITLE
[BUG] [v3.4pre14] Load GetCapabilities after deploy needs 1-2 minutes

### ISSUE THREAD

**Issue by gu-LGB** [deegree/deegree3#337]
After deploy the application needs about 1 to 2 minutes to call the "GetCapabilities". Thereafter, the application behaves as expected.
The problem was observed with Tomcat 6 and Tomcat 7.

**Comment by lgoltz** [comment]
@gu-LGB Does the error still occure?

**Comment by gu-LGB** [comment]
No, the error does not exist anymore (tested with 3.4 pre23).
