### ISSUE TITLE
[BUG] [v.3.4-pre15]  feature (utah Workspace): Unable to find matching navigation case

### ISSUE THREAD

**Issue by NielsWalen** [deegree/deegree3#338]
Acctual behavior:
If you navigate in deegree-workspace-utah to the faeature utah_airports, followed by clicking on Loader the warning/ failure [1] appears.

Expected behavior:
If you click on Loader at  deegree-workspace-utah feature (utah_airports) the action happens without failure/warning.

[1]  Unable to find matching navigation case with from-view-id '/console/datastore/feature/index.xhtml' for action '#{config.openLoader}' with outcome '/console/featurestore/loader'

Tested with Firefox and Ubuntu 12.04.

**Comment by lgoltz** [comment]
Bug cannot be reproduced with 3.4-RC5.
