### ISSUE TITLE
[v.3.4-pre15] Creation of new service fails

### ISSUE THREAD

**Issue by mmacata** [deegree/deegree3#339]
<b>Current Behaviour:</b>
When creating a new service in the menu 'webservices' - 'services' - 'Create new' and typing in an Identifier an error occurs when clicking 'create new' for the following service types: WPS, CSW, WMS, WMTS.
The error is:
<i>java.lang.NullPointerException</i>

<b>Expected Behaviour:</b>
When creating a new service I can start editing the xml resource or a specific error message appears 

Tested with Firefox (v.31.0) in Ubuntu 12.04

**Comment by julianzz98** [comment]
In deegree version 3.5.3, the reported issue can not be replicated. Therefore the issue is considered as fixed.
