### ISSUE TITLE
[BUG] [v.3.4-pre15]  Changing workspace with click on start has no impact on send requests

### ISSUE THREAD

**Issue by NielsWalen** [deegree/deegree3#348]
Actual behavior:

If you change of a running workspace to another with clicking start to the other workspace, send requests has still the old workspace values. First if you refresh your latest started workspace send requests values are updated to the current workspace.

Expected behavior:

If you start a workspace all configured values are loaded corresponding to the started workspace.

Tested with Firefox and Ubuntu 12.04.

**Comment by lgoltz** [comment]
Tested successfully with 3.4-RC3.
