### ISSUE TITLE
Problem logging into services console when running deegree-webservices using mvn tomcat:run

### ISSUE THREAD

**Issue by MrSnyder** [deegree/deegree3#378]
After fixing #349, the deegree-webservices module does not longer work correctly when started via

`mvn tomcat:run`

The most obvious problem is that it's not possible to log in to the services console any more.

However, everything works as expected in case the module is run in Eclipse or via

`mvn tomcat:run-war`

**Comment by tfr42** [comment]
The Tomcat Maven plugin has been replaced by Jetty Maven plugin with PR #1169.
Issue closed.
