### ISSUE TITLE
Creation of new configuration file failed over deegree console

### ISSUE THREAD

**Issue by dbretschneider** [deegree/deegree3#385]
### Actual Behaviour

After merging all pull request during the code sprint in berlin it is not possible to create some configuration file like:
- webservices
- data stores
  - coverage (raster)
  - feature (shape)
  - metadata (ISO19139-Memory)
- JDBC Connection
- Layer

The full log of the NullPointerException you will find in [GitHub GIST](https://gist.github.com/dbretschneider/aec003a5a3fa1071de62)
### Expected Behaviour

It is possible to create the configuration over deegree console. After click `create new` the xml editor will open.
### Additional information

Caused by [#363](https://github.com/copierrj/deegree3/commit/7aa0e734898880a9df0f235e13cb8f436ae6e356).

**Comment by lgoltz** [comment]
Problem does not occur in 3.4-RC5.
