### ISSUE TITLE
[WMTS 1.0.0] Wrong exceptionCode / no locator while executing a request with a invalid request value

### ISSUE THREAD

**Issue by dbretschneider** [deegree/deegree3#417]
If I execute the CITE test *wmts:Server.KVP.GET.InvalidRequest* against [deegree webservices 3.4-pre15] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/), deegree responds with a wrong exceptionCode and no locator.

### Actual behavior ###
 * ExceptionCode: *InvalidRequest*
 * Locator is missing
 * [Invalid request] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/services/wmts?service=WMTS&request=GetBOGUS)

### Expected behavior ###
 * ExceptionCode value: *InvalidParameterValue*
 * Locator value: *request*
 * Code: *400*
 * Message: *Bad request*

See WMTS 1.0.0 Spec, table 21

**Comment by stephanr** [comment]
Resolved by #465
