### ISSUE TITLE
[WMTS 1.0.0] Wrong HTTP Status Code and exceptionCode / no locator while executing a GetTile request with a non-existent style

### ISSUE THREAD

**Issue by dbretschneider** [deegree/deegree3#418]
If I execute the CITE test *wmts:Server.KVP.GET.GetTile.Invalid.Tile.Style* against [deegree webservices 3.4-pre15] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/), deegree responds with a wrong HTTP Status Code, exceptionCode and no locator.

### Actual behavior ###
 * Code: *200*
 * [Request with non-existent style] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/services/wmts?service=WMTS&request=GetTile&version=1.0.0&layer=cite&style=BogusForTest&format=image/png&TileMatrixSet=InspireCrs84Quad&TileMatrix=8&TileRow=127&TileCol=255)

### Expected behavior ###
 * ExceptionCode value: *InvalidParameterValue*
 * Locator value: *Style*
 * Code: *400*
 * Message: *Bad request*

See WMTS 1.0.0 Spec, table 24

**Comment by stephanr** [comment]
Resolved by #465
