### ISSUE TITLE
[WMTS 1.0.0] Wrong exceptionCode / no locator while executing a request with a invalid layer value

### ISSUE THREAD

**Issue by dbretschneider** [deegree/deegree3#419]
If I execute the CITE test *wmts:Server.KVP.GET.GetFeatureInfo.Invalid.Layer* against [deegree webservices 3.4-pre15] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/), deegree responds with a wrong exceptionCode and no locator.

### Actual behavior ###
 * ExceptionCode value: *LayerNotDefined*
 * [Request with non-existent layer] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/services/wmts?service=WMTS&request=GetFeatureInfo&version=1.0.0&layer=BogusForTest&style=default&format=image/png&infoFormat=application/gml+xml; version=3.0&TileMatrixSet=InspireCrs84Quad&TileMatrix=8&TileRow=127&TileCol=255&J=127&I=127)

### Expected behavior ###
 * ExceptionCode value: *InvalidParameterValue*
 * Locator value: *layer*
 * Code: *400*
 * Message: *Bad request*

See WMTS 1.0.0 Spec, table 24

**Comment by stephanr** [comment]
Resolved by #465
