### ISSUE TITLE
[WMTS 1.0.0] No locator while executing a request with a missing parameter

### ISSUE THREAD

**Issue by dbretschneider** [deegree/deegree3#424]
If I execute the CITE test *wmts:Server.KVP.GET.GetTile.Missing* against [deegree webservices 3.4-pre15] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/), deegree responds with no locator.

### Actual behavior ###
 * ExceptionCode value: *InvalidParameterValue*
 * Locator is missing
 * [Request with no layer parameter] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/services/wmts?service=WMTS&request=GetTile&version=1.0.0&style=default&format=image/png&TileMatrixSet=InspireCrs84Quad&TileMatrix=8&TileRow=127&TileCol=255)

### Expected behavior ###
 * ExceptionCode value: *MissingParameterValue*
 * Locator value of the name of the missing parameter
 * Code: *400*
 * Message: *Bad request*

See WMTS 1.0.0 Spec, table 24

**Comment by stephanr** [comment]
Resolved by #465
