### ISSUE TITLE
[WMTS 1.0.0] Wrong ExceptionCode / No locator while executing a request with a non-existent InfoFormat value

### ISSUE THREAD

**Issue by dbretschneider** [deegree/deegree3#425]
If I execute the CITE test *wmts:Server.KVP.GET.GetFeatureInfo.Invalid.InfoFormat* against [deegree webservices 3.4-pre15] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/), deegree responds with a wrong exception code and no locator.

### Actual behavior ###
 * ExceptionCode value: *NoApplicableCode*
 * Locator is missing
 * [Request with non-existent InfoFormat value] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/services/wmts?service=WMTS&request=GetFeatureInfo&version=1.0.0&layer=cite&style=default&format=image/png&infoFormat=BogusForTest&TileMatrixSet=InspireCrs84Quad&TileMatrix=8&TileRow=127&TileCol=255&J=127&I=127)

### Expected behavior ###
 * ExceptionCode value: *InvalidParameterValue*
 * Locator: *InfoFormat*
 * Code: *400*
 * Message: *Bad request*

See WMTS 1.0.0 Spec, table 27

**Comment by stephanr** [comment]
Resolved by #465
