### ISSUE TITLE
[WMTS 1.0.0] Wrong HTTP Status Code and exceptionCode / no locator while executing a GetFeatureInfo request with an invalid Pixel Row J

### ISSUE THREAD

**Issue by dbretschneider** [deegree/deegree3#434]
If I execute the CITE test *wmts:Server.KVP.GET.GetFeatureInfo.Invalid.Pixel.Row.J* against [deegree webservices 3.4-pre15] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/), deegree responds with a wrong HTTP Status Code, exceptionCode and no locator.

### Actual behavior ###
 * Code: *500*
 * [Request with invalid Pixel Row J] (http://cite.lat-lon.de/deegree-webservices-3.4-pre15/services/wmts?service=WMTS&request=GetFeatureInfo&version=1.0.0&layer=cite&style=default&format=image/png&infoFormat=application/gml+xml; version=3.0&TileMatrixSet=InspireCrs84Quad&TileMatrix=8&TileRow=127&TileCol=255&J=256&I=127)

### Expected behavior ###
 * ExceptionCode value: *TileOutOfRange*
 * Locator value: *J*
 * Code: *400*
 * Message: *Bad request*

See WMTS 1.0.0 Spec, table 26

**Comment by stephanr** [comment]
Resolved by #465
