### ISSUE TITLE
New JDBC configuration does not work with the modules directory

### ISSUE THREAD

**Issue by dbretschneider** [deegree/deegree3#444]
New the JDBC configuration for deegree webservices 3.4 does not work, if using the modules directory of the workspace.

____

I have tested some variations of different deegree versions with new and old JDBC configuration.

For the first test, I have added the Oracle JAR in the modules directory of the workspace:

 * deegree webservices 3.3.12 with old JDBC configuration works
 * deegree webservices 3.4-pre15 with old JDBC configuration works
 * deegree webservices 3.4-pre15 with new JDBC configuration does not work
```xml
[08:42:58] ERROR: [DefaultWorkspace] Unable to build resource ConnectionProviderProvider:oracle: Error connecting to database: Cannot load JDBC driver class 'oracle.jdbc.OracleDriver'
```

For the second test, I have added the Oracle JAR into WEB-INF/lib directory of the webapp:

 * deegree webservices 3.3.12 with old JDBC configuration works
 * deegree webservices 3.4-pre15 with old JDBC configuration works
 * deegree webservices 3.4-pre15 with new JDBC configuration works

**Comment by tfr42** [comment]
PR #621 fixes or clarifies the usage of the modules directory. From *3.4.0* on placing a JDBC driver in deegree modules directory is **not supported** anymore!
