### ISSUE TITLE
Dataset metadata configuration for layers and themes 

### ISSUE THREAD

**Issue by MrSnyder** [deegree/deegree3#445]
The workspace currently supports configuration of metadata (title, abstract, ...) for layers and themes at several places:

* Layer resource files
* Theme resource files
* Service metadata files

The service metadata approach is the most flexible and extensible (see #395 and [1]). As suggested by #395, putting metadata in layer and theme files should be deprecated.

Before this can actually be enforced, there are two shortcoming that need to be taken care of. In the service metadata file, a unique name is needed to identify the dataset (layer/theme/feature type/...) to attach the metadata to:

```xml
  <DatasetMetadata>
    <Dataset>
      <Name>layer1</Name>
      <Title>Layer 1 Title (from metadata config)</Title>
      <Abstract>Layer 1 Abstract (from metadata config)</Abstract>
      ...
    </Dataset>
  </DatasetMetadata>
```
The Name element refers to the name/identifier of a layer, theme or feature type. There are two problems with this:

* A layer does not need to have an identifier. This is a mechanism used by the WMS capabilities, it implies that this (group) layer can not be requested.
* Identifiers of layers and themes may clash in the WMTS (and probably in WMS 2.0 which is supposed to export both themes and layers in the capabilities as well).

WMTS capabilities snippet:

```xml
...
   <Layer>
      <ows:Title>Luchtfoto 2013 (Winter)</ows:Title>
      <ows:Identifier>actueel_winter</ows:Identifier>
      ...
    </Layer>
    ...
    <Theme>
      <ows:Title>Luchtfoto 2013 (Winter)</ows:Title>
      <ows:Identifier>actueel_winter</ows:Identifier>
      <LayerRef>actueel_winter</LayerRef>
    </Theme>
   ...
```

In order to solve the first issue, I suggest to add the boolean attribute "requestable" to the ows:Identifier element in the Theme config:

```xml
...
<Theme>
  <Identifier requestable="false">grouplayer</Identifier>
  <Theme>
    <Identifier>layer1</Identifier>
    <Layer>layer1</Layer>
  </Theme>
  <Theme>
    <Identifier>layer2</Identifier>
    <Layer>layer2</Layer>
  </Theme>
</Theme>
...
```

The default value for the requestable attribute would be "true", which allows for backward compatibility.

In order to solve the second issue, I suggest to make use of the fact that the Name element in the metadata config already is a QName (used for identifying feature types). In order to distinguish between metadata datasets for layers and themes, they should be treated as qualified names:

```xml
  <DatasetMetadata>
    <Dataset>
      <Name xmlns:layer="http://www.deegree.org/layer">layer:actueel_winter</Name>
      <Title>Layer 1 Title</Title>
      <Abstract>Layer 1 Abstract</Abstract>
      ...
    </Dataset>
    <Dataset>
      <Name xmlns:theme="http://www.deegree.org/theme">theme:actueel_winter</Name>
      <Title>Theme 1 Title</Title>
      <Abstract>Theme 1 Abstract</Abstract>
      ...
    </Dataset>
  </DatasetMetadata>
```
For ease-of-use (and backward compatibility), the lookup of layer/theme metadata should be done in two phases. First, we should try a qualified lookup. If this does not succeed, a lookup based on the local name should be tried.

[1] http://download.deegree.org/documentation/3.3.12/html/webservices.html#metadata

**Comment by tfr42** [comment]
Closed. Fixed by PR #450 for 3.4 line.
