### ISSUE TITLE
Fix release note links on the deegree Download page

### ISSUE THREAD

**Issue by MrSnyder** [deegree/deegree3#451]
http://www.deegree.org/Download

They are broken since we closed the Trac issue tracker. Also I am unsure which link to use for pointing to the GitHub-based changelog.

@tfr42: Can you take the lead here, please?

**Comment by lgoltz** [comment]
Link is still broken: https://www.deegree.org/github.com/deegree/deegree3/pulls?q=is:pr+is:closed+milestone:3.3.20

**Comment by tfr42** [comment]
Change log for 3.3.x and newer now taken from GitHub.
