### ISSUE TITLE
Feature type without geometry will result all data in WFS

### ISSUE THREAD

**Issue by paul999** [deegree/deegree3#479]
Hi,

When you have a feature type with all geometry, but provide a bounding box in WFS, all data will be returned. 
Instead of returning all data (Limited to max features) when requesting with a bounding box, we think a error would be more in place.

**Comment by tfr42** [comment]
Hi, 
do I get you right that a feature type *without* a geometry shall not be returned within the response for a GetFeature request providing a BBOX? Did you check the OGC specs for WFS 1.1.0 or 2.0?

**Comment by tfr42** [comment]
Without further information it is not possible to get this inquire resolved. If you can provide more information like a complete WFS GetFeature request/response example and a workspace with an example feature store this would be very helpful. In this case please re-open the issue.
