### ISSUE TITLE
handbook: publish on github.io/deegree3

### ISSUE THREAD

**Issue by mmacata** [deegree/deegree3#482]
The future url would be: http://deegree.github.io/deegree3

I started working on it on branches gh-pages and feature/fossgis-hacking-handbook in the forked https://github.com/FOSSGIS-Hacking-Event/deegree3 repository. The branch gh-pages is needed by github convention to publish a website for the project. The feature/fossgis-hacking-handbook-branch includes a makefile in the handbook directory which is able to publish the handbook in gh-pages when running maven under a profile called 'gh-pages'.

With these changes the handbook can only be build 'the old way' by running maven with the profile 'build'.

Is it sufficient to build the handbook only when using profiles? Or even to only use the github version? Any comments/ideas?

**Comment by tfr42** [comment]
An example how the documentation would be published under github.io is already available for the fork fossgis-hacking-event:
http://fossgis-hacking-event.github.io/deegree3/deegree-services/deegree-webservices-handbook/index.html

Before merging the gh-pages branch into the deegree master project the make file needs to be adjusted:
https://github.com/FOSSGIS-Hacking-Event/deegree3/blob/feature/fossgis-hacking-handbook/deegree-services/deegree-webservices-handbook/Makefile

**Comment by tfr42** [comment]
Things we need to check before
 * versioning of the handbook
 * apply properties

**Comment by copierrj** [comment]
The TMC decided that migrating the handbook is not a priority for now.
