### ISSUE TITLE
Migration of demo.deegree.org to plaza

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#488]
All services hosted on demo.deegree.org shall move to plaza.deegree.org
This will require some changes of the setup for the integration tests.

**Comment by tfr42** [comment]
download.deegree.org and schema.deegree.org are already on plaza

**Comment by wanhoff** [comment]
Documentation for deegree 3.3 demo services can be found in the handbook:
http://download.deegree.org/documentation/3.3.13/html/lightly.html

**Comment by wanhoff** [comment]
I guess, it is a good idea to set up all demo services for the recent stable version. So we shoud skip the migration and just install services for all demo workspaces.
Ideally we should create jenkins jobs to do a one-click-deployment for the demo services. So we could keep the demos up-to-date easily. Adjustment should be minimal (just the version), so the additional effort after a release should be only a few minutes.

**Comment by wanhoff** [comment]
Migration should be complete.
 * Setup of demo tomcat and database as described in documentation.
 * Nameserver entry of demo.deegree.org points to plaza.deegree.org, now.
 * Redirect to www.deegree.org/demo works, too. Copied the index.html from old demo.deegree.org to ROOT-webapp in demo tomcat

**Comment by wanhoff** [comment]
http://www.deegree.org/Demo needs to be updated.

**Comment by NielsWalen** [comment]
For me the demo.deegree.org runs on plaza without any problems after testing. The four demos are installed and can be reached by the URL:
http://demo.deegree.org/$XX-workspace/
for examle:
http://demo.deegree.org/csw-workspace/
Now, there aren't any reason not to update http://www.deegree.org/Demo.

**Comment by tfr42** [comment]
Updates to links applied to http://www.deegree.org/Demo. 
@wanhoff @NielsWalen Thanks for your support!
