### ISSUE TITLE
Go-live of dev.deegree.org

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#489]
Publish http://dev.deegree.org under www.deegree.org and let the drupal site retire.

**Comment by tfr42** [comment]
OK. but wiki is down.

**Comment by tfr42** [comment]
We need access and editor rights

**Comment by tfr42** [comment]
add grit to the list of companies

**Comment by wanhoff** [comment]
Admin credentials have been provided to Torsten and Arie. So you should be able to grant the requested rights.

**Comment by wanhoff** [comment]
wiki.deegree.org has not been migrated to plaza.deegree.org.

**Comment by kraaka** [comment]
I've added grit to the list of companies

**Comment by tfr42** [comment]
Closed. [Wiki] (http://wiki.deegree.org/deegreeWiki/) is back online and the old trac based [issue tracker] (http://tracker.deegree.org/deegree-services/)  just for documentation purposes only too
