### ISSUE TITLE
Prepare release 3.4

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#490]
We need funding for fixing the open bugs reported against 3.4 pre release.

**Comment by copierrj** [comment]
Any update on this?

**Comment by tfr42** [comment]
Can the PSC members help out here?

**Comment by tfr42** [comment]
Or shall we start a crowd-funding campaign to raise some money?

**Comment by HermanAssink** [comment]
Is there an estimate of the required effort?

**Comment by tfr42** [comment]
Not in counted hours or person days yet. But can everyone please post his estimate in days to fix all open issues wrt the deegree admin console - see the list of [open issue target milestone 3.4] (https://github.com/deegree/deegree3/issues?page=1&q=is%3Aissue+is%3Aopen+milestone%3A3.4).

**Comment by tfr42** [comment]
My estimate is 5 person days
@copierrj @MrSnyder @stephanr Can you please post your estimates?

**Comment by MrSnyder** [comment]
I agree. My estimate would be 5 PD as well.

**Comment by tfr42** [comment]
Furthermore we need some more days for testing all merged PR.

**Comment by tfr42** [comment]
Release 3.4.0 is GA and comes without the feature store wizard. As a workaround the CLI https://github.com/deegree/deegree3/tree/master/deegree-tools/deegree-tools-config is available.
