### ISSUE TITLE
FOSS4G Europe Workshop submission 2015

### ISSUE THREAD

**Issue by MrSnyder** [deegree/deegree3#491]

**Comment by MrSnyder** [comment]
In the latest  [TMC meeting] (wiki/tmc-meeting-minutes-20150206) this has been discussed. TMC is totally in favor of a deegree workshop at FOSS4G Europe. The actual submission and presenters still need to be decided but there's at least one definitive option: lat/lon and wetransform.to are willing to do a joint presentation.

**Comment by segoerke** [comment]
As a workshop abstract was submitted, I think this can be closed

**Comment by tfr42** [comment]
The workshop committee of the FOSS4G Europe 2015 conference rejected our submission.
