### ISSUE TITLE
Replace default Joomla-Style Favorite Icon

### ISSUE THREAD

**Issue by stephanr** [deegree/deegree3#492]
The Site uses currently the default Joomla Favicon. 
I would like to propose to use the from the previous site as Favicon instead of the default Joomla one.

I prepared a ![Favicon](http://wega.grit.de/dl/reichhelm/deegree_favicon.ico) Icon (.ico) [1] created from the previously used one [2].

[1] http://wega.grit.de/dl/reichhelm/deegree_favicon.ico
[2] https://web.archive.org/web/20140208034907im_/http://www.deegree.org/sites/default/files/deegree_logo_d.png

**Comment by kraaka** [comment]
Excellent.

**Comment by kraaka** [comment]
Done by Jeronimo, thanks.

**Comment by stephanr** [comment]
Great, thanks
