### ISSUE TITLE
Preffered Link for github Logo on the Website

### ISSUE THREAD

**Issue by stephanr** [deegree/deegree3#493]
The "Fork me on github" Link on the Website tragets to the deegree3 repository, but the "github" Icon on the Bottom/Footer target to "https://github.com/deegree/deegree.github.io".

I would prefer to link to the Organization page on "https://github.com/deegree" instead of the currentyl empty deegree.github.io repository.

**Comment by tfr42** [comment]
We do have a PR for the new start page. See https://github.com/deegree/deegree.github.io/pull/1
Which looks good in my opinion. Ca we merge that?

**Comment by stephanr** [comment]
This issue is no longer relevant / up-to-date see https://github.com/deegree/deegree3/issues/967
