### ISSUE TITLE
Put characteristics of each deegree service on about page

### ISSUE THREAD

**Issue by MrSnyder** [deegree/deegree3#499]
I like that the new deegree website lists the different service types on the about page [1].

Thanks for doing this, Arie. I would suggest to go even one step further: Why not provide the linked introduction (from the handbook) directly on the "About deegree" page? I believe that people who are looking at the deegree website are always somehow technically inclined. And IMHO, the answer to "What is deegree?" should not only include information on it's organization and history, but first and foremost hard facts on the features implemented in deegree. After all, the question on a visitors mind will rather be "What can deegree do for me?" than "What is the story behind deegree?".
 
Therefore, I suggest to use the text from the introduction chapter of the handbook [1] on the about page as well. As the first paragraphs. Slight adaptations are required (I can help here). Plus, it may be nice to add the respective OGC compliance logos for each service individually (or the full certification panel on the right).

[1] http://deegree.org/index.php/about-deegree
[2] http://download.deegree.org/documentation/3.3.13/html/intro.html

**Comment by kraaka** [comment]
Thanks for your suggestion. I agree. I have put the introduction on the website (please check). I put the full certification panel into the article, but still looking for a better position of this (rigid sized) badge.

**Comment by MrSnyder** [comment]
Great, thanks. Would it be possible to put it below the "deegree services" box on the right?

**Comment by MrSnyder** [comment]
I believe, this (certification panel on the right) could also be a good option for the start page.

**Comment by kraaka** [comment]
Yes, I will try that. I just found that I can add a size property to the 
url, otherwise it would be too big for the right sidebar (or the sidebar 
too small for the badge).

Kind regards,

Arie Kraak

IDgis <http://www.idgis.nl>
Tel +31 (0)548 367 280

Volg IDgis op LinkedIn! <http://www.linkedin.com/company/idgis>
Markus Schneider schreef op 11-2-2015 om 16:19:

**Comment by MrSnyder** [comment]
Nice progress, Arie.
