### ISSUE TITLE
Link to download shall remain http://deegree.org/Download

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#500]
The new joomla website introduces a new URL to the download page
<http://deegree.org/index.php/download>

But it should remain <http://deegree.org/Download>.
Same with <http://www.deegree.org/Documentation> which shall remain too.

**Comment by copierrj** [comment]
This can be done by configuring Apache (e.g. with mod_rewrite) to map /* to /index.php/*

**Comment by stephanr** [comment]
On Jommla this redirection is named SEF URLs see #502

**Comment by stephanr** [comment]
I had enabled the server setting for the SEF so the URLs are working now, only the Joomla setting has to be done.

So this issue can be closed after #502 is ready.

**Comment by stephanr** [comment]
As #502 is fixed, this also can be closed
