### ISSUE TITLE
use of different expression

### ISSUE THREAD

**Issue by mmacata** [deegree/deegree3#505]
The sentence "some of the internationally operating companies which are happy to play a role in your project - against reasonable costs - are:" on page "Support" needs rewording.

Any suggestions/ideas?

**Comment by kraaka** [comment]
Could you be more specific: is it the content of the message, the phrasing, the grammar?

**Comment by tfr42** [comment]
Page support has been removed. See www.deegree-enterprise.com for professional services around the deegree OSS stack.
