### ISSUE TITLE
navigation for 'deegree in practice'

### ISSUE THREAD

**Issue by mmacata** [deegree/deegree3#506]
When I click on "deegree in practice" on the main page, the instructions tell me to "click on the menu item  "Create Article" on the right" - but there is no such link.

When I have a look at either deegree in action or WMS and WFS, I don't know where I am in the navigation or how I reached this sub-page.

**Comment by kraaka** [comment]
Thanks for notifying!. I've added the create article menu item (only visible after login)  and added a breadcrumb module.
