### ISSUE TITLE
Issue in GML served by WFS for SRS with northing/easting as mandated axis order.

### ISSUE THREAD

**Issue by phasenohr** [deegree/deegree3#509]
Hello,

It seems that the coordinates contained in the GML file (<gml:posList> element) returned by a WFS2/GML3.2 service provided by Deegree 3.3.13 are not always ordered according to the axis order specified in the EPSG database for the corresponding SRS.

My source dataset is in urn:ogc:def:crs:EPSG::4258 and I made several GetFeature requests to the WFS service with the different srsName parameters listed in the table below:

srsName | coordinate order in `<gml:posList>` | Is matching epsg db?
------------------------------------ | -------------------------------------------- | --------------------------
urn:ogc:def:crs:EPSG::4326 | latitude longitude | OK
urn:ogc:def:crs:EPSG::4258 | latitude longitude | OK
urn:ogc:def:crs:EPSG::3857 | easting northing | OK
urn:ogc:def:crs:EPSG::3035 | easting northing | NO (northing easting required)
urn:ogc:def:crs:EPSG::3043 | easting northing | NO (northing easting required)

In the case of ETRS89-LAEA (EPSG:3035), the coordinates are ordered differently from what is specified in the EPSG database. As a consequence, QGIS is not able to display correctly the dataset reprojected by deegree (and retrieved using the WFS2 plugin for QGIS).
The GML3.2 files produced by HALE and FME for epsg:3035, epsg:3857 and epsg:3043 have by default the coordinates ordered according to the axis order specified by EPSG: easting/northing for epsg:3857 and northing/easting for epsg:3035 and epsg:3043.

Could you please let me know if I am doing anything wrong?

Best regards,
Paul Hasenohr
European Environment Agency

**Comment by segoerke** [comment]
Hi Paul, what you are describing is a known issue for deegree versions below 3.4. Please see: https://github.com/deegree/deegree3/wiki/Axis-order-handling for more information.

Hopefully this will help you.

**Comment by phasenohr** [comment]
Hi Sebastian,

Thank you for your quick answer. I just downloaded the CRS database currently in trunk and put it in my workspace. It is working as expected now :)

Best regards,
Paul
