### ISSUE TITLE
WFS-T update problem when using 3D-coordinates

### ISSUE THREAD

**Issue by larseggan** [deegree/deegree3#511]
I have set up a WFS-Transaction server with deegree 3.3.8 (SQL Feature store)
I want  to use 3D-coordinates:
wfs:Insert is OK with xyz, but wfs:Update failes.
The error message from wfs:Update:
<?xml version='1.0' encoding='UTF-8'?>
<ows:ExceptionReport 
    xmlns:ows="http://www.opengis.net/ows/1.1" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="2.0.0">
    <ows:Exception exceptionCode="NoApplicableCode">
        ows:ExceptionTextGeometry is invalid. Dimensionality of coordinates (=3) does not match dimensionality of CRS 'urn:ogc:def:crs:EPSG::25832' (=2)./ows:ExceptionText
    /ows:Exception
/ows:ExceptionReport

I have used EPSG:25832 (ETRS89 / UTM zone 32N), but the correct EPSG code is a compound crs EPSG:6172 (ETRS89 / UTM zone 32 + NN54 height) or EPSG:5972 (ETRS89 / UTM zone 32 + NN2000 height).
Is there any way of getting these crs into deegree?
Regards,
Lars

**Comment by tfr42** [comment]
Unfortunately the handbook is missing this information. But please have a look on the pull requests #174 and #238 as an example. There are 3 configuration files you might have to touch: ``crs-definitions.xml``, ``datum-definitions.xml``, and  ``projection-definitions.xml``.

**Comment by larseggan** [comment]
I followed the following description: http://wiki.deegree.org/deegreeWiki/deegree3/WorkspaceConfiguration/CRSConfiguration
And then added a new crs to crs\deegree\d3\config\crs-definitions.xml:
<crs:CompoundCRS>
                <crs:Id>epsg:6172</crs:Id>        
                <crs:Id>urn:ogc:def:crs:epsg::6172</crs:Id>
                <crs:Name>ETRS89 / UTM zone 32N +NN54 height</crs:Name>
                <crs:Version>2015-03-11</crs:Version>
                <crs:Description>Inserted by hand.</crs:Description>
               <crs:AreaOfUse>6.0,57.93,12.0,65.76</crs:AreaOfUse>
                <crs:AreaOfUse>Norway - onshore between 6°E and 12°E.</crs:AreaOfUse>
                <crs:UsedCRS>epsg:25832</crs:UsedCRS>
                <crs:HeightAxis>
                        <crs:Name>height</crs:Name>
                        <crs:Units>metre</crs:Units>
                        <crs:AxisOrientation>up</crs:AxisOrientation>
                </crs:HeightAxis>
                <crs:DefaultHeight>0.0</crs:DefaultHeight>
</crs:CompoundCRS>

I have also added EPSG:6172 to PostGIS.

wfs:GetFeature works OK.
wfs:Insert does not work, error:
<ows:ExceptionReport 
    xmlns:ows="http://www.opengis.net/ows/1.1" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="2.0.0">
    <ows:Exception exceptionCode="InvalidParameterValue">
        <ows:ExceptionText>Cannot perform insert operation: Error inserting feature: ERROR: Column has Z dimension but geometry does not</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
Thanks,
Lars

**Comment by segoerke** [comment]
Can you Provide an example feature which you want to insert? Seems your geometries do not have a Z dimension..

**Comment by larseggan** [comment]
I struggle both with wfs:Insert and wfs:Update after I added the new crs.
wfs:insert sample:
<?xml version="1.0" encoding="utf-8"?>
<wfs:Transaction version="2.0.0" service="WFS" xmlns:wfs="http://www.opengis.net/wfs/2.0"
  xsi:schemaLocation="http://skjema.geonorge.no/standard/geosynkronisering/1.0/endringslogg http://geosynkronisering.no/files/skjema/1.0/changelogfile.xsd http://kart4.nois.no/skjema/va http://kart4.nois.no/skjema/va/va.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:va="http://kart4.nois.no/skjema/va"
  xmlns:gml="http://www.opengis.net/gml/3.2">
  <wfs:Insert handle="100">
    <va:NyGNIS_Knutepunkt xmlns:va="http://kart4.nois.no/skjema/va" gml:id="vanygnis_knutepunkt.1">
      <va:id>99999</va:id>
      <va:navn>Kum nr.1092</va:navn>
      <va:beskrivelse>Lars</va:beskrivelse>
      <va:vaType>KUM</va:vaType>
      <va:punkt>
        <gml:Point gml:id="GEOMETRY_01aa6580-38bc-4ef5-9e1a-fbe55ddd5bd3" srsName="urn:ogc:def:crs:EPSG::6172" srsDimension="3">
           <gml:pos>503031.890 6766718.730 372.300</gml:pos>
        </gml:Point>
      </va:punkt>
    </va:NyGNIS_Knutepunkt>
  </wfs:Insert>
</wfs:Transaction>

In PostGIS the geometry column is defined as: geometry(PointZ,6172).

I added the two crs to PostGIS:
EPSG:5776 (NN54):
INSERT into spatial_ref_sys (srid, auth_name, auth_srid, proj4text, srtext) values ( 5776, 'EPSG', 5776, '', 'VERT_CS["NN54 height",VERT_DATUM["Norway Normal Nul 1954",2005,AUTHORITY["EPSG","5174"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Up",UP],AUTHORITY["EPSG","5776"]]');
Compound crs 6172 ETRS89 / UTM zone 32 + NN54 height EPSG:
INSERT into spatial_ref_sys (srid, auth_name, auth_srid, proj4text, srtext) values ( 6172, 'EPSG', 6172, '+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +vunits=m +no_defs ', 'COMPOUNDCRS["ETRS89 / UTM zone 32 + NN54 height",PROJCRS["ETRS89 / UTM zone 32N",BASEGEODCRS["ETRS89",DATUM["European Terrestrial Reference System 1989",ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["metre",1.0]]]],CONVERSION["UTM zone 32N",METHOD["Transverse Mercator",ID["EPSG",9807]],PARAMETER["Latitude of natural origin",0,ANGLEUNIT["degree",0.01745329252]],PARAMETER["Longitude of natural origin",9,ANGLEUNIT["degree",0.01745329252]],PARAMETER["Scale factor at natural origin",0.9996,SCALEUNIT["unity",1.0]],PARAMETER["False easting",500000,LENGTHUNIT["metre",1.0]],PARAMETER["False northing",0,LENGTHUNIT["metre",1.0]]],CS[cartesian,2],AXIS["easting (E)",east,ORDER[1]],AXIS["northing (N)",north,ORDER[2]],LENGTHUNIT["metre",1.0],ID["EPSG",25832]],VERTCRS["NN54 height",VDATUM["Norway Normal Null 1954"],CS[vertical,1],AXIS["gravity-related height (H)",up],LENGTHUNIT["metre",1.0],ID["EPSG",5776]],ID["EPSG",6172]]');

Thanks,
Lars

**Comment by larseggan** [comment]
I still struggle with deegree (now on version 3.3.16) regarding x,y,Z coordinates.
<ows:ExceptionText>Cannot perform insert operation: Error inserting feature: ERROR: Column has Z dimension but geometry does not</ows:ExceptionText>
Any hope for a fix / solution?
Thanks,
Lars

**Comment by larseggan** [comment]
Fixed by #693 and #694
