### ISSUE TITLE
Poor Blogging module on deegree website

### ISSUE THREAD

**Issue by segoerke** [deegree/deegree3#515]
The actual bloggin module used on the deegree website is poor in functionality and look-and-feel.
Something like K2 should be evaluated: http://extensions.joomla.org/extension/k2

**Comment by kraaka** [comment]
I agree, (for instance: http://savvypanda.com/blog/why-i-think-k2-is-the-best-joomla-blogging-component.html)
 
k2 is free and offers many more extensions. It is also convenient as component at back-end.

**Comment by tfr42** [comment]
Website moved to GitHub pages, see #967.
