### ISSUE TITLE
CSW: Support for JSON unclear in documentation

### ISSUE THREAD

**Issue by MrSnyder** [deegree/deegree3#530]
The deegree handbook for 3.3.14 [1] states: "deegree3 CSW (up to 3.2-pre11) supports JSON as additional output format. "

This confuses me:

* Do versions after 3.2-pre11 support JSON as well?
* If not, why is this stated in the documentation at all?

IMHO, the deegree handbook does not need to (and shouldn't) refer to certain versions. It is versioned and should always refer to the corresponding deegree version.

[1] http://download.deegree.org/documentation/3.3.14/html/webservices.html#extended-functionality

**Comment by lgoltz** [comment]
GetRecords Request with outputFormat="application/json"  is still working with the deegee demo workspace  http://demo.deegree.org:80/csw-workspace/services/ 
```
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" service="CSW" version="2.0.2" maxRecords="15" startPosition="1" resultType="results" outputFormat="application/json" outputSchema="http://www.isotc211.org/2005/gmd" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2                        http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd">
  <csw:Query typeNames="gmd:MD_Metadata">
    <csw:ElementSetName typeNames="gmd:MD_Metadata">full</csw:ElementSetName>
  </csw:Query>
</csw:GetRecords>
```

I will remove the version from the handbook.
