### ISSUE TITLE
ISOMetadataStore (SQL): Setup tables script fails on PostgreSQL 9.3/PostGIS 2.1

### ISSUE THREAD

**Issue by MrSnyder** [deegree/deegree3#531]
I am setting up an ISOMetadataStore (SQL) using deegree 3.4-pre17 on Ubuntu 14.04 LTS (packaged PostgreSQL/PostGIS version). I run into the following issue when creating the database tables using "Setup tables":

"Error: ERROR: function addgeometrycolumn(unknown, unknown, unknown, unknown, unknown, unknown) is not unique Hint: Could not choose a best candidate function. You might need to add explicit type casts. Position: 8"

I analyzed the SQL script and found the problem in line 75:

"SELECT AddGeometryColumn('public','idxtb_main','bbox','-1','GEOMETRY','2');"

Here's what works for me:

"SELECT AddGeometryColumn('public','idxtb_main','bbox',0,'GEOMETRY',2);"

I think there are two problems:
* SRID and dimension should be given as numbers, not strings
* Since some time, the official "undefined" SRID is 0, not -1

**Comment by segoerke** [comment]
> Since some time, the official "undefined" SRID is 0, not -1
That's the case since PostGIS 2.0
