### ISSUE TITLE
Upgrade Nexus repository manager on repo.deegree.org

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#554]
Nexus on repo.deegree.org needs an update.
Requires:
 - [x] backup of Nexus config
 - [x] install using bundle
 - [x] create systemd service
 - [x] remove obsolete tomcat instance

Current configuration is in `/usr/local/tomcat/nexus/webapps/ROOT/WEB-INF/plexus.properties`
New configuration: `${install_dir}/conf/nexus.properties`

Download older versions from
- https://help.sonatype.com/repomanager2/download/download-archives---repository-manager-oss

Post-Installation steps
- [x] #660 Remove unused SNAPSHOTS
- [x] optimize Nexus disk space usage
- [x] limit content of repo to deegree RELEASES and SNAPSHOTS (public) and Third party libs required to build deegree (protected repository)

References:
- https://support.sonatype.com/hc/en-us/articles/213464138-How-do-I-upgrade-Nexus-Repository-Manager-2-x-to-2-y
- https://help.sonatype.com/repomanager3/upgrading#Upgrading-Upgradingfrom2.xto2.y
- https://support.sonatype.com/hc/en-us/articles/213464338-Nexus-Repository-Manager-Upgrade-and-Compatibility-Notes
- https://help.sonatype.com/repomanager3/installation/run-as-a-service
- https://help.sonatype.com/repomanager3/installation/run-behind-a-reverse-proxy
- https://support.sonatype.com/hc/en-us/articles/213464278-How-to-Reset-Nexus-Logging-Configuration
- https://support.sonatype.com/hc/en-us/articles/213465138-How-can-I-optimize-Nexus-2-to-minimize-disk-space-used-

**Comment by stephanr** [comment]
In order to inform our users, we should also announce the maintenance on our website.
This could also be possible done through a tweet.

**Comment by tfr42** [comment]
During downtime the latest release versions can be downloaded via the Github site. 

Manually uploaded the release WAR/ZIP files for 3.4.8 and 3.3.21 to
https://github.com/deegree/deegree3/releases

**Comment by tfr42** [comment]
Moving to OSGeo repo is may be an alternative, see #1075

**Comment by tfr42** [comment]
Nexus has been updated to v3.0 and is available at http://nexus3.deegree.org or it's alias https://repo.deegree.org.
