### ISSUE TITLE
Add spam blocker to blog module

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#559]
Recently more and more spam comments are added to our [blog](http://www.deegree.org/posts/). We need a spam blocker.

**Comment by stephanr** [comment]
A common way to block bots from adding spam comments is to use a captcha plugin/service.
If the installed Joomla version is capable, i would suggest to use googles recaptcha [1] to block bots.

[1] https://www.google.com/recaptcha

**Comment by tfr42** [comment]
Website moved to GitHub pages, #967.
