### ISSUE TITLE
How to use filter encoding on WFS, with complex features, in KVP/GET.

### ISSUE THREAD

**Issue by atellezarenas** [deegree/deegree3#560]
Hi,

I have seen the answer (examples of working urls with filter, bbox and PropertyIsEqualTo), for WFS delivering simple GML;

But when the WFS implements a complexe schema (INSPIRE schema, in our case EarthResourceML):
http://minerals4eu.brgm-rec.fr/deegree/services?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAMES=ge:MappedFeature&OUTPUTFORMAT=text/xml; subtype=gml/3.2.1&count=1&resolveDepth=*

How to build a working filter? I need to filter on
- bbox
- and attributes using PropertyIsLike or PropertyIsEqualTo

For instance:
`<Filter xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0" xmlns:mr-core="http://inspire.ec.europa.eu/schemas/mr-core/3.0" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:mr-m4eu="http://inspire.ec.europa.eu/schemas/mr-m4eu/1.0"><PropertyIsEqualTo><ValueReference>ge:MappedFeature/ge:specification/mr-m4eu:MineralOccurrence_Extension/ge:name</ValueReference><Literal>FRA-00743</Literal></PropertyIsEqualTo></Filter>`

`<Filter xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0" xmlns:mr-core="http://inspire.ec.europa.eu/schemas/mr-core/3.0" xmlns:mr-m4eu="http://inspire.ec.europa.eu/schemas/mr-m4eu/1.0"><PropertyIsLike wildCard="*" singleChar="." escapeChar="!"><ValueReference>ge:MappedFeature/ge:specification/mr-m4eu:MineralOccurrence_Extension/ge:name</ValueReference><Literal>FRA-007*</Literal></PropertyIsLike></Filter>`

`<Filter xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0" xmlns:mr-core="http://inspire.ec.europa.eu/schemas/mr-core/3.0"><PropertyIsEqualTo><ValueReference>ge:MappedFeature//mr-core:commodity@xlink:href</ValueReference><Literal>http://inspire.ec.europa.eu/codelist/CommodityCodeValue/iron</Literal></PropertyIsEqualTo></Filter>`

But it's not working (no result, but I know there are, and no error in the log file). Or, impossible to use '@' in the XPATH. But in that case, How can I filter on the value of an attribute?

Do you have examples of working FILTERs (urls) on WFS delivering complex features?

Thanks,

Agnès / BRGM.

**Comment by MrSnyder** [comment]
Here's a collection of WFS requests and filtering on complex features:

http://demo.deegree.org/inspire-workspace/console/client/client.xhtml

**Comment by MrSnyder** [comment]
If you want to perform a complex request using KVP, I would suggest to first create a working XML request. This is much more readable. Afterwards, use the filter in the KVP request. Make sure that all namespaces are bound in the XML. Perform URL encoding of the XML.

Example (XML):

```
<GetFeature version="2.0.0" service="WFS" xmlns="http://www.opengis.net/wfs/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
  <Query typeNames="ge:MappedFeature">
    <Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
      <BBOX>
        <ValueReference>ge:shape</ValueReference>
        <Envelope srsName="EPSG:4258" xmlns="http://www.opengis.net/gml/3.2">
          <lowerCorner>4.220000 45.956500</lowerCorner>
          <upperCorner>4.220001 45.956501</upperCorner>
        </Envelope>
      </BBOX>
    </Filter>
  </Query>
</GetFeature>
```

You can easily send an XML request via curl:

```
curl -H Content-Type:application/xml -d @/tmp/request.xml http://minerals4eu.brgm-rec.fr/deegree/services
```

After the request works, extract the filter. Remove whitespaces:

```
<Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0"><BBOX><ValueReference>ge:shape</ValueReference><Envelope srsName="EPSG:4258" xmlns="http://www.opengis.net/gml/3.2"><lowerCorner>4.220000 45.956500</lowerCorner><upperCorner>4.220001 45.956501</upperCorner></Envelope></BBOX></Filter>
```

Perform URL encoding:

```
%3CFilter%20xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%20xmlns%3Age%3D%22http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fge-core%2F3.0%22%3E%3CBBOX%3E%3CValueReference%3Ege%3Ashape%3C%2FValueReference%3E%3CEnvelope%20srsName%3D%22EPSG%3A4258%22%20xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%3E%3ClowerCorner%3E4.220000%2045.956500%3C%2FlowerCorner%3E%3CupperCorner%3E4.220001%2045.956501%3C%2FupperCorner%3E%3C%2FEnvelope%3E%3C%2FBBOX%3E%3C%2FFilter%3E

Example (KVP):

http://minerals4eu.brgm-rec.fr/deegree/services?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&NAMESPACES=xmlns(ge,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fge-core%2F3.0)&TYPENAMES=ge%3AMappedFeature&FILTER=%3CFilter%20xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%20xmlns%3Age%3D%22http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fge-core%2F3.0%22%3E%3CBBOX%3E%3CValueReference%3Ege%3Ashape%3C%2FValueReference%3E%3CEnvelope%20srsName%3D%22EPSG%3A4258%22%20xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%3E%3ClowerCorner%3E4.220000%2045.956500%3C%2FlowerCorner%3E%3CupperCorner%3E4.220001%2045.956501%3C%2FupperCorner%3E%3C%2FEnvelope%3E%3C%2FBBOX%3E%3C%2FFilter%3E

NOTE: The NAMESPACES parameter is required for the ge-prefix in the feature type name, not for the filter.

**Comment by atellezarenas** [comment]
Thanks a lot.

I had a small mistake in my filter, now with the examples I was able to fix it. Now, is it possible to use XPATH on attribute? (I mean ...@xlink:yref), for instance.

**Comment by MrSnyder** [comment]
Generally, filtering on attributes is supported, although it has some pitfalls. For example, filtering on "virtual" attributes like srsName or xmlns will not work.

Filtering on xlink:href should work for your case. Here's how such a request would look like:

```
<GetFeature version="2.0.0" service="WFS" xmlns="http://www.opengis.net/wfs/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
  <Query typeNames="ge:MappedFeature">
    <Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
      <PropertyIsEqualTo>
        <ValueReference>ge:mappingFrame/@xlink:href</ValueReference>
        <Literal>http://inspire.ec.europa.eu/codeList/MappingFrameTerm/topographicSurface</Literal>
      </PropertyIsEqualTo>
    </Filter>
  </Query>
</GetFeature>
```

Unfortunately, I do not get the expected result from your server. Could you please:

* Check if you're running the latest 3.3 version (3.3.14)
* If this doesn't help, please try with a 3.4-pre version [1]. The UI is currently broken in this series, but the WFS should work fine (and has some improvements over 3.3).

[1] http://deegree.org/download

**Comment by atellezarenas** [comment]
Thanks for your help!

I have tried both, it's not working. The current version is 3.4-pre, and I'm trying the following request (POST, using https://www.hurl.it/)

There's nothing in my tomcat log file. And I can not see the SQL requests (I don't have the access). 

I hope it will work, I'd like to report that we can use Deegree for our INSPIRE WFSs!

`
<GetFeature xmlns="http://www.opengis.net/wfs/2.0" xmlns:base="http://inspire.ec.europa.eu/schemas/base/3.3" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0" xmlns:mr-core="http://inspire.ec.europa.eu/schemas/mr-core/3.0" xmlns:mr-m4eu="http://inspire.ec.europa.eu/schemas/mr-m4eu/1.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" service="WFS" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/fes/2.0 http://schemas.opengis.net/filter/2.0/filter.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd"
count="2" resolveDepth="*">
  <Query typeNames="ge:MappedFeature">
    <fes:Filter>
      <fes:And>
      <fes:BBOX>
        <fes:ValueReference>ge:shape</fes:ValueReference>
        <gml:Envelope srsName="EPSG:4258">
          <gml:lowerCorner>4.7 49.8</gml:lowerCorner>
          <gml:upperCorner>4.8 49.85</gml:upperCorner>
        </gml:Envelope>
      </fes:BBOX>
       <fes:PropertyIsEqualTo>
        <fes:ValueReference>ge:mappingFrame/@xlink:href</fes:ValueReference>
        <fes:Literal>http://inspire.ec.europa.eu/codeList/MappingFrameTerm/topographicSurface</fes:Literal>
      </fes:PropertyIsEqualTo>
      </fes:And>
    </fes:Filter>
  </Query>
</GetFeature>
`

**Comment by nmtoken** [comment]
I tried the same request using [hurl it](https://www.hurl.it/) against my service (endpoint http://194.66.252.155/m4eu/services?) .  The service is using deegree version 3.3.13.

E.g.

```
<GetFeature version="2.0.0" service="WFS" xmlns="http://www.opengis.net/wfs/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
  <Query typeNames="ge:MappedFeature">
    <Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
      <PropertyIsEqualTo>
        <ValueReference>ge:mappingFrame/@xlink:href</ValueReference>
        <Literal>http://inspire.ec.europa.eu/codeList/MappingFrameTerm/topographicSurface</Literal>
      </PropertyIsEqualTo>
    </Filter>
  </Query>
</GetFeature>
```

Gives this response:

```
<?xml version='1.0' encoding='UTF-8'?>
<wfs:FeatureCollection
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd http://inspire.ec.europa.eu/schemas/ge-core/3.0 http://194.66.252.155/m4eu/services?SERVICE=WFS&amp;VERSION=2.0.0&amp;REQUEST=DescribeFeatureType&amp;OUTPUTFORMAT=application%2Fgml%2Bxml%3B+version%3D3.2&amp;TYPENAME=ge:MappedFeature&amp;NAMESPACES=xmlns(ge,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fge-core%2F3.0)"
  xmlns:wfs="http://www.opengis.net/wfs/2.0" timeStamp="2015-05-20T13:08:13Z"
  xmlns:gml="http://www.opengis.net/gml/3.2" numberMatched="unknown" numberReturned="0">
  <!--NOTE: numberReturned attribute should be 'unknown' as well, but this would not validate against the current version of the WFS 2.0 schema (change upcoming). See change request (CR 144): https://portal.opengeospatial.org/files?artifact_id=43925.-->
</wfs:FeatureCollection>
```

If I make a simple request like [GetFeature with typename=ge:MappedFeature](http://194.66.252.155/m4eu/services?service=WFS&request=GetFeature&version=2.0.0&typename=ge:MappedFeature&)

It seems (I haven't checked all feature) that all features report:

```
<ge:mappingFrame xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://inspire.ec.europa.eu/codeList/MappingFrameTerm/topographicSurface"/>
```

My understanding then is that the filter should have returned all my ge:MappedFeature featuretypes and not none.   MrSnyder was this your expectation?

**Comment by nmtoken** [comment]
Changing my query to the below results in all (814) ge:MappedFeature features being returned:

```
<?xml version="1.0" encoding="UTF-8"?>
<GetFeature version="2.0.0" service="WFS" xmlns="http://www.opengis.net/wfs/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
    <Query typeNames="ge:MappedFeature">
        <Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
            <PropertyIsNil>
                <ValueReference>ge:mappingFrame/@xlink:href</ValueReference>
            </PropertyIsNil>
        </Filter>
    </Query>
</GetFeature>
```

I assume this means that ge:mappingFrame/@xlink:href is not being correctly evaluated.

**Comment by tfr42** [comment]
Since the initial question "Do you have examples of working FILTERs (urls) on WFS delivering complex features?" has been answered I will close this ticket.
@atellezarenas In case you have any other questions please send a message to the [deegree-users mailing-list] (http://www.deegree.org/community)

**Comment by zzeid** [comment]
Very interesting topic.
