### ISSUE TITLE
OGC certification badge is broken

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#563]
Currently the OGC certification badge is broken. 
Expected is that for the current stable release 3.3 the certification is renewed (if needed).

**Comment by segoerke** [comment]
The compliance records for deegree expired by May 9th.
For recertification it is required to have succesful testruns with the OGC account which holds the certificates for the "product". Currently that's the lat/lon company account.
The goal should be to have a valid certification ASAP.

**Comment by kraaka** [comment]
For the time being I unpublished the live-badge on the website. I will restore the badge as soon as there is a working link again.

**Comment by segoerke** [comment]
Okay. We are short before getting the certification badge back

**Comment by segoerke** [comment]
https://portal.opengeospatial.org/public_ogc/compliance/srv_ogc_compliance_badge.php?id=42&pid=1139

@kraaka This is working again :-)

**Comment by kraaka** [comment]
Badge is back on website as well.

Kind regards, Arie Kraak

Verzonden door TypeMail



Op 7 jul. 2015 10:11, bij 10:11, Sebastian Goerke <notifications@github.com> schreef:
