### ISSUE TITLE
wfs:Replace is not supported in current version 3.3.14.

### ISSUE THREAD

**Issue by larseggan** [deegree/deegree3#568]
When will wfs:Replace be available in degree?

**Comment by tfr42** [comment]
New features and enhancements will go into the 3.4 line. For the 3.3 line our plan is to provide bug fixes only. See wiki page [Bug or Feature](../wiki/Bug-or-Feature) explaining why.

This issue tracker is supposed to keep track of bugs, enhancements and features. When having questions about deegree and upcoming features then the best way is to use the mailing-lists. Questions like yours can be discussed on the [deegree-users mailing list] (http://www.deegree.org/community). Please read [our hints for posting a question to the deegree-users mailing list] (http://www.deegree.org/community/guidelines). 
Hope that helps.

**Comment by tfr42** [comment]
And if you consider this as a important enhancement for deegree 3.4 then send a feature request to the [deegree-users mailing list] (http://www.deegree.org/community). Read more in [Feature Request writing Guidelines](../wiki/Feature-Request-writing-Guidelines).
