### ISSUE TITLE
WFS 1.1.0 must support gml 3.1.1

### ISSUE THREAD

**Issue by jandm** [deegree/deegree3#571]
I am sending the following request to the Inspire Demo server:

http://demo.deegree.org/inspire-workspace/services/wfs?REQUEST=DescribeFeatureType&VERSION=1.1.0&SERVICE=WFS&outputFormat=text/xml;%20subtype=gml/3.1.1

I get the response:

This WFS is not configured to handle the output/input format 'text/xml; subtype=gml/3.1.1'

I know that Inspire is relying on WFS 2.0.0 and GML 3.2.1, but according to the spec WFS 1.1.0 must at least support GML 3.1.1.

**Comment by segoerke** [comment]
This is just a show case for demonstration purposes. Ticket can be closed, as deegree is capable to handle GML 3.1.1 through WFS 1.1.0
