### ISSUE TITLE
WFS GetFeature POST request with filter fails to evaluate xlink:href attribute

### ISSUE THREAD

**Issue by nmtoken** [deegree/deegree3#573]
Originally tested against deegree 3.3.13, but can confirm the issue remains in 3.3.14 and 3.4-pre17 releases. 

When using a WFS 2 GetFeature POST request where the ValueReference attempts to evaluate an attribute value _(tested specifically with xlink:href, may apply to other attributes)_, deegree fails to return any results.  deegree therefore fails the Filter Encoding Minimum Standard Filter conformance class.

For example using the following service end point: 

http://194.66.252.155/m4eu/services?

Looking at  ge:MappedFeature (ref: http://194.66.252.155/m4eu/services?service=WFS&request=GetFeature&version=2.0.0&typenames=ge:MappedFeature&count=3&)

If we use a **PropertyIsNull** operator (tests the specified property to see if it exists in the resource being evaluated. ref: OpenGIS Filter Encoding 2.0 Encoding Standard, section 7.7.3.5) as below we get no results, but we can see that ge:mappingFrame/@xlink:href should evaluate.

```
<?xml version="1.0" encoding="UTF-8"?>
<GetFeature version="2.0.0" service="WFS" handle="Filter on attribute test with PropertyIsNull deegree" count="100"
    xmlns="http://www.opengis.net/wfs/2.0" 
    xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:wfs="http://www.opengis.net/wfs/2.0"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd">
    <Query typeNames="ge:MappedFeature">
        <Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
            <PropertyIsNull>
                <ValueReference>ge:mappingFrame/@xlink:href</ValueReference>
            </PropertyIsNull>
        </Filter>
    </Query>
</GetFeature>
```

As a sanity check we can see that a similar filter query using the **PropertyIsNull** operator but without the xlink:href attribute returns results:

```
<?xml version="1.0" encoding="UTF-8"?>
<GetFeature version="2.0.0" service="WFS" handle="Filter on element test with PropertyIsNull deegree" count="100"
    xmlns="http://www.opengis.net/wfs/2.0" 
    xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:wfs="http://www.opengis.net/wfs/2.0"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd">
    <Query typeNames="ge:MappedFeature">
        <Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
            <PropertyIsNull>
                <ValueReference>ge:mappingFrame</ValueReference>
            </PropertyIsNull>
        </Filter>
    </Query>`
</GetFeature>
```

It follows too that using a **PropertyIsEqualTo** operator to evaluate the value of the attribute also fails:

```
<?xml version="1.0" encoding="UTF-8"?>
<GetFeature version="2.0.0" service="WFS" handle="Filter on attribute test with PropertyIsEqualTo deegree" count="100"
    xmlns="http://www.opengis.net/wfs/2.0" 
    xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:wfs="http://www.opengis.net/wfs/2.0"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd">
    <Query typeNames="ge:MappedFeature">
        <Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
            <PropertyIsEqualTo>
                <ValueReference>ge:mappingFrame/@xlink:href</ValueReference>
                <Literal>http://inspire.ec.europa.eu/codeList/MappingFrameTerm/topographicSurface</Literal>
            </PropertyIsEqualTo>
        </Filter>
    </Query>
</GetFeature>
```

Just checking that such a query should be possible, here it is working as expected in a GeoServer service.

end point: http://ogc.bgs.ac.uk/digmap625k_gsml32_insp_gs/wfs?  

Looking at  gsml:MappedFeature (ref: http://ogc.bgs.ac.uk/digmap625k_gsml32_insp_gs/wfs?service=WFS&request=GetFeature&version=2.0.0&typenames=gsml:MappedFeature&count=3&)

The null test returns no results

```
<GetFeature
    version="2.0.2"
    service="WFS"
    handle="Filter on attribute test with PropertyIsNull GeoServer"
    count="10"
    xmlns="http://www.opengis.net/wfs/2.0"
    xmlns:fes="http://www.opengis.net/fes/2.0"
    xmlns:gsml="http://xmlns.geosciml.org/GeoSciML-Core/3.2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd">
    <Query typeNames="gsml:MappedFeature">
        <Filter  
            xmlns="http://www.opengis.net/fes/2.0" 
            xmlns:xlink="http://www.w3.org/1999/xlink" 
            xmlns:gsml="http://xmlns.geosciml.org/GeoSciML-Core/3.2" >
            <PropertyIsNull>
                <ValueReference>gsml:samplingFrame/@xlink:href</ValueReference>
            </PropertyIsNull>
        </Filter>
    </Query>
</GetFeature>
```

Whilst the **PropertyIsEqualTo** request for an xlink:href attribute gives us results

```
<GetFeature
    version="2.0.2"
    service="WFS"
    handle="Filter on attribute test with PropertyIsEqualTo GeoServer"
    count="10"
    xmlns="http://www.opengis.net/wfs/2.0"
    xmlns:fes="http://www.opengis.net/fes/2.0"
    xmlns:gsml="http://xmlns.geosciml.org/GeoSciML-Core/3.2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd">
    <Query typeNames="gsml:MappedFeature">
        <Filter  
            xmlns="http://www.opengis.net/fes/2.0" 
            xmlns:xlink="http://www.w3.org/1999/xlink" 
            xmlns:gsml="http://xmlns.geosciml.org/GeoSciML-Core/3.2" >
            <PropertyIsEqualTo>
                <ValueReference>gsml:samplingFrame/@xlink:href</ValueReference>
                <Literal>http://inspire.ec.europa.eu/codelist/MappingFrameValue/topOfBedrock</Literal>
            </PropertyIsEqualTo>
        </Filter>
    </Query>
</GetFeature>
```

**Comment by tfr42** [comment]
@dstenger can you check this against OGC ETS for FE with TEAM engine please?

**Comment by tfr42** [comment]
Issue was mentioned in https://themes.jrc.ec.europa.eu/discussion/view/108800/examples-of-inspire-view-and-dowload-services-for-lclu

**Comment by tfr42** [comment]
PR is currently under preparation.

**Comment by tfr42** [comment]
see the related PR https://github.com/deegree/deegree3/pull/837 and https://github.com/lat-lon/deegree-cli-utility/pull/1 for [deegree-cli-utility](https://github.com/lat-lon/deegree-cli-utility)

**Comment by tfr42** [comment]
Please verify expected behavior against recent [release candidate RC5](http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices/3.4-RC5/deegree-webservices-3.4-RC5.war) and report your results here.

**Comment by DirkThalheim** [comment]
Just upgraded to deegree 3.4-RC5. Still have the issue: When mapping as primitive, I get an empty hy-n:hydroNodeCategory node.

I just looked into the schema. hy-n:hydroNodeCategory is a gml:ReferencedType. Maybe it's connected to this type. But I'm pretty sure for other FeatureTypes it worked.

**Comment by tfr42** [comment]
OK, thank you for the feedback. Can you provide or point me to sample test data for the linked workspace?

**Comment by DirkThalheim** [comment]
The complete workspace configuration can be found here: https://github.com/de-bkg/deegree-workspace-dlm250-inspire. From the `SQLFeatureStore` configuration dlm250 just take the hy-n:HydroNode `FeatureTypeMapping`. Here you can alter the `hy-n:hydroNodeCategory` mapping from `Feature` to `Primitive`.

Sample data can be imported from this GetFeature Request: http://sg.geodatenzentrum.de/wfs_dlm250_inspire?service=WFS&request=GetFeature&VERSION=2.0.0&TYPENAMES=hy-n:HydroNode&COUNT=10

Let me know if you need more information.

**Comment by marcus-mohr** [comment]
I have to confirm Dirk's problem with version 3.4-RC5. Furthermore it seems that it's not possible to use a filter with xlink:href in case of wms layerstyling. Neither a xlink:href filter in a sld nor in a feature layer seems to work. Thematically, this Problem is related to #587

**Comment by nmtoken** [comment]
I can confirm that **PropertyIsEqualTo** as below fails to return results on a service running 3.4-RC6

    <?xml version="1.0" encoding="UTF-8"?>
    <GetFeature version="2.0.0" service="WFS" handle="Filter on attribute test with PropertyIsEqualTo deegree" count="5"
        xmlns="http://www.opengis.net/wfs/2.0" 
        xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:wfs="http://www.opengis.net/wfs/2.0"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd">
        <Query typeNames="ge:MappedFeature">
            <Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/3.0">
                <PropertyIsEqualTo>
                    <ValueReference>ge:mappingFrame/@xlink:href</ValueReference>
                    <Literal>http://inspire.ec.europa.eu/codeList/MappingFrameTerm/topographicSurface</Literal>
                </PropertyIsEqualTo>
            </Filter>
        </Query>
    </GetFeature>

When a GetFeature request shows that the attribute value exists:

    http://ogcdev.bgs.ac.uk/test/services?service=WFS&request=GetFeature&version=2.0.0&typenames=ge:MappedFeature&count=3&

**Comment by lgoltz** [comment]
## Summary of the problems described in this issue

* WFS GetFeature POST request with filter fails to evaluate xlink:href attribute
  * The original theme of this issue.
  * Should work when the SQLFeatureStore configuration contains a primitive mapping instead of a feature mapping
  * Documentation in https://github.com/deegree/deegree3/blob/master/deegree-services/deegree-webservices-handbook/src/main/sphinx/featurestores.rst#mapping-strategies-for-xlinkhref-attributes
* WFS GetFeature  Response does not contain the` @xlink:href` attributes configured with primitive mapping
  * Described in https://github.com/deegree/deegree3/issues/573#issuecomment-330169448
  * New issue created: #875
  * Related to #866 
* Filtering on xlink:href in WMS layerstyling or in a feature layer does not work in BLOB mode and relation mode (primitive mapping as well as feature type mapping)
  * Described in https://github.com/deegree/deegree3/issues/573#issuecomment-349668095
  * Existing issue: #587

**Comment by lgoltz** [comment]
@nmtoken  I assume you are using a SQLFeatureStore with relational mapping? Can you check the configuration of `ge:mappingFrame`? It is configured as primitive or feature mapping? Differences (concering `@xlink:href`) are described in https://github.com/deegree/deegree3/blob/master/deegree-services/deegree-webservices-handbook/src/main/sphinx/featurestores.rst#mapping-strategies-for-xlinkhref-attributes

**Comment by nmtoken** [comment]
Yes, the backed is a PostgreSQL/PostGIS relational database, and mappings are done using a SQLFeatureStore. 

ge:mappingFrame is part of ge:MappedFeature which has the following mapping:

    
	<FeatureTypeMapping name="ge:MappedFeature" table="MineralOccurrence_vw">
		<FIDMapping prefix="M4EU.MAF_">
			<Column name="mineralOccurrenceDbk" type="integer"/>
		</FIDMapping>
		<Complex path="ge:shape">
			<Geometry path="." mapping="geometry"/>
		</Complex>
		<Complex path="ge:mappingFrame">
			<Feature path=".">
				<Href mapping="mappingFrame"/>
			</Feature>
		</Complex>
		<Complex path="ge:specification">
			<Feature path=".">
				<Href mapping="mineralOccurrenceId"/>
			</Feature>
		</Complex>
	</FeatureTypeMapping>

The complete mapping for the service and the XML schema is: 
[m4eu v1.1.2.zip](https://github.com/deegree/deegree3/files/1543617/m4eu.v1.1.2.zip)

**Comment by lgoltz** [comment]
@nmtoken Please change your configuration as follows to support filtering on `ge: mappingFrame/@xlink:href`:
```
<Complex path="ge:mappingFrame">
  <Primitive path="@xlink:href" mapping="mappingFrame"/>
</Complex>
```

This is described in the section [Mapping strategies for xlink:href attributes](https://github.com/deegree/deegree3/blob/master/deegree-services/deegree-webservices-handbook/src/main/sphinx/featurestores.rst#mapping-strategies-for-xlinkhref-attributes)  in the deegree-webservices Handbook.

**Comment by nmtoken** [comment]
@lgoltz thanks for the feedback.

I didn't create the mapping, just implementing it, so I will pass on this advice; I assume the strategy applies to any attributes I want to query, not just xlink:href?

**Comment by lgoltz** [comment]
> I assume the strategy applies to any attributes I want to query, not just xlink:href?

Yes, but usually other attributes than `@xlink:href` are not configured as feature mapping.
