### ISSUE TITLE
links for support in web page

### ISSUE THREAD

**Issue by nmtoken** [deegree/deegree3#575]
I see on the [deegree home page](http://www.deegree.org/) that you link to [questions tagged deegree on stackoverflow](https://stackoverflow.com/questions/tagged/deegree) though there are no such questions.  Perhaps the link would be better pointing to [questions tagged deegree on Geographic Information Systems Stack Exchange ](https://gis.stackexchange.com/questions/tagged/deegree).

**Comment by tfr42** [comment]
Thanks for that hint! I have updated https://github.com/deegree/deegree3/wiki/Bug-Report-writing-Guidelines.
