### ISSUE TITLE
Wrong reprojection in Hale 2.9.2

### ISSUE THREAD

**Issue by phasenohr** [deegree/deegree3#579]
Hi,

I just notice that reprojecting a shapefile from ETRS89-LAEA to urn:ogc:def:crs:EPSG::4258 does not work correctly in HALE 2.9.2 (resulting polygons totally misplaced) while it was working correctly in 2.9.0 with exactly the same input file and the same project file.
Is it a bug or are there some parameters I am unaware of?

Best regards,
Paul

**Comment by tfr42** [comment]
Dear Paul, thanks for the posting. How is this issue you are reporting here related to deegree? In case you want to report an issue to the HALE community please go to: http://community.esdi-humboldt.eu/projects/hale/boards

**Comment by phasenohr** [comment]
Sorry, I posted my message at the wrong place. It was obviously intended for the HALE community. Sorry about that.
Paul

**Comment by tfr42** [comment]
Thanks.
