### ISSUE TITLE
CSW error when creating database tables

### ISSUE THREAD

**Issue by diegomigliavacca** [deegree/deegree3#581]
When I click on the "setup tables" button in the "metadata" view, I get the following errors:

Error: ERROR: function addgeometrycolumn(unknown, unknown, unknown, unknown, unknown, unknown) is not unique Hint: Could not choose a best candidate function. You might need to add explicit type casts. Position: 8

Error: ERROR: column "bbox" does not exist

It happens in both Deegree 3.3 and 3.4 versions, using PostGis 2.1.

**Comment by lgoltz** [comment]
I think this issue is a duplicate of #531, isn't it?

**Comment by diegomigliavacca** [comment]
yes, it is a duplicate.
