### ISSUE TITLE
Unhandled surface geometry element: 'CompositeSurface' in GML Loader

### ISSUE THREAD

**Issue by MatteoMatassoni** [deegree/deegree3#586]
We tried to load an INSPIRE PS theme gml file into a feature store. With the present file an error of "Unhandled surface geometry element: 'CompositeSurface'" occurred. 

> GML import failed: Error in XML document (file '<file>', line: 6, column: 5, character offset: 619): Unhandled surface geometry element: '{http://www.opengis.net/gml/3.2}CompositeSurface'.

**Comment by dstenger** [comment]
This issue is fixed in #716.
