### ISSUE TITLE
Push new XSD files to schemas.deegree.org

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#608]
Files added in PR #598 should be published at schems.deegree.org
Using the job
http://buildserver.deegree.org/job/deegree-3.4-upload-schemas/
should do it.

**Comment by lgoltz** [comment]
The schema for the ExtendedCapabilities describing the SOAP support in the WMS capbilities was added manually to http://schemas.deegree.org/extensions/services/wms/1.3.0/soapwms.xsd.

**Comment by lgoltz** [comment]
The GetFeatureInfo.xsd from # 598 was provided: http://schemas.deegree.org/extensions/services/wms/1.3.0/GetFeatureInfo.xsd

**Comment by tfr42** [comment]
All XML schema files have been updated to version 3.4.0 and are available at http://schemas.deegree.org/.
see also #780, #751, #750, #735
