### ISSUE TITLE
Add 3.4 info to website

### ISSUE THREAD

**Issue by copierrj** [deegree/deegree3#611]
Many users are already using deegree 3.4. It is desirable to include information (downloads, handbook etc.) for this version on the website.

**Comment by lgoltz** [comment]
And I think many of the users expects this on the website. I was searching there for the handbook  already myself...

**Comment by tfr42** [comment]
Download the latest developer version 3.4-preX as ZIP and WAR from http://www.deegree.org/download.
The documentation is currently available from the Nexus repository only. The download links for the documentation files for the latest 3.4-pre19 release are:
 * [Documentation as PDF] (http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices-handbook/3.4-pre19/deegree-webservices-handbook-3.4-pre19.pdf)
 * [HTML files as a ZIP] (http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices-handbook/3.4-pre19/deegree-webservices-handbook-3.4-pre19.zip)

**Comment by tfr42** [comment]
For the RC the documentation shall made be available on the website.

**Comment by copierrj** [comment]
3.4-RC1 stuff is online:

http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices/3.4-RC1

Handbook:
- pdf: http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices-handbook/3.4-RC1/deegree-webservices-handbook-3.4-RC1.pdf
- zip: http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices-handbook/3.4-RC1/deegree-webservices-handbook-3.4-RC1.zip
- view online: http://download.deegree.org/documentation/3.4-RC1/html/

**Comment by stephanr** [comment]
I added a separate heading for the "Release Candidate" to the Joomla page and added the RC1 links for the online and zip version.

We should talk about the if the pdf verion should be linked there too.
