### ISSUE TITLE
Perform test against 3.4-pre21 release to ensure that the classloader issue is resolved

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#629]
Test scenario for this PR might be (based on the proposal of @stephanr in #580):
 - (re)load the workspace
 - request against WFS against a FeatureType against the database
 - request against WMS against a Layer against the database
 - check if there is a leak in the permgen space of the JVM with jvisualvm (Oracle JDK 7)

repeat this for at least n (>5) iterations with the following alternative setups:
- [x] Testing Apache Tomcat 7 with postgres driver in WEB-INF-lib
- [x] Testing Apache Tomcat 7 with postgres driver in shared location
- [x] Testing Apache Tomcat 7 with postgres driver in deegree workspace (which should fail!)
- [ ] Testing Oracle WLS 12 with oracle driver in WEB-INF-lib
- [ ] Testing Oracle WLS 12 with oracle driver in shared location
- [ ] Testing Oracle WLS 12 with oracle driver in deegree workspace (which should fail!)

**Comment by dstenger** [comment]
# Used deegree components #

* deegree 3.4-RC1
 * Downloaded via http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices/3.4-RC1/deegree-webservices-3.4-RC1.war
* Workspace: workspace-iceland 0.1
 * Provided via https://github.com/lat-lon/workspace-wfs20/tree/workspace-wfs20-0.1/workspace-iceland

# Preparations for tests #

## Preparation of workspace ##

* Setup of database.
* Added minimal layer configuration (iceland.xml).
```
<?xml version="1.0"?>
<FeatureLayers xmlns="http://www.deegree.org/layers/feature" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:l="http://www.deegree.org/layers/base" xmlns:d="http://www.deegree.org/metadata/description" xmlns:s="http://www.deegree.org/metadata/spatial" xsi:schemaLocation="http://www.deegree.org/layers/feature http://schemas.deegree.org/layers/feature/3.2.0/feature.xsd"
  configVersion="3.2.0">
  <FeatureStoreId>iceland</FeatureStoreId>
  <FeatureLayer>
    <l:Name>iceland</l:Name>
    <d:Title>iceland</d:Title>
    <s:CRS>EPSG:4326</s:CRS>
  </FeatureLayer>
</FeatureLayers>
```
* Added minimal themes configuration (iceland.xml).
```
<?xml version="1.0"?>
<Themes configVersion="3.2.0" xmlns="http://www.deegree.org/themes/standard" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:d="http://www.deegree.org/metadata/description"
  xmlns:s="http://www.deegree.org/metadata/spatial" xsi:schemaLocation="http://www.deegree.org/themes/standard http://schemas.deegree.org/themes/3.2.0/themes.xsd">
  <LayerStoreId>iceland</LayerStoreId>
  <Theme>
    <Identifier>iceland</Identifier>
    <d:Title>iceland</d:Title>
    <Layer>iceland</Layer>
  </Theme>
</Themes>
```
* Added minimal WMS service configuration (wms.xml).
```
<?xml version="1.0" encoding="UTF-8"?>
<wms:deegreeWMS configVersion="3.2.0" xmlns:wms="http://www.deegree.org/services/wms" xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dgws="http://www.deegree.org/webservices"
  xsi:schemaLocation="http://www.deegree.org/services/wms http://schemas.deegree.org/services/wms/3.2.0/wms_configuration.xsd">
  <wms:ServiceConfiguration>
    <wms:ThemeId>iceland</wms:ThemeId>
  </wms:ServiceConfiguration>
</wms:deegreeWMS>
```
* Modified SQLFeatureStore.
 * Removed GMLSchema.
 * Removed all mappings bound to gml namespace.

## Prepared requests ##

* Request to test WFS
 * POST http://localhost:8080/deegree-webservices-3.4-RC1/services/wfs
```
<?xml version="1.0" encoding="UTF-8"?>
<wfs:GetFeature service="WFS" version="2.0.0" xmlns:app="http://www.deegree.org/app"
 xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd
http://www.opengis.net/fes/2.0 http://schemas.opengis.net/filter/2.0/filter.xsd"
 count="10">
  <wfs:Query typeNames="app:osm_protected_area"/>
</wfs:GetFeature>
```
* Request to test WMS
 * http://localhost:8080/deegree-webservices-3.4-RC1/services/wms?LAYERS=iceland&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=default&FORMAT=image%2Fpng&CRS=EPSG%3A900913&BBOX=-3676444.4055399,9015551.6176472,-302819.72561491,10268507.385123&WIDTH=2758&HEIGHT=1024

## Prepared load test ##

* Following load test was created.
 * 5 threads firing 10 requests (50 requests in total).

# Tomcat 8 with Java 7 #

## Setup of test execution ##

* OS: Ubuntu 15.10
* Oracle JDK 1.7.0_80
* Tomcat 8.5.4
* PostgreSQL 9.4.8 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010, 64-bit
* PostGIS 2.1.8 r13780

## Testing Apache Tomcat 8 with postgres driver in WEB-INF-lib ##

* (re)load the workspace
 * No errors (tested 5 times).
* request against WFS against a FeatureType against the database
 * Average Response Time of load test: 0,172 seconds.
 * All requests return feature member (no timeouts or other errors).
* request against WMS against a Layer against the database
 * Average Response Time of load test: 5,651 seconds.
 * All requests return status code 200 (no timeouts or other errors).
* check if there is a leak in the permgen space of the JVM with jvisualvm
 * Sent 5 parallel WMS and WFS requests.
 * Reload of workspace (via deegree Console).
 * Each reload increases PermGen ~4000 Bytes (cannot be reverted with GC).

## Testing Apache Tomcat 8 with postgres driver in shared location ##

Moved postgis-jdbc-1.3.3.jar and postgresql-9.1-901-1.jdbc4.jar to apache-tomcat-8.5.4/lib/.

* (re)load the workspace
 * No errors (tested 5 times).
* request against WFS against a FeatureType against the database
 * Average Response Time of load test: 0,194 seconds.
 * All requests return feature member (no timeouts or other errors).
* request against WMS against a Layer against the database
 * Average Response Time of load test: 5,734 seconds.
 * All requests return status code 200 (no timeouts or other errors).
* check if there is a leak in the permgen space of the JVM with jvisualvm
 * Sent 5 parallel WMS and WFS requests.
 * Reload of workspace (via deegree Console).
 * Each reload increases PermGen ~2000 Bytes (cannot be reverted with GC).

## Testing Apache Tomcat 8 with postgres driver in deegree workspace (which should fail!) ##

Moved postgis-jdbc-1.3.3.jar and postgresql-9.1-901-1.jdbc4.jar to workspace/modules/.

* (re)load the workspace
 * After workspace reload has been executed: WMS cannot be activated and WFS does not return any data.

# Tomcat 8 with Java 8 #

## Setup of test execution ##

* OS: Ubuntu 15.10
* Oracle JDK 1.8.0_101
* Tomcat 8.5.4
* PostgreSQL 9.4.8 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010, 64-bit
* PostGIS 2.1.8 r13780

## Testing Apache Tomcat 8 with postgres driver in WEB-INF-lib ##

* (re)load the workspace
 * No errors (tested 5 times).
* request against WFS against a FeatureType against the database
 * Average Response Time of load test: 0,131 seconds.
 * All requests return feature member (no timeouts or other errors).
* request against WMS against a Layer against the database
 * Average Response Time of load test: 4,529 seconds.
 * All requests return status code 200 (no timeouts or other errors).
* check if there is a leak in the permgen space of the JVM with jvisualvm
 * There is no PermGen in Java 8 (just Metaspace).

## Testing Apache Tomcat 8 with postgres driver in shared location ##

Moved postgis-jdbc-1.3.3.jar and postgresql-9.1-901-1.jdbc4.jar to apache-tomcat-8.5.4/lib/.

* (re)load the workspace
 * No errors (tested 5 times).
* request against WFS against a FeatureType against the database
 * Average Response Time of load test: 0,131 seconds.
 * All requests return feature member (no timeouts or other errors).
* request against WMS against a Layer against the database
 * Average Response Time of load test: 4,342 seconds.
 * All requests return status code 200 (no timeouts or other errors).

## Testing Apache Tomcat 8 with postgres driver in deegree workspace (which should fail!) ##

Moved postgis-jdbc-1.3.3.jar and postgresql-9.1-901-1.jdbc4.jar to workspace/modules/.

* (re)load the workspace
 * After workspace reload has been executed: WMS cannot be activated and WFS does not return any data.

# Oracle WLS #

## Setup of test execution ##

* OS: CentOS Linux release 7.0.1406 (Core)
* Oracle JDK 1.7.0_67
* WebLogic Server Version: 12.1.2.0.0
* PostgreSQL 9.4.8 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010, 64-bit
* PostGIS 2.1.8 r13780

Deployment of deegree fails on WLS 12c.
An Issue was created: https://github.com/deegree/deegree3/issues/744

# Conclusion #

* No unexpected errors occurred with Tomcat 7 and 8.
* PermGen increases less during workspace reload when shared location is used for jdbc drivers (see Tomcat 8 with Java 7).
* Deployment on WLS was not possible (see Oracle WLS).

**Comment by tfr42** [comment]
All tests were successful on Tomcat. Issue is resolved.
