### ISSUE TITLE
Update all schema files to use 3.4 version 

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#650]
For all relevant XSD files hosted on [schemas.deegree.org] (http://schemas.deegree.org/) a 3.4 version shall be available.

**Comment by tfr42** [comment]
Workaround is to checkout the relevant pull requests and run the shell script used by the build job http://buildserver.deegree.org/job/deegree-3.4-upload-schemas/

**Comment by copierrj** [comment]
first order or business: prepare pull request with the required changes to the schema files.

possible results:
- it actually does work ok
- we need to solve the problem or work around it

next step to be discussed by the tmc (?)

**Comment by copierrj** [comment]
most likely obstacle: xml schema imports (used by WMS)

**Comment by copierrj** [comment]
required changes:

- update schema directory name to '3.4.0'
- update references to schema files (java and xsd)
- extend configVersion enumerations

**Comment by stephanr** [comment]
Hi, i am starting to work on this at the FOSS4G Bonn Code Sprint
