### ISSUE TITLE
Multiple TYPENAMES interpreted as Join Query

### ISSUE THREAD

**Issue by jarped** [deegree/deegree3#666]
Deegree interprets multiple TYPENAMES as being a join query, even without a join predicate filter being set. Today we get the following reply:

> Join queries between multiple feature types are currently not supported

I believe the correct response by deegree to such a request should be to return the features without performing any joining. My interpretation is based on the following excerpt from the standard:

> A join operation query shall be encoded by:
> 
> 1) listing the feature types to join using the typeNames parameter (see 7.9.2.4.1)
> 
> 2) **specifying a join predicate between the feature types using a filter expression** (see OGC 09-026r2,  Clause 7)

Ref http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#108 (7.9.2.5.3.1 Join queries in ISO19142)

**Comment by tfr42** [comment]
Thanks for this finding. This is an issue for 3.4, right? Currently the deegree WFS 3.4 is not fully supporting the WFS 2.0 conformance classes "Standard Joins", "Standard Joins", and "Temporal Joins". Support for those conformance classes is planned for the next release version 3.5.

**Comment by jarped** [comment]
Actually, I see this issue in 3.3.17. Here's an example (added count just to limit size of requested data). Both featuretypes work if called separately:
http://wfs.geonorge.no/skwms1/wfs.skolerogbarnehager?service=WFS&request=GetFeature&version=2.0.0&srsName=urn:ogc:def:crs:EPSG::4258&typeNames=app:Barnehage&count=2

and

http://wfs.geonorge.no/skwms1/wfs.skolerogbarnehager?service=WFS&request=GetFeature&version=2.0.0&srsName=urn:ogc:def:crs:EPSG::4258&typeNames=app:Skole&count=2

However, if we try to fetch both at once:

http://wfs.geonorge.no/skwms1/wfs.skolerogbarnehager?service=WFS&request=GetFeature&version=2.0.0&srsName=urn:ogc:def:crs:EPSG::4258&typeNames=app:Barnehage,app:Skole&count=2

And the same with bbox:
http://wfs.geonorge.no/skwms1/wfs.skolerogbarnehager?service=WFS&request=GetFeature&version=2.0.0&srsName=urn:ogc:def:crs:EPSG::32633&typeNames=app:Barnehage,app:Skole&count=2

My understanding is that both the two last calls should not be interpreted as join queries.

**Comment by jarped** [comment]
I'm trying to find some explicit source for this in the standard. So far this is the closest I've gotten:

> ...If more that one feature type name is specified as the value of the TYPENAMES keyword (***in a non-join query***), a corresponding list of parameter lists shall be specified (see 6.2.5.3)....

http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#99

I'll keep looking.

**Comment by jarped** [comment]
Example POST-query that returns data as expected:

```
<wfs:GetFeature version="2.0.0" service="WFS"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" resolveDepth="1"
    xsi:schemaLocation="http://www.opengis.net/fes/2.0 http://schemas.opengis.net/filter/2.0/filterAll.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd"
    xmlns:fes="http://www.opengis.net/fes/2.0"
    xmlns:wfs="http://www.opengis.net/wfs/2.0"
    xmlns:gml="http://www.opengis.net/gml/3.2"
    xmlns:app="http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/Skolerogbarnehager">

    <wfs:Query typeNames="app:Skole">
        <fes:Filter >
            <fes:Within>
               <fes:ValueReference>app:posisjon</fes:ValueReference>
                <gml:Envelope srsName="urn:ogc:def:crs:EPSG::32633">
                    <gml:lowerCorner>-82143.5815086 6804291.3326</gml:lowerCorner>
                    <gml:upperCorner>-5567.93749142 6843648.9614</gml:upperCorner>
                </gml:Envelope>
            </fes:Within>
        </fes:Filter>
    </wfs:Query>

    <wfs:Query typeNames="app:Barnehage">
        <fes:Filter >
            <fes:Within>
                <fes:ValueReference>app:posisjon</fes:ValueReference>
                <gml:Envelope srsName="urn:ogc:def:crs:EPSG::32633">
                    <gml:lowerCorner>-82143.5815086 6804291.3326</gml:lowerCorner>
                    <gml:upperCorner>-5567.93749142 6843648.9614</gml:upperCorner>
                </gml:Envelope>
            </fes:Within>
        </fes:Filter>
    </wfs:Query>
</wfs:GetFeature>
```

**Comment by tfr42** [comment]
Issue occurs also in case when requesting multiple FeatureTypes and one of the requested FeatureTypes has no Feature elements.
