### ISSUE TITLE
Handbook for 3.3.18 is missing

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#668]
The release build job completed successfully but the handbook is not available at http://download.deegree.org/documentation/3.3.18/html

**Comment by tfr42** [comment]
Files are present in repo.deegree.org
http://nexus.deegree.org/content/groups/public/org/deegree/deegree-webservices-handbook/3.3.18/deegree-webservices-handbook-3.3.18.zip
http://nexus.deegree.org/content/groups/public/org/deegree/deegree-webservices-handbook/3.3.18/deegree-webservices-handbook-3.3.18.pdf

**Comment by stephanr** [comment]
I had added the handbooks, see [Releasing-deegree](/deegree/deegree3/wiki/Releasing-deegree)
