### ISSUE TITLE
Transfer plaza.deegree.org to new server sponsored by FOSSGIS e.V.

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#675]
The transfer of the domain deegree.org to the OSGeo foundation has been completed (see http://nic.com/whois?domain=deegree.org). The current server plaza.deegree.org (provided by lat/lon) shall be transfered to a new server sponsored by the german chapter of OSGeo foundation / FOSSGIS e.V. (see http://www.fossgis.de/wiki/F%C3%B6rderantr%C3%A4ge/deegree_org_hosting for further information). 
Questions:
- Install new software components for Nexus and Jenkins and other from scratch?
  or
- Copy everthing from plaza.deegree.org to the new server?

**Comment by tfr42** [comment]
@MrSnyder @copierrj @stephanr Please post your comments.

**Comment by copierrj** [comment]
I would prefer a fresh installation to make sure we do not (by accident) use old versions of software packages. The configuration could / should be copied of course.

**Comment by copierrj** [comment]
In case people are wondering how this system is currently used; this is how we do releases:

https://github.com/deegree/deegree3/wiki/Releasing-deegree

**Comment by stephanr** [comment]
If the hosting will remain at hetzner the server could transferred to the new owner (by passing a token) without work at the server side.

If the server will be migrated to a new/other system, it might be also necessary to handle:
- Security Settings / Firewall / User Accounts
- IP-Address / CNAME changes for the aliases of repo.deegree.org, demo.deegree.org, schemas.deegree.org, etc. ... 

I would prefer to transfer only the owner if possible, so the saved time can be used for upgrading components like nexus.
If that is not possible a clean install would be better but will also requires much more effort (time)  to handle.

**Comment by tfr42** [comment]
The transfer at hetzner is completed and the [wiki page Infrastructure](../wiki/Infrastructure) has been updated.
