### ISSUE TITLE
Service parameter value is CaseSensitive

### ISSUE THREAD

**Issue by zzeid** [deegree/deegree3#691]
It is possible to get answer from deegree 3.3.18 server for requests like:

- ?SERVICE=WFS&VERSION=2.0.0&REQUEST=**GetCapabilities**
- ?SERVICE=WFS&VERSION=2.0.0&REQUEST=**GETCAPABILITIES**

but trying to get answer for request: ?SERVICE=WFS&VERSION=2.0.0&REQUEST=_**LISTSTOREDQUERIES** (in **UPPERCASE**) - I get an error:_

`<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="2.0.0">
    <ows:Exception exceptionCode="InvalidParameterValue" locator="request">
        <ows:ExceptionText>`
            _**No service for request type 'LISTSTOREDQUERIES' is configured / active.**_
        `</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>`

...?SERVICE=WFS&VERSION=2.0.0&REQUEST=**ListStoredQueries** response correctly.
deegree 3.4.RC1 correctly handles with REQUEST=**LISTSTOREDQUERIES** - in UPPERCASE too.

**Comment by nmtoken** [comment]
Not sure if this should be seen as a bug, the specification tells us that the value is case sensitive.  So it should be 'GetCapabilities' and not 'GETCAPABILITIES' and similarly it should be  'ListStoredQueries' and not 'LISTSTOREDQUERIES'.

**Comment by tfr42** [comment]
The [OGC WFS 2.0 spec](http://portal.opengeospatial.org/files/?artifact_id=39967) states:
6.2.5.2 Parameter ordering and case
Parameter names shall not be case sensitive, but parameter values shall be case sensitive. In this International Standard, parameter names used in KVP encoding are typically shown in uppercase for typographical clarity, not as a requirement."

**Comment by nmtoken** [comment]
The syntax of a KVP parameter is name=value&

> Parameter names shall not be case sensitive, but parameter values shall be case sensitive

So the parameter name here is **REQUEST**,  but the issue is not with the parameter name, it is with the parameter value.

> In this International Standard, parameter names used in KVP encoding are typically shown in uppercase for typographical clarity, not as a requirement."

This sentence doesn't mention spelling of values, only names.

So the issue still stands.  

The correct **values** are _GetCapabilities_ and not _GETCAPABILITIES_ and similarly it should be _ListStoredQueries_ and not _LISTSTOREDQUERIES_
