### ISSUE TITLE
No features returned for FT Address on demo.deegree.org 

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#695]
WFS http://demo.deegree.org/inspire-workspace/services/wfs is not returning data for FeatureType "Address".

**Comment by JuergenWeichand** [comment]
Probably the following line is missing in the **MemoryFeatureStore** `inspire`.

`<GMLFeatureCollection version="GML_32">../../data/addresses.xml</GMLFeatureCollection>`

**Comment by lgoltz** [comment]
Maybe the features was not inserted? There are request to delete and insert features. Currently the requests GetFeature -> All_110.xml and All_200.xml returns features.

**Comment by lgoltz** [comment]
POST request   http://demo.deegree.org/inspire-workspace/services/wfs with 
```
<GetFeature xmlns="http://www.opengis.net/wfs/2.0" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ad="urn:x-inspire:specification:gmlas:Addresses:3.0" xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" service="WFS" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd">
  <Query typeNames="ad:Address"/>
</GetFeature>
```
returns some data.
