### ISSUE TITLE
WPS over https

### ISSUE THREAD

**Issue by awst-baum** [deegree/deegree3#706]
Is it possible to offer WPS services via https with deegree?
I've deployed 3.3.18 on a tomcat running via https but the GetCapabilities the server produces lists all operations with http (and not https) links. Accordingly, I get errors when trying to describe or execute processes.
Can I configure the protocol in the server somehow?

**Comment by tfr42** [comment]
Yes, you can use deegree with HTTPS (SSL/TLS). To configure your Apache Tomcat container to provide HTTPS please check the [Tomcat SSL HowTo] (https://tomcat.apache.org/tomcat-8.5-doc/ssl-howto.html) for more information. A short intro gives https://dzone.com/articles/setting-ssl-tomcat-5-minutes. Or you deploy deegree behind a [Apache httpd with SSL enabled](http://httpd.apache.org/docs/2.4/en/ssl/).

For both cases you configure the deegree service controller in the ```services/main.xml``` configuration file. Check chapter [5.7. Service controller](http://download.deegree.org/documentation/3.3.18/html/webservices.html#service-controller) for more information.
