### ISSUE TITLE
Support OGC HTTP URI style CRS references

### ISSUE THREAD

**Issue by stempler** [deegree/deegree3#711]
deegree currently doesn't support CRS references like the following:

```
srsName="http://www.opengis.net/def/crs/EPSG/0/25832"
```

This notation resolves to the actual definitions provided by the OGC. It has been around for some time and is supported in other solutions like [GeoServer](http://docs.geoserver.org/stable/en/user/services/wfs/webadmin.html#gml).

The closest thing I could find as kind of official reference for this is an OGC Whitepaper from 2010 ([OGC 10-124r1](http://portal.opengeospatial.org/files/?artifact_id=39467)). Related to that is also this statement:

> In June 2010 OGC revised the naming policy to use http URIs to identify persistent OGC resources instead of URNs. The change to URIs was primarily to make resolution easier, and in order that OGC technologies can integrate with linked data and semantic web. 

Recent OGC documents (for instance the GML 3.3 spec) also feature this style of reference in all their GML examples.

I also heard from different sources that this is the notation style that should be used in INSPIRE GML documents, but haven't found any official reference for that yet.

**Comment by zzeid** [comment]
_deegree_ supports custom CRS. You can define  Your's own. See http://wiki.deegree.org/deegreeWiki/deegree3/WorkspaceConfiguration/CRSConfiguration for details.
INSPIRE _Technical Guidelines_ propose/**recommend** to use the http URLs like above. See any TG at http://inspire.ec.europa.eu/index.cfm/pageid/2 .

**Comment by stempler** [comment]
So you don't think it would make sense to have them supported without the need for a custom configuration?

How are the CRS definitions in deegree maintained?
Is this done manually or is there at least for parts an automated generation process, e.g. based on the EPSG registry (database)?

**Comment by dstenger** [comment]
We have created a new issue regarding the status and maintenance of CRS definitions in deegree: #715

**Comment by tfr42** [comment]
Please verify expected behavior against recent [release candidate 3.4-RC5](http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices/3.4-RC5/deegree-webservices-3.4-RC5.war) and report your results here.
