### ISSUE TITLE
maven jaxb plugin update

### ISSUE THREAD

**Issue by copierrj** [deegree/deegree3#731]
We should update the maven jaxb plugin to use the latest version.

**Comment by tfr42** [comment]
And to ensure that the build can be configured to use active HTTP proxy settings of the JVM executing the Maven process.
The ```useActiveProxyAsHttpproxyuseActiveProxyAsHttpproxy```option is available as of version 0.13.1 of the ```org.jvnet.jaxb2.maven2org.jvnet.jaxb2.maven2:maven-jaxb2-plugin```.

**Comment by tfr42** [comment]
@stephanr Is the [CatalogResolver](https://github.com/deegree/deegree3/blob/master/uncoupled/deegree-jaxb-resolver/src/main/java/org/deegree/uncoupled/jaxb/CatalogResolver.java) capable to use the global proxy settings?

**Comment by stephanr** [comment]
@tfr42  The CatalogResolver only interferes the resolve of local available deegree schema files.

All other schema files or deegree schmeas not found in the classloader classpath will use the regular resolver, `com.sun.org.apache.xml.internal.resolver.tools.CatalogResolver ` class from the plugin.

It has to be checked that the update of the jaxb-plugin does not break the logic to use the schema files locally if available.
Personally i do not know if the `0.13.1` plugin has changes in the lookup procedure or classes, if so the CatalogResolver maybe needs a update to reflect this.
