### ISSUE TITLE
FeatureStore wizard fails to create mapping for GML application schemas with cyclic references

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#742]
In case the GML application schema has cyclic references the FeatureStore wizard skips the generation of the respective DDL and FeatureType mapping.

Example:
in http://inspire.ec.europa.eu/schemas/ps/4.0 the `<element name="legalFoundationDocument" nillable="true"/>` misses a mapping in the generated SQLFeatureStore 
`<FeatureTypeMapping/>` and generated DDL.

Effected classes:
https://github.com/deegree/deegree3/blob/master/deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/DDLCreator.java
https://github.com/deegree/deegree3/blob/master/deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/SQLFeatureStoreConfigWriter.java

**Comment by dstenger** [comment]
Fixed by #817.
