### ISSUE TITLE
Disable resolve of xlink:href for codelist values

### ISSUE THREAD

**Issue by DirkThalheim** [deegree/deegree3#747]
INSPIRE uses xlink:href attributes to specify codelist values as URLs. For example:
-  `<gn:nativeness xlink:href="http://inspire.ec.europa.eu/codelist/NativenessValue/endonym"/>`
-  `<gn:nameStatus xlink:href="http://inspire.ec.europa.eu/codelist/NameStatusValue/official"/>`

deegree however interprets every xlink:href as complex feature and tries to resolve those references. When importing data as GML this extremely slows down the process as for every URL a request is performed to resolve the reference (which of course fails).

It should be possible to disable the default behaviour of reference resolving for a configurable set of URL paths.

**Comment by tfr42** [comment]
> It should be possible to disable the default behaviour of reference resolving for a configurable set of URL paths.

To be defined:

- which configuration file should have this option?
- which format for defining the URL path should be used?
  -  regex pattern style or simple by defining a base URL path

**Comment by tfr42** [comment]
Please verify expected behavior against recent [release candidate 3.4-RC5](http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices/3.4-RC5/deegree-webservices-3.4-RC5.war) and report your results here.
