### ISSUE TITLE
Support inserting features via WFS-T that reference features already in the service

### ISSUE THREAD

**Issue by stempler** [deegree/deegree3#749]
I'm wondering if it is possible to insert features into a WFS via a transaction where a feature that is inserted references a feature or features that are already part of the database.

I experimented with an example with two transactions where in the second one the feature inserted references the feature inserted in the first transaction. If deegree supports this, the question is how to formulate the reference and if some other configuration is necessary. I tried it with a local reference, but the service answers that it cannot be resolved (because the ID cannot be resolved within the request).

Example workspace and WFS-Transaction are contained in this archive: [deegree_transaction_references.zip](https://github.com/deegree/deegree3/files/432593/deegree_transaction_references.zip)

This is related to #743 as support for this could be one step to allowing the client to split WFS transactions over mutliple requests, even if the features are referencing each other.

**Comment by stempler** [comment]
One possibility I see would be using an external URL of a KVP GetFeatureById request to the feature, but for that the external location must be known and may not change. Also this might probably entail including the service version in the URL.

**Comment by stempler** [comment]
**Remark:** If both features and the local reference are included in one request, storing the features will work, and when part of a GetFeature response a local reference is used to reference the feature if it is part of the response, otherwise the reference is a request to the WFS.
What is stored in the reference field in the database is the local reference including the identifier prefix (so the value in this example is `#CP_CADASTRALZONING_Bundesland_02`).

**Comment by lgoltz** [comment]
Currently it is not possible to insert a feature with a reference to an already inserted feature. deegere uses the GmlDocumentIdContext to resolve references in a FeatureCollection. The context of this  GMLReferenceResolver  is limitied to the FeatureCollection. A FeatureStoreGMLIdResolver is already implemented to resolve references using a FeatureStore, but this is not used during insert.

**Comment by tfr42** [comment]
The scenario to be supported is that a client is sending 2 (or more) WFS-T Insert requests where the FeatureCollection of the 2nd Insert request contains a Feature with reference to a feature sent within the 1st Insert request.

Example:
- step 1) The client is sending a first WFS-T Insert Request ```wfs-insert-1``` with a FeatureCollection containing 2 Features with id  e.g. ```feature-1``` and ```feature-2```.
Where ```feature-2``` has a reference to ```feature-1```.
- step 2) Then the client is sending a second WFS-T Insert Request ```wfs-insert-2``` with a FeatureCollection containing 2 more Features with id ```feature-3``` and ```feature-4```. 
Where ```feature-3``` has a reference to ```feature-1```.

Expected is that deegree  ```GMLReferenceResolver``` can resolve the reference from step 2 for WFS-T Insert request (look back approach). A look ahead approach where the ```GMLReferenceResolver``` can resolve a reference from ```feature-1``` to ```feature-4``` would be nice to have.

**Comment by tfr42** [comment]
Please verify expected behavior against recent [release candidate 3.4-RC5](http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices/3.4-RC5/deegree-webservices-3.4-RC5.war) and report your results here.
