### ISSUE TITLE
Error/exception when generating DDL (postgis) from XSD with non-ascii characters in tag-names.

### ISSUE THREAD

**Issue by bgrotan** [deegree/deegree3#757]
Goal: Generate PostgreSQL/PostGIS tables from  XSD and expose as WFS 2.0
(XSD generated from EA - Enterprise Architect). 

Tested with Java7/Tomcat8

Reproduction:
(down)load [RadonAktsomhet.xsd](https://github.com/deegree/deegree3/files/436909/RadonAktsomhet.txt)
(rename from txt) into deegree webapp-folders and reload config.

The problem occurs when trying to generate the DDL from the XSD. Deegree webinterface gave me a non-inuitive errormessage. Looking at the stacktrace in tomcat server logfiles, it seems to me to be related to the xml parser somehow. Please advice if this is something that can be reconfigured or if it is a deeper problem with an external library outside Deegree.

If I change the xsd-file so no norwegian (æøå) characters are found in tag-names (område -> omrade)
the DDL-process works as expected, and also WFS 2.0 getCapabilities and other get*-calls are functioning as expected.

The goal here is to get Deegree to generate the DDL from the valid XSD-file, but before running the DDL - I want to change suggested column names to only consist of a-z. 

We also see that some relations from the original UML model does not propagate down to the DDL. If this problem is related or seperate issue, I am not sure.

**Comment by tfr42** [comment]
Thanks for your posting. Can you please post which version of deegree you are using for generating the SQL DDL and deegree FeatureStore configuration files? 
And please post for which version of deegree you would like to have the bug fix.

**Comment by bgrotan** [comment]
deegree version is 3.3.18

I would rather have a fix for 3.3.x than wait around for 3.4 since we are planning to make use of Deegree for our national public delivery of datasets with WFS 2.0 and GML 3.2.1

**Comment by tfr42** [comment]
> We also see that some relations from the original UML model does not propagate down to the DDL. If this problem is related or seperate issue, I am not sure.
This issue might be related to #746 or #742 when using deegree 3.4.

**Comment by tfr42** [comment]
Besides deegree FeatureStore config is supporting unicode characters the database must support unicode for table and column names too. PostgreSQL and Oracle DBMS do support this but other may not. Hint needs to be added to the deegree handbook.

**Comment by tfr42** [comment]
@bgrotan SNAPSHOT Version for testing is available.

**Comment by tfr42** [comment]
Fixed in 3.4.2
