### ISSUE TITLE
Remove unused/outdated branches form deegree3 repository

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#762]
Remove:
- [x] deegree-3.2-staging
- [x] deegree-3.3-staging
- [x] handbook
- [ ] feature/gml-temporal-support

Clarification needed for:
- [ ] revert-400-jrcportal-1723-resourceHandling-ISOMetadataStore

**Comment by tfr42** [comment]
@MrSnyder input is welcome if these branches are still required

**Comment by tfr42** [comment]
deleted deegree-3.2-staging, 3.3-staging and handbook

**Comment by stephanr** [comment]
Discussed by TMC members in CodeSprint 2024 in Dortmund and decided to close as this is obsolete.
