### ISSUE TITLE
WMS GetFeatureInfo is empty in case of XSLT is used to transform complex data models

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#781]
In the case of a GetFeatureInfo is configured via XSLT, an exception occurs for complex data models that the XML namespace ```xsi``` is not bound. And the GFI response is empty.

**Comment by tfr42** [comment]
For reproducer we need the deegree workspace including the XSLT document and the GFI response document in GML format.

**Comment by JuergenWeichand** [comment]
[LDBV] Attached a simple INSPIRE Protected Sites testcase containing GML and XSLT documents.
[ps_testcase.zip](https://github.com/deegree/deegree3/files/583697/ps_testcase.zip)

Sample data based on dataset `Schutzgebiete des Naturschutzes`.
> Datenquelle: Bayerisches Landesamt für Umwelt, www.lfu.bayern.de

Please use the following schema to setup your deegree workspace http://inspire.ec.europa.eu/schemas/ps/4.0/ProtectedSites.xsd.

**Comment by JuergenWeichand** [comment]
The following exception occurs using deegree 3.4 RC3.

`SystemId Unknown; Line #1; Column #253667; The prefix "xsi" for attribute "xsi:nil" associated with an element type "ps:legalFoundationDate" is not bound.`

**Comment by tfr42** [comment]
Please verify expected behavior against recent [release candidate 3.4-RC5](http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices/3.4-RC5/deegree-webservices-3.4-RC5.war) and report your results here.

**Comment by JuergenWeichand** [comment]
[LDBV] We will verify the solution.

**Comment by JuergenWeichand** [comment]
[LDBV] Bug is successfully fixed in 3.4-RC5.
