### ISSUE TITLE
EPSG-related test-error in RemoteWMSTileStore

### ISSUE THREAD

**Issue by jarped** [deegree/deegree3#798]
In **deegree-datastores/deegree-tilestores/deegree-tilestore-remotewms/src/test/java/org/deegree/tile/persistence/remotewms/RemoteWMSTileStoreTest.java**:
> assertEquals( "urn:opengis:def:crs:epsg::26912", metadata.getCoordinateSystems().get( 0 ).getId() );

results in
> Failed tests:   testGetMetdataEPSG26912(org.deegree.tile.persistence.remotewms.RemoteWMSTileStoreTest): expected:<[urn:opengis:def:crs:epsg::]26912> but was:<[http://www.opengis.net/gml/srs/epsg.xml#]26912>

Tried both 3.3.20 and master

**Comment by lgoltz** [comment]
Which java version/type was used?

**Comment by jarped** [comment]
**java -version**

>java version "1.8.0_111"
>Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
>Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**javac -version**
> javac 1.8.0_111

**Comment by lgoltz** [comment]
then it is related to #625

**Comment by jarped** [comment]
switched to 7:
**java -version**

>java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

Same issue persists

**Comment by jarped** [comment]
Pull-request #799 fixes it for me.

**Comment by jarped** [comment]
When I run integration-tests it does however give return the urn and not the url.

**Comment by jarped** [comment]
Stopped being an issue. Must have been a local setting. Closing.
