### ISSUE TITLE
Error in wps-test

### ISSUE THREAD

**Issue by jarped** [deegree/deegree3#800]
Error while building. 

In **deegree-processproviders/deegree-processprovider-jrxml/src/test/java/org/deegree/services/wps/provider/jrxml/contentprovider/TestSubreportContentProviderTest.java**

> assertEquals( 3, inputs.size() );

results in 

> Failed tests:   testInspectInputParametersFromJrxml(org.deegree.services.wps.provider.jrxml.contentprovider.TestSubreportContentProviderTest): expected:<3> but was:<1>

Tried both 3.3.20 and master

**Comment by tfr42** [comment]
Can you please post which JDK Version you are using?

**Comment by jarped** [comment]
Same with both Oracle 7 and 8.

**Comment by jarped** [comment]
Stopped being an issue. Must have been a local setting. Closing.
