### ISSUE TITLE
DDL for PostgreSQL created with deegree contains too long column names 

### ISSUE THREAD

**Issue by lgoltz** [deegree/deegree3#827]
The DDL for HydroPhysicalWaters [1] created with the deegree-cli-utility [2] using deegree contains too long column names (e.g. gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_3137881). 

Expected is that the column names are truncated to the length specified with _maxLength_.

[1] http://inspire.ec.europa.eu/schemas/hy-p/4.0/HydroPhysicalWaters.xsd
[2] https://github.com/lat-lon/deegree-cli-utility/tree/deegree-3.4

**Comment by dstenger** [comment]
Pull request: https://github.com/deegree/deegree3/pull/838
