### ISSUE TITLE
DescribeFeatureType and GetFeature: outputFormat=application/gml+xml; version=3.2 returns “InvalidParameterValue”

### ISSUE THREAD

**Issue by pw321** [deegree/deegree3#830]
Hello everyone, 

I am having problems with wfs DescribeFeatureType and GetFeature with outputFormat= application/gml+xml; version=3.2 (version doesn’t matter). 

However text/xml works fine. It could be an encoding problem.

i.e. on the INSPIRE-workspace (general bug in my opinion)

Sending the request: 

…/deegree/services/wfs?service=WFS&REQUEST=DescribeFeatureType&OUTPUTFORMAT=application/gml+xml; version=3.2&VERSION=2.0.0

Returns:

...
<ows:Exception exceptionCode="InvalidParameterValue" locator="outputFormat">
    <ows:ExceptionText>This WFS is not configured to handle the output/input format 'application/gml xml; version=3.2'</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
...

However these two requests work:

…/deegree/services/wfs?service=WFS&request=DescribeFeatureType&OUTPUTFORMATS=application/gml+xml; version=3.2&VERSION=2.0.0

Thus it works - to my surprise - with outputFormats, which I thought would not work in a DescribeFeature-Request. But according to OGC WFS... it should be outputFormat (without the s).

…/deegree/services/wfs?service=WFS&request=DescribeFeatureType&VERSION=2.0.0&OUTPUTFORMAT=application%2Fgml%2Bxml%3B version%3D3.2

This working request indicates an encoding issue, maybe because of the “+”. 

The first request should also work. 

The request doesn’t work in deegree 3.3.20 

Thanks for your help and time in advance.

**Comment by tfr42** [comment]
In case you have a question how to configure deegree please post it to the [deegree-users mailing list](http://www.deegree.org/community/guidelines).
In case you want to report a bug please provide the configuration and indicate the issue you have discovered. 
Please note:
- In deegree 3.3.20 the WFS 2.0 implementation is most likely not complete
- Please verify the requests against 3.4-RC and report the outcome here. Please not that deegree passes the [OGC CITE WFS 2.0 Conformance Test Suite](https://github.com/opengeospatial/ets-wfs20).

**Comment by lgoltz** [comment]
You have to encode the output format, the '+' is not an allowed character. As you can see in the exception deegree tries to handle the output format `application/gml xml; version=3.2` (without '+') which is not supported.
Please try with  `application%2Fgml%2Bxml%3B%20version%3D3.2` instead of application/gml+xml; version=3.2.

**Comment by tfr42** [comment]
Please reopen  in case the issue is not resolved.
