### ISSUE TITLE
Obsolete PHP version website www.deegree.org

### ISSUE THREAD

**Issue by kraaka** [deegree/deegree3#831]
Message form Joomla backend: "We have detected that your server is using PHP 5.4.45-0+deb7u3 which is obsolete and no longer receives official security updates by its developers. The Joomla! Project recommends upgrading your site to PHP 5.6 or later which will receive security updates at least until 2018-12-31. Please ask your host to make PHP 5.6 or a later version the default version for your site. If your host is already PHP 5.6 ready please enable PHP 5.6 on your site's root and 'administrator' directories – typically you can do this yourself through a tool in your hosting control panel, but it's best to ask your host if you are unsure."

**Comment by tfr42** [comment]
Joomla has been disabled and update of PHP is not needed anymore. No usage of PHP in other modules.

**Comment by tfr42** [comment]
PHP module will be disabled in Apache.

**Comment by tfr42** [comment]
PHP is disabled, see https://github.com/deegree/deegree3/wiki/tmc-meeting-minutes-20190426
