### ISSUE TITLE
Support for GeoJSON as output format for WFS (as part of OGC WFS 3.0)

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#849]
WFS shall support GeoJSON as output format. 
`outputFormat=application/geo+json` as specified in RFC 7946, see http://geojson.org for more information.

**Comment by tfr42** [comment]
As part of [OGC Testbed 14](https://portal.opengeospatial.org/files/77327) the work will be continued on the WFS 3.0 spec. WFS3.0: Next Generation OGC RESTful Web service interfaces will accept GeoJSON as a geospatial data interchange format.

This feature will enable GeoJSON as output format. Further enhancements are needed to enable full WFS 3.0 support in deegree Web Feature Service.

References:
- [Testbed-12 REST User Guide](http://docs.opengeospatial.org/guides/16-057r1.html)
- [Testbed-12 REST Architecture Engineering Report](http://docs.opengeospatial.org/per/16-035.html)
- [](https://github.com/opengeospatial/WFS_FES/)

**Comment by nmtoken** [comment]
Down the line, for INSPIRE compliant services support, use of WFS 3 with GeoJSON only will be a problem.  Because GeoJSON only supports one projection system, which is the equivalent of urn:ogc:def:crs:OGC::CRS84 and INSPIRE mandates ETRS89.

**Comment by tfr42** [comment]
In PR https://github.com/deegree/deegree3/pull/941 is the extension for WFS 2.0 already available. Same implementation will be used in OGC API - Features #911.

**Comment by tfr42** [comment]
Support for Json/GeoJson will be available with 3.5 line.

**Comment by tfr42** [comment]
PR #1164 was merged into main for 3.5 line.
