### ISSUE TITLE
Improved support for INSPIRE

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#860]
we have an important request for your next TMC-Meeting: As you know deegree3 is used by many governmental organizations for the implementation of web services according to INSPIRE. The next milestone (aka deadline…) on the INSPIRE roadmap will be the 23/11/2017 and every responsible organization has to provide its interoperable spatial data sets (Annex I) until this date.

In this context many improvements and bugfixes were promoted by LDBV Bayern / LGB Brandenburg in cooperation with known service providers. Unfortunately many organizations are still working with deegree 3.4 RC3 or other versions (it’s a small mess at the moment) and they encounter huge problems which are already solved in the developments we ordered.

For this reason, we strongly recommend to take the following tickets into account and we hope that you’ll integrate these improvements in the new release (or at least into a release candidate):

 * [x] https://github.com/deegree/deegree3/issues/573
 * [x] https://github.com/deegree/deegree3/issues/742
 * [x] https://github.com/deegree/deegree3/issues/713
 * [x] https://github.com/deegree/deegree3/issues/745
 * [x] https://github.com/deegree/deegree3/issues/747
 * [x] https://github.com/deegree/deegree3/issues/781
 * [x] https://github.com/deegree/deegree3/issues/782
 * [x] https://github.com/deegree/deegree3/issues/749
 * [x] https://github.com/deegree/deegree3/issues/827
 * [x] https://github.com/deegree/deegree3/issues/711

We think it would be more effective and easier for INSPIRE users if these developements were available in one merged version. The community would benefit and it would increase the distribution of deegree.

refs: 
- https://sourceforge.net/p/deegree/mailman/message/36081617/
- https://twitter.com/deegree_org/status/922396238724640769

**Comment by tfr42** [comment]
|  Issue |   PR | GA version |
|:------ |:---- |:----------:|
| #573 | | |
| #742 | | |
| #713 | #752, #796 | [3.4-RC4](http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices/3.4-RC4/deegree-webservices-3.4-RC4.war) |
| #745 | | |
| #747 | | |
| #781 | | |
| #782 | | |
| #749 | | |
| #827 | #838 | [3.4-RC4](http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices/3.4-RC4/deegree-webservices-3.4-RC4.war) |
| #711 | | |

**Comment by marcus-mohr** [comment]
I've tested PR #820 - please see: https://github.com/deegree/deegree3/issues/864

**Comment by JuergenWeichand** [comment]
[LDBV] #781 (#834) is successfully fixed in 3.4-RC5.

**Comment by marcus-mohr** [comment]
I can confirm that #747 (#787) now works as expected in 3.4-RC5

**Comment by marcus-mohr** [comment]
#782 (#836) is also "fixed". But the `<soapwms:ExtendedCapabilities>` element ist not disabled by default.

**Comment by marcus-mohr** [comment]
#827 (#838) is fixed!

**Comment by marcus-mohr** [comment]
#573 (837) doesn't seem to be fixed. Now there is another bug which affects the gml output of a getfeature request and there are also problems with filtering at layerstyling.

**Comment by tfr42** [comment]
@marcus-mohr Have you tried to apply the provided information in https://github.com/deegree/deegree3/issues/573#issuecomment-350210473 and following comments to verify the expected behavior?

**Comment by tfr42** [comment]
deegree wegservices 3.4.0 is GA. Please create a new issue in case you encounter an error or problem.
