### ISSUE TITLE
INSPIRE ReferencedType and RESOLVEDEPTH

### ISSUE THREAD

**Issue by DirkThalheim** [deegree/deegree3#862]
INSPIRE uses in some places a ReferencedType to implement relations betweend different FeatureTypes exclusevly via URL. To dynamically generate GetFeatureByID-Requests we're using in the SQLFeatureStore configuration the Feature-mapping. Therefore we're populationg within the database only the href column with values like '#_GML_ID_'.
Unfortunelately the URL is only generated when working with RESOLVEDEPTH/TRAVERSEXLINKDEPTH = 0.

See the net:NetworkReference/net:element/@xlink:href value in following examples:
* http://sg.geodatenzentrum.de/wfs_dlm250_inspire?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAMES=tn-a:AerodromeCategory&COUNT=10&RESOLVEDEPTH=0
* http://sg.geodatenzentrum.de/wfs_dlm250_inspire?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAMES=tn-a:AerodromeCategory&COUNT=10&RESOLVEDEPTH=1

We're using 3.4-RC3 (bayldbvdeegree-1.0.0).

**Comment by tfr42** [comment]
Please verify expected behavior against recent [release candidate version 3.4-RC5](http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices/3.4-RC5/deegree-webservices-3.4-RC5.war) and report your results here.

**Comment by DirkThalheim** [comment]
Still present in deegree 3.4-RC5.

**Comment by JuergenWeichand** [comment]
@DirkThalheim 
If your using `resolvedepth > 0` the response will automatically contain the `wfs:additionalObject` section with the solved reverence targets. Because of this behavior you'll get only local GML-References like `#DLM250_AerodromeNode_DEBKGDL200012BQO`.

**Comment by DirkThalheim** [comment]
Thanks! I didn't see the `wfs:additionalObject` section. I think this closes the issue.
