### ISSUE TITLE
Merge deegree-cli-utility into deegree project

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#873]
As decided during last TMC meeting to overcome the blocking issue for #471 we incorporate the deegree-cli-utility which was initialy created by https://github.com/JuergenWeichand/deegree-cli-utility.
Prepare PR including deegree-cli-utility (https://github.com/lat-lon/deegree-cli-utility/tree/deegree-3.4) with the following changes:
 - [ ] merge into maven module ```deegree-tools-config``` as sub-module of ```deegree-tools```
 - [ ] refactor package name to ```org.deegree.tools.config```
 - [ ] upgrade to 3.4-RC6

**Comment by tfr42** [comment]
@JuergenWeichand Your author tag and header element with copyright is kept!

**Comment by JuergenWeichand** [comment]
+1

**Comment by dstenger** [comment]
Solved by PR #887.
