### ISSUE TITLE
Release new version of deegree maven plugin and integrate into main project

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#903]
- [x] merge pull request https://github.com/deegree/deegree-maven-plugin/pull/7
- [x] release deegree maven plugin
- [x] update main project

**Comment by tfr42** [comment]
Build job has been updated http://buildserver.deegree.org/view/All/job/deegree-maven-plugin/

**Comment by hwbllmnn** [comment]
The Jenkins build should finally be fixed with https://github.com/deegree/deegree-maven-plugin/pull/8 .

**Comment by tfr42** [comment]
Build job updated: http://buildserver.deegree.org/view/misc/job/deegree-maven-plugin/ to call the maven release plugin

**Comment by tfr42** [comment]
Release 2.0.0 is available:
- http://repo.deegree.org/content/repositories/releases/org/deegree/deegree-maven-plugin/2.0.0/

**Comment by tfr42** [comment]
PR for upgrading the plugin:
-  https://github.com/deegree/deegree3/pull/914

**Comment by tfr42** [comment]
travis-ci failed several times for PR #914, see https://travis-ci.org/deegree/deegree3/jobs/406168702

**Comment by tfr42** [comment]
Release 2.0.1 is available:
- http://repo.deegree.org/content/repositories/releases/org/deegree/deegree-maven-plugin/2.0.1/

**Comment by tfr42** [comment]
PR #914 contains the recent plugin version.
