### ISSUE TITLE
WMTS 1.0.0 returns wrong HTTP status code when requesting an non exisiting endpoint

### ISSUE THREAD

**Issue by dstenger** [deegree/deegree3#905]
When OGC CITE test suite [1] is executed with deegree 3.4.0 [2], one test is failing.

Test result: http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0041
One test is failing: Test wmts:Server.KVP.GET.HTTP.Mandatory
This test did not fail with 3.4-RC7 (#882).
Reason of failure: ```Fail:  Server returned 200 instead of expected HTTP status code 404 in response to request http://cite.deegree.org/deegree-webservices-3.4.0/services/wmts100/nonesuch```

**Hints:**
* Also see #900.
* Java version was updated to OpenJDK 1.8 on cite.opengeospatial.org right before executing the test. This fact should be considered during analysis.

[1] http://cite.opengeospatial.org/teamengine/
[2] http://cite.deegree.org/deegree-webservices-3.4.0/services/wmts100?service=WMTS&request=GetCapabilities

**Comment by dstenger** [comment]
## Analysis of test failure

The test is currently failing with deegree 3.4-RC3 (current reference implementation) and deegree 3.4.0.
When Java is set back to version 1.7, the reference implementation is passing the test again.

Thus, the new test failure is related to the update of Java from ```java-7-oracle``` to ```java-8-openjdk-amd64```.

**Comment by dstenger** [comment]
## Problem is solved for cite.opengeospatial.org

Solution is to use ```java-8-oracle``` instead of ```java-8-openjdk-amd64```.
Now, the correct HTTP status code is returned.

**Comment by copierrj** [comment]
Suggestion: try another OpenJDK build such as https://www.azul.com/downloads/zulu/zulu-linux/

**Comment by dstenger** [comment]
Next step:
* Install OpenJDK (no Debian package) [1] on Docker container and rerun test.

[1] http://repos.azulsystems.com/

**Comment by dstenger** [comment]
# Test OpenJDK build of azul

## Create Docker Network

```
docker network create deegree-testing
```

## Install Zulu on Docker Container instance

```
docker run -it --rm --network=deegree-testing --name deegree -p 8081:8080 debian
apt-get update
apt-get install gnupg
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x219BD9C9
echo 'deb http://repos.azulsystems.com/debian stable main' > /etc/apt/sources.list.d/zulu.list
apt-get update
apt-get install zulu-8
```

## Setup deegree on same Docker Container instance

```
apt-get install tomcat8
vim /etc/default/tomcat8
  insert: export JAVA_HOME=/usr/lib/jvm/zulu-8-amd64
service tomcat8 force-reload
apt-get install wget
/var/lib/tomcat8/webapps# wget http://nexus.deegree.org/content/groups/public/org/deegree/deegree-webservices/3.4.0/deegree-webservices-3.4.0.war
  copy and activate CITE workspace
```

deegree is reachable via: http://localhost:8081/deegree-webservices-3.4.0/
And inside the Docker Network: http://deegree:8080/deegree-webservices-3.4.0/
Capabilities are reachable via
* http://localhost:8081/deegree-webservices-3.4.0/services/wmts100?service=WMTS&request=GetCapabilities
* http://deegree:8080/deegree-webservices-3.4.0/services/wmts100?service=WMTS&request=GetCapabilities

## Start WMTS test suite on new Docker Container instance

Following project is used: [teamengine-docker](https://github.com/opengeospatial/teamengine-docker).

```
teamengine-docker/teamengine-ets-wmts10$ mvn clean package docker:build -Dets-wmts10.version=1.0 && docker run -p 8082:8080 --rm --network=deegree-testing opengis/teamengine-ets-wmts10
```

## Execute WMTS tests

Execute test suite against http://deegree:8080/deegree-webservices-3.4.0/services/wmts100?service=WMTS&request=GetCapabilities.

--> All tests are passed successfully.
--> This includes test ```wmts:Server.KVP.GET.HTTP.Mandatory```.

Thus, it can be concluded that the Debian package version of OpenJDK is erroneous. When Zulu OpenJDK is used, all tests are passed.

**Comment by tfr42** [comment]
PR #909 contains updates for the installation section of the handbook with hints to use TCK certified distributions of OpenJDK.
