### ISSUE TITLE
Support latest OGC API - Features (aka WFS 3.0) standard

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#911]
deegree shall support [OGC Web Feature Service 3.0 - Part 1: Core](https://github.com/opengeospatial/WFS_FES/) conformance class. The following requirement classes shall also be supported:

- [x] Support [OpenAPI 3.0](https://github.com/opengeospatial/WFS_FES/blob/master/core/standard/clause_9_oas.adoc)
- [x] [Support for GeoJSON](https://github.com/deegree/deegree3/issues/849) encoding
- [x] Support for HTML encoding
- [x] Support for GML Level 0 and 2 encoding

Encoding as specified in https://github.com/opengeospatial/WFS_FES/blob/master/core/standard/clause_8_encodings.adoc

Remark: The specification title changed to ["OGC API - Features" as of document version 
revision: 2019-05-20, version: 1.0.0-SNAPSHOT](http://docs.opengeospatial.org/DRAFTS/17-069r1.html)!

**Comment by tfr42** [comment]
Currently the following libraries are in favour to be used for Open API 3.0 and REST support:
- https://swagger.io/
- https://jersey.github.io/

See https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5 for more information how to set it up.

**Comment by tfr42** [comment]
Implementation has started. Please stay tuned... we will publish the first prototype soon...

**Comment by tfr42** [comment]
Our first prototype is available at https://oaf.lat-lon.de/deegree-services-oaf/

**Comment by tfr42** [comment]
PR will be provided step-by-step to align the frameworks and deegree API used to implement deegree OGC API - Features.

**Comment by tfr42** [comment]
First PR which needs to be merged into master ist PR #941.

**Comment by tfr42** [comment]
New repo is setup which will contain the implementation for OGC API - Features: https://github.com/deegree/deegree-ogcapi

**Comment by dstenger** [comment]
Further pull requests required for implementation of OGC API Features:
* #1161 
* #1162 
* #1163 
* #1164

**Comment by tfr42** [comment]
The implementation also supports OGC API - Features Part 2 (CRS).

**Comment by tfr42** [comment]
Announcement of the donation to the OSGeo project deegree: https://sourceforge.net/p/deegree/mailman/message/37334202/

**Comment by tfr42** [comment]
PR with the implementation is available: https://github.com/deegree/deegree-ogcapi/pull/1
Build job for building the developer version is configured: https://buildserver.deegree.org/view/deegree-ogcapi/job/deegree-ogcapi-BUILD/

**Comment by tfr42** [comment]
Demo instance: https://oaf.lat-lon.de/deegree-services-oaf/datasets/  
Online documation for demo: https://oaf.lat-lon.de/deegree-services-oaf/documentation/index.html

**Comment by tfr42** [comment]
Support for OGC API Features Part 1 and Part 2 is implemented. Check out the https://github.com/deegree/deegree-ogcapi repo for links to download and document.
