### ISSUE TITLE
Response to 'GetFeature' request for INSPIRE data: "xlink" prefixes are missing relevant namespace

### ISSUE THREAD

**Issue by sMorrone** [deegree/deegree3#920]
I am using deegree to serve INSPIRE data using Memory feature stores. Just downloaded latest deegree stable version 3.4.3, but still struggling with same issue I already had with my previous version (3.3.18) : in the GetFeature response, associations to external object via ‘xlink’ are missing the namespace definition.
Find below description of the issue for the INSPIRE Area Management data set returned by request  https://msdi.data.gov.mt/deegree/services/am_GroundwaterProtectionZones?request=GetFeature&Language=eng&service=WFS&version=2.0.0&count=10&typeNames=am:ManagementRestrictionOrRegulationZone
In the INSPIRE AM schema, the legal document establishing the restrictions in place for the specific area is provided by means of the ‘legalBasis’ element. The GetFeature request should encode the reference to the document as follows
am:legalBasis xmlns:xlink="http://www.w3.org/1999/xlink" 
xlink:href="http://justiceservices.gov.mt/DownloadDocument.aspx?app=lom&amp;itemid=12384&amp;l=1"
 xlink:title="legislationName=Water Policy Framework Regulations LN 345 of 2015 -- LegislationLevel=national" />
Conversely, the GetFeature request returns 
am:legalBasis 
 xlink:href="http://justiceservices.gov.mt/DownloadDocument.aspx?app=lom&amp;itemid=12384&amp;l=1"
xlink:title="legislationName=Water Policy Framework Regulations LN 345 of 2015 -- LegislationLevel=national" />
You can see that the namespace for the xlink prefix is missing and this causes the following validation error in the INSPIRE validator:
"The prefix "xlink" for attribute "xlink:href" associated with an element type "am:legalBasis" is not bound"
Because of this error, the valid INSPIRE physical .gml file becomes invalid when served via the relevant deegree WFS 

To better define the context from the data model point of view, the legalBasis element is an “association”, and its definition in the AM schema is 
element ref="base2:LegislationCitation"
attributeGroup ref="gml:AssociationAttributeGroup"
attributeGroup ref="gml:OwnershipAttributeGroup"

On a side note: the “xlink" for the “gml:ReferenceType” elements in the schema- like the code lists -works fine (i.e. namespace is provided) and likewise for the internal references via ’#’.

Could you help? 
I am using Windows 10 - apache-tomcat-7.0.73 - jdk1.8.0_74.
Thank you
Stefania

**Comment by tfr42** [comment]
Please post the deegree workspace configuration and don't forget to send an email to the degree-users mailing list (see <https://www.deegree.org/community> for further information).

**Comment by tfr42** [comment]
Without the complete deegree workspace it is hard to tell what causes the problem.

In case you have further questions how to configure deegree please post it to the [deegree-users mailing list](http://www.deegree.org/community/guidelines) or use https://gis.stackexchange.com/questions/tagged/deegree.
