### ISSUE TITLE
no outputformat in getcapabilities getfeature operation

### ISSUE THREAD

**Issue by pvgenuchten** [deegree/deegree3#925]
Hi team, this may be an old deegree server, so it may not be relevant on the current threads, just wanted to verify an issue i have.

This came up related to this PR https://github.com/geonetwork/core-geonetwork/pull/3026

this WFS service http://services.inspire-provincies.nl/ProductionAndIndustrialFacilities/services/download_PF?request=getcapabilities&service=WFS does not advertise any outputformats for the getfeature operation

I checked [(some version of) the specs](http://www.isotc211.org/protdoc/211n2632) and noticed indeed that this parameter is optional, the standard suggests then a default value of 'text/xml; subtype=gml/3.2'

However this server does not accept this outputformat, it expects 'text/xml; subtype=gml/3.2.1'

This maybe related to the fact that I don't have the latest WFS 2 spec, or some misconfiguration? At least I would recommend to always advertise the outputformats in capabilities to prevent this type of issues. Looking forward to hear your thoughts.

**Comment by tfr42** [comment]
Without the configuration of that deegree web service it is hard to say what causes the problem.
You may check the deegree workspace for the WFS configuration file and if the following is applied:
```xml
<GMLFormat gmlVersion="GML_32">
    <MimeType>text/xml; subtype=gml/3.2.1</MimeType>
    <GetFeatureResponse>
      <DisableStreaming>true</DisableStreaming>
    </GetFeatureResponse>
  </GMLFormat>
```
See chapter ["5.1.7. Adapting GML output formats"](http://download.deegree.org/documentation/3.4.3/html/webservices.html?highlight=adapting#adapting-gml-output-formats) for further information.

**Comment by tfr42** [comment]
In case you have further questions how to configure deegree please post it to the [deegree-users mailing list](http://www.deegree.org/community/guidelines) or use https://gis.stackexchange.com/questions/tagged/deegree.
