### ISSUE TITLE
Error memory feature store: "Parsing of 'gml:RectifiedGrid' elements is not supported".

### ISSUE THREAD

**Issue by fabiovinci** [deegree/deegree3#927]
I am using deegree to serve INSPIRE data using Memory feature stores. The INSPIRE gml file is compliant to the ElevationGridCoverage xsd schema (http://inspire.ec.europa.eu/schemas/el-cov/4.0/ElevationGridCoverage.xsd). The gml contains the element gml:RectifiedGrid and when I try to setup a memory feature store I receive the following error message: 

_•	Error in feature store configuration file 'file:/C:/Users/Administrator/.deegree/14.06.2018.deegree-workspace-MSDI/datasources/feature/inspire_el_DSM.xml': Error setting up feature store from configuration: 'Error in XML document (file 'file:/C:/Users/Administrator/.deegree/14.06.2018.deegree-workspace-MSDI/data/EL/EL.ElevationGridCoverage.DSM_4258.gml', line: 27, column: 17, character offset: 1714): Parsing of 'gml:RectifiedGrid' elements is not supported.'._

Do you have any idea how to overcome the error? 

Thank you,
Fabio

**Comment by tfr42** [comment]
Can you please post the deegree version you are using and the complete workspace if possible?
And a message to the users mailing list too.

**Comment by tfr42** [comment]
In case you have a question how to configure deegree please post it to the [deegree-users mailing list](http://www.deegree.org/community/guidelines) or use https://gis.stackexchange.com/questions/tagged/deegree.

**Comment by JohannaOtt** [comment]
@fabiovinci Is there a solution/answer to this issue. Did you overcome it somehow? We are currently running into the same problem.
