### ISSUE TITLE
Security issue: Local file inclusion in deegree3 console

### ISSUE THREAD

**Issue by olis84** [deegree/deegree3#942]
deegree3 console allows via ./console/client/download.jsp to an unauthorized user to download files from server. The file name isn't validated sufficiently, so hackers are able to get local files. It's also possible to download the password from the interface of deegree3 console. 
It would be recommended to validate the user's input. Values like '../' should be filtered to prevent access to higher-level folders. During a penetration test, it was possible to access /etc/passwd an other sensible files on host.

**Comment by tfr42** [comment]
Thanks for your investigation. Please have a look on our [guidelines](https://github.com/deegree/deegree3/wiki/Bug-Report-writing-Guidelines#reporting-a-security-vulnerability) for future posting.

**Comment by tfr42** [comment]
There is a SNAPSHOT version available including a fix ready for testing:
- WAR file: http://buildserver.deegree.org/view/misc/job/deegree-3.4-PR955/ws/deegree-services/deegree-webservices/target/deegree-webservices-3.4.4-SNAPSHOT.war
    - download and then just deploy it manually to your preferred web container
- deegree bundled with Tomcat: 
http://buildserver.deegree.org/view/misc/job/deegree-3.4-PR955/ws/deegree-services/deegree-webservices-tomcat-bundle/target/deegree-webservices-tomcat-bundle-3.4.4-SNAPSHOT-distribution.zip
    - download and then run the following commands:
```
unzip deegree-webservices-tomcat-bundle-3.4.4-SNAPSHOT-distribution.zip 
cd deegree-webservices-tomcat-bundle-3.4.4-SNAPSHOT/apache-tomcat-8.0.50/bin/
chmod a+x *.sh
./startup.sh
```
- Docker Image: https://cloud.docker.com/repository/docker/tfr42/deegree/general
```
docker pull tfr42/deegree:3.4.4-SNAPSHOT
docker run -p 8080:8080 --name deegree --rm tfr42/deegree:3.4.4-SNAPSHOT
```

**Comment by tfr42** [comment]
Official version 3.4.4 available including the bug fix. Download from http://www.deegree.org/Download
