### ISSUE TITLE
Security issue: Missing input validation for upload via console

### ISSUE THREAD

**Issue by olis84** [deegree/deegree3#943]
Uploading new ZIP-workspaces via the console (./config/upload) is a helpful feature, but there is no input validation of the upload path. The ZIP file will be unzipped after upload directly to the upload path. 
It would be recommended to validate the user's input. Values like '../' should be filtered to prevent access to higher-level folders. During a penetration test, it was possible to upload files to the /tmp folder.
See also https://www.owasp.org/index.php/File_System#Path_traversal

**Comment by tfr42** [comment]
Thanks for your investigation. Please have a look on our [guidelines for reporting security vulnerabilities](https://github.com/deegree/deegree3/wiki/Bug-Report-writing-Guidelines#reporting-a-security-vulnerability) for future posting.

**Comment by tfr42** [comment]
Please check https://github.com/deegree/deegree3/issues/942#issuecomment-464137034 for further information providing a fix for the reported issue.

**Comment by tfr42** [comment]
Official version 3.4.4 available including the bug fix. Download from http://www.deegree.org/Download
