### ISSUE TITLE
 WMS&WFS Can support data filtering, similar to CSQL in GeoServer 

### ISSUE THREAD

**Issue by zhhang920** [deegree/deegree3#944]
geoserver ECQL Reference
https://docs.geoserver.org/latest/en/user/filter/ecql_reference.html

**Comment by tfr42** [comment]
deegree WMS and WFS implementation supports OGC compliant KVP, XML and SOAP requests and for WFS filter encoding (see http://download.deegree.org/documentation/3.4.3/html/intro.html). No support for ECQL. Use Filter Encoding instead (see http://download.deegree.org/documentation/3.4.3/html/filterencoding.html)
