### ISSUE TITLE
WPS 2.0?

### ISSUE THREAD

**Issue by awst-baum** [deegree/deegree3#946]
Hi!

May I ask what the dev team's plans regarding WPS 2.0 implementation are, roughly? Something like "Not on the radar", "Planned for the far future", "Planned to happen within the next 2 years", or something completely different? (I'm mainly interested in the WPS client side.)

**Comment by tfr42** [comment]
Currently no plans to support WPS 2.0. Either it requires volunteer work from the community or a (financial) contribution. The OSGeo project https://www.osgeo.org/projects/pywps/ provides an implementation.

**Comment by tfr42** [comment]
In case of funding is available or voluntary contributions please re-open the issue and label this issue as feature request.
