### ISSUE TITLE
proxy settings

### ISSUE THREAD

**Issue by DrYSG** [deegree/deegree3#947]
I am successfully running deegree 3.4.3 in 
Apache Tomcat/9.0.14 on windows 10.

However, the imports are not working. It is unclear what I should be doing to setup the proxy info. I run a localhost proxy which sets up all the information for the corporate host. Applications that look for http_proxy environment variable can use: http://localhost:3128  (There is a local service at port 3128 that adds all the credentials and forwards http/s requests to the company proxy).

Here is what the default is, but using that will allow me to connect to repo.deegree.org
```
  <ProxyHost>http://proxy.deegree.org</ProxyHost>
  <ProxyPort>8000</ProxyPort>
  <ProxyUser>deegree</ProxyUser>
  <ProxyPassword>pwd</ProxyPassword>
  <NonProxyHosts>127.0.0.1|localhost</NonProxyHosts>
```

I have tried techniques that usually work for other programs here: 

```
  <ProxyHost>http://localhost</ProxyHost>
  <ProxyPort>3128</ProxyPort>
  <ProxyUser></ProxyUser>
  <ProxyPassword></ProxyPassword>
  <NonProxyHosts>127.0.0.1|localhost</NonProxyHosts>
```

But in this case, I get an immediate error about not being able to connect to the localhost

**Comment by tfr42** [comment]
The configuration looks a little bit awkward. The proxy host is localhost and it is also a non-proxy host. 
 
In general we do recommend for asking questions to post them to https://gis.stackexchange.com/questions/tagged/deegree 

In case you have a question how to configure deegree please also post it to the [deegree-users mailing list](http://www.deegree.org/community/guidelines).

**Comment by tfr42** [comment]
Similar issue has been reported when using deegree workspace configuration which imports external XSD resources running on JDK 8.
