### ISSUE TITLE
Workspace startup failed: GC overhead limit exceeded(class java.lang.OutOfMemoryError)

### ISSUE THREAD

**Issue by DrYSG** [deegree/deegree3#948]
All the example workspaces are working for me except the INSPIRE.

I get the following error when starting it:

Workspace startup failed: GC overhead limit exceeded(class java.lang.OutOfMemoryError)

I have an 8 core 32GB computer, and I am running:

* Java 1.8.0_191-b12 in 64 bit mode
* Tomcat 9.0.14
* deegree 3.4.3 
* windows 10

I am using Chrome to view the workspace.

**Comment by tfr42** [comment]
In case you have a question how to configure deegree please post it to the [deegree-users mailing list](http://www.deegree.org/community/guidelines) or use https://gis.stackexchange.com/questions/tagged/deegree.

Check if the JVM running Tomcat has enough memory. Check the JVM `-Xms` and `-Xmx` settings.

For example use `JAVA_OPTS="-Xms128m -Xmx1024m"` (starting with 128 MB and max 1GB).
