### ISSUE TITLE
deegree CLI does not work for schema OF (Annex III)

### ISSUE THREAD

**Issue by gannebamm** [deegree/deegree3#961]
This tool:
https://github.com/deegree/deegree3/tree/master/deegree-tools/deegree-tools-config

is unable to create output for:
`java -jar deegree-cli-utility-1.2-jar-with-dependencies.jar --srid=25832 --format=ddl --idtype=uuid http://inspire.ec.europa.eu/schemas/of/4.0/OceanFeatures.xsd`

The sql is empty

**Comment by stempler** [comment]
Hi @gannebamm,

the problem here lies with the schema and not the tool.
The OceanFeatures schema defines no feature types of its own and only imports the INSPIRE base types which are not really relevant.

I understand the data specification that ocean features should be represented as Observations, and thus the schema should at least import the [Observations and Measurements schema](http://schemas.opengis.net/om/2.0/observation.xsd), though there are more schemas in INSPIRE that related to observations and might have to be imported:

- [INSPIRE Application Schema Observable Properties](http://inspire.ec.europa.eu/schemas/omop/3.0/ObservableProperties.xsd)
- [INSPIRE Application Schema Specialised Observations](http://inspire.ec.europa.eu/schemas/omso/3.0/SpecialisedObservations.xsd)
- [INSPIRE Application Schema Processes](http://inspire.ec.europa.eu/schemas/ompr/3.0/Processes.xsd)

**Comment by gannebamm** [comment]
Hi @stempler ,
Yes, this is correct. OF is an aglomeration of different schemas. I made a simplified diagram for myself to show these relationships:
[draw.io Diagram](https://www.draw.io/?lightbox=1&highlight=0000ff&layers=1&nav=1&title=INSPIRE_OF.html#R7V1bc9u2Ev41nkkf6uFd0qPtRDmdiWtPnPT0PHUgEhLZUASHpGyrv%2F5gQUC8gJCpmBe5pp1xRIgEAeyHy367WFyYN9vnzwmK%2FVvi4fDC0LznC%2FPjhWHo5sKi%2F0HKPk%2BZOTxhkwQev6lIeAj%2BwTxR46m7wMNp5caMkDAL4mqiS6IIu1klDSUJearetiZh9a0x2mAp4cFFoZz638DLfJ7q2FbxxX9wsPHFq3VnkX%2BzReJuXpXURx55KiWZny7Mm4SQLP%2B0fb7BIbSeaJj8uaXi20PJEhxlbR4wNAe5q%2FnCWNmr9cL71ZrzcmV7UVvs0crzS5JkPtmQCIWfitTrhOwiD0OOGr3ys21IP%2Br0I34Osj9Ln%2F8Ht1za9OpvnGV7Llm0ywhNKvL%2BQkjMn1qTKOO36Rq%2FviEhSVjZTOsj%2FNL0NENJdgWypV94AdqSyBPJyyAMedloqyT7P8sXRZHkpuOtmZJd4mJFe804%2FlCywZniHi58aMhSxlwgnzHZYloQekOCQ5QFj1WUIQ7WzeE%2B%2FiitLdqXbohJEGVpKed7SKA38H7nzBe0nixP0e%2BMRRUcLz%2FBu67qCUt%2F%2FROGZpafoB%2FymoqrUpMVSQzW7SCuzzqF%2BBFEjQTynwJyCxyfCYwXdcBYunEcxvITsxdAabz%2BCdvuF8aiYR9RuONNLeF6Q2EbK%2BHwiJMMP1eS%2BIyJViIH7aJRxKLWllRrnc%2BBT8XEaJl5S2h%2BaU48TOZNwCg12kltMpea5FP0GCQk2tK6o%2FCWREFGkiDaXLkUoEG2l1osfQq2IYqw6JX8G%2Bilrh%2BE3he0JzuoAu107g9xde3TXP8h8A5%2BM%2BuTvE8bDuRG%2B2epT3sIz9du5ckHyJF34QSn9Nl7ITO9lnSLnis3fkFpxhNcEoYoToPVodxb2qWD6JpkGdnym0Qtl9VCrdkPK31CfuDSN447x6t149iixGUdXTKKShg5LIgqGHF6wMiiodtc8%2Fuv6P8PGQBEAgatSya1TERypJSakSehMNhE9DLEa3gMGiOgC8grnpzB2H%2Bdxsil7%2FrC7vloFSlfeRtAEqHPrkM25PuB5%2BGIzUYZEp0U5MnHTFpQ%2B5r%2Bo612AzOQTQt%2BQ6%2F14tr%2ByG5P6PwS0bqggIkRU%2Fw8YcBQCwHPW8tXTOiONCQoxN29tPnUIIs7Qls8CbwfgdvGiALXFAJHfMj%2FFgjBX62gQdwMUu5Wf4OmOIGgMxDM5iOCoGltBCDwcOomQZwFJJo6fz9y1zV5BTic4FWz%2ByrX3673udjpshCHJMaT4DsUvKmNJ3jTUgg%2Bxdn3eAkyA7lfwLvN5yvaAgrN4D4hmwRttxM0uoSG3XIJaFndQ0NQdBI0dimQyOWVQAGDJUbZLplA0KUaoLUcH8wOtD5rbeiW7lhrS0PGzDR%2BNRUguLy8bCdk0ILZj6zMr234fcvifvKDDD%2FQYkDeTwmKZRYy%2F%2BkJGm2nji6gIa0Z7AZoOGgLbRDmfaF6pd2QJMFpTCIvBcqUQIGgSXASEA9Wmbt8UanRZnV9uMXH%2BaKjacZZUuGHjIvSfAQZrjAVNx2eYsg3ggyTXRTRO5VILfHRnY5MTbCoMuFlksw4hcqWOsHLsDqBWXquYaiMK72JjdR6AJYgZM%2BLodWdtgxtH5OxrJi92CsmhrZrhtZQoOt0htbso99YE0X7yrVZ%2B4HyDChaFUO7pVWmS3AYGOjVV7w5EHcu8fCXIJ3oug4RMCZnq1qbb8kqCLnMrwkJMYomkXcn8jEZWhVdM5ll%2BpP3qMxsk5KVj%2FJegPiyD3vT%2BN6b8MdkZx2F8HMtmi2F6bI54%2BT8V%2FAfwl6eMkGgOwi0ZWF7WeWp7LI%2BSu9WKU4eUWGVu7v9q5T2If3l3cKgiYHpAxrzlsu%2FPjgBFT9PYpwwAFBBceP9fU6x5SBRff1t%2F44NewMBprXG2AVgJDJfZd6fyPzuyfzToTEbk8xvWmocJfNhKKFvTvAa00ZwMfDthHsDaV6Q0A%2Fhni1Kw5B%2Bzol92o601RLi4jTNUzwqTajLCuhGkQOw%2BU8%2BSXF%2BdwwQwpD4AV8Cm6%2FF%2Fj4FUIGQ6St8vC2uVgGV1ya%2Fzl9IMh8nrMFinjlZ0z%2B4zKCykkZeAAMjzJsaAismXWnFGBZVrCqEza15TWl%2BDmuKFXzawCdOvHhQwKuo4QXbA0tLL9aF%2BcIF%2FVxDYQoWEVrtrFTmNnnQtnnvJo721OzJJg6rDxNHE3XTaOIwrz2U%2BqxR9cam6MzksZB2lOiztiYPo482krmO6vpWarGhTBzrNXbct2Pi8GaLlabVkQQX9yjLcBKxFEODVAKdDxTKj7PmLTFKJJ9mFLEa1ad5DyhSESiTUYQtemqj8FyD33aSt1pL%2Foi1pBkIPeBAxaVMzOkISGiymgyGBHm30%2BTkPDYgmmwqQwHCVKnF69yZ8W79W0SnSdYoAIullDwhpH%2BENFphBoOIytTKdFkPPF4FAXufa7cTJobARJNxZihM2CpmPvZxRLOngpz2TI0NkCbTzWAAUc0rgke6z6ktbr77vPxLJLxrJn5QfDTZbxrx0YNqKhbBTebdXZhNqBhNT9XbTisdoEIy0qgIi8lIc6qRpsJ3nc5snY4bs6UW04cFx2xajhy14HzGEU4C9zAhcVIVbCjC%2BMJHIvpWsJqg6OgY9E5MDe0Jz%2BcaBEqwOKxcy7DQ533goon4ajQ19GdasIX%2BxDvKXLiqjxLtxpQdJ07e1DrtplgX%2FUfcXelNduO81H63xQG3rzcs6PM%2BKAEVjTgZFlo64h364ZswIJiq3TWTAaFHiY9pKLBUBE%2BINyi8pqPwhi1DcuF%2FqSVOKOgOBWNaBywVi3PIvELwfS6%2FcpJ%2FN%2FIflfu3VDQNicIgwl%2BxCA8KMPATvJ5E36Xoh6T4JS5GJfqJizmVi%2BkFG23Z%2FT74FqtpK95RvmVJVUn8RJIf9PMKpbkfKXh%2BxiQMXB4BGD8itm%2FXI%2B4O1FHgXTy8DqLc4zOPiMGjDXM%2FVnRReNmy%2FFhqidPJuRv6uiVzh83z8HAckj3fJcyeUEbzSUVB8yfXAQ7BybXu%2F%2Fo93aGQOcoyf9ZPNc%2FV27Lnakmz5tE7oBYhySuJk%2B0FiwvCHHYhJDItwGPuw5uxBRhiTrLwzBo%2FASIwSt67E%2BwJGvMxZmoxVJwPy5bk1UvM%2FH9LqHERq%2B1YrHHBSowcbHwm%2BRI7C6OMlRZPzI0XQodL4cl%2F4on5vIbgboONW84E8VMgLvzIj0FcePSODPG5dMiD6cyPwk9%2BQmw46At%2BzhnAryVcukbpz42w5svws88Dfro%2Bk%2FDHT%2BhQ4a%2FhEcMxOgWgpEDJxqerOKarXbYufYCNW0h2lRtsH4fQwM7TuKJWJFvrWCdHfuPzYQGpBuJFHNdUMbEIhkYJ8O3zV7AYRpsQlyApnOj4%2B36VFTp91kLZRyHsY0EZvobBK5VWpa9Esd5gMVweIiKrtZzlYX%2BehHElWyAsZCpD4JtlC6pdWYKqcuh4lXWoCau9MEW6bA68u%2BVOwVVN%2FMALAFqKWF3tIXLYz6XaljZB5BRz0nAQkS2Id3wUuXMxioARiX3mkENLzi%2FYoFLwMC0hMjdWZhPn6Nl47lkTRE60NQ0GEVMmnNPdKs2CbJcxvnC1l3m3hxi7ARXoP9g7ujvWRzF8DIPoR3Vh33btLRQAvugXKgAQYbyxdHt2qdnzuWHaxsKiC85ZTWTmEUyqUZx%2FI86MlFz75K2sRkUpubS1w5FzUGL9UnNmIgFin1DB4YRXJUQrXLLj1mjBVmqFbEbQZb1C5ff5ol5RAqbdsDQSaaepH7KyoGnSkYT1mCR5nfmDxxQPTSJ3rHktr7xppLx%2BRglGjm657gKtZmu8cO2Gk6vwM52BQ9mrq2fluLgU%2FeYUrbfUMZbLxeL4ir%2Bi5dYbxGmBRmGNGV3NXVQ1BMc%2BziNKD8xeOIFQ152jD7yelKk3vz6xMqfhVW8YPs%2BVlrEkjqXGMbd55KVTMynIO3jkKPkjZzCTD600jJ%2BcEObS5GI5s94mhDpUGgOLqPZtTkFFjgcVUXbp9qSTbsiHGQs3%2BxfdPsw%2BdmZNQUNe6ehz6GNvwrfXbtojMfn29izxMX17bVXwzAw2OE0S70fig%2FrxSqtISeKfk8B7oOo%2FTo%2FxJu9F4BVK5TgLUlvea%2Bzn4if2WJ4OoVFdgW1l6CDurVeKxfyRJ90E2fvGVS8oGDPwhyPrD1NY9jFAMGZwD0elIvDotlTciNPKAIL7euoEhA6B0DqKRx82G9VoMO0RgJJ2u0fgJ9RKbciYDNKas0nNqGGi7833umZKlpyFLTVK8%2F77RR9h6Bs24NPxkUIfn0N034M98m0QcQcjaUPvUcLx9XvqTaMPZCj32oXELa2tp6BIqslU3de6J%2BL6CH7UuKtqCs46kOjtIXVrlZVvirF5ajC0A%2F%2FSCyjmA6ra8nigUrNWuT38en9ww8UhmaaCbkWvawNq2LLsVVaZKX7m2QwOuvBYHCSApjRlqCK0TJG7zwokzpBsrQQSlU4xhVkdGxfzAVUNGReqmO45LorY3RM2RsCG0bTzbDhsqNTQKbb7GUFEsEXjTCtKA1DV8vM7vfD%2BYDdNqBgCFc6oTiYqD4HJGvR6a1AX6Fi0nFa6MAfJ5W1Cx4unrNZsI9w6IkJyX1Q2mLLlS0xXMLTRGD3K84tWKd9ymsdw2hYbTy9KYaRioVHTSx6MCfH25VsRYyiMC1kE8LKUyZKHZYJb4VhXtsM7C7b5XWmGogzORM2jTx323rDbb759FJmGRbny3dMphXmUlyU%2FU3bNjppln3Gc%2BakoRF4lAnso31sIqFdYeE6NAaXrl9qi%2FNtDBzFkDljsbkwruxvH89N%2Fq%2BbB6h5KAOKL3nonO%2FLLR8ha89Z%2B%2FH3YEx2ZIAKnz8ndcxh3T3X%2FPs9tAfXRVGaObndhFrBNSdVJd4LRecNo0L0GdRjJRJPYDzcNRG8GQaPuXZDpqPoYdFMKADsB6ZyBNOwOhjqSZNaKIQm4y4atMNO8du5gGnQjhCKQxGl%2BnBOCXkLQIbxHDUFlvVbrB06Dbqmow0l2C4Zh6Qt3%2FeQcuvYtCZpit0ywOq%2BBacg9GRKSZJ71W4LAMkeS%2FTQ2vRkQtd680c%2FhH00nfh1l65VcpbZOyPbAVKMiBC7Aj0XBvTghCKD24W75iwq7%2F06i%2B%2FSYIrrdhotsZLrFwd2vQZO9MPECuSsdL9bYnbkN289FJD9fF5H8bikyctsHqWEh3SWPGKrn0SEBgETon99%2Bf7j%2F7esngM6yBKR6fECRQotcvEokxiLhG4OmvH5jVqYEl9BdjzOoocMhJYcYhbREYPKhmbJzZBvzg0CE7AFWGajVHzhNMbTihwc%2FiH8BUdHq%2Bxfc2JXvAVgVL8m70yeovOIETx6Bd1%2FuZ48BOjwbsHNEfFRTe1CW0RftMgyV%2BIRYESqH5Gp0yCTRJi2XHg4rCdZMXG6yC1jFRfmfAoaOFa5VI%2FNpH9r4RV2aq3EFp6CUq8Eb94IfRsdGmOJ0mTWztMV0SiHJNgcURDLxlAJ2yS70RPkOcmFt%2FEKJ4OkUZ9%2Fj3Lp3JRqO58NPrWFNJB0K03jQqnYUwHGR1tnwV5xiahdX31hsMziQoHnoa56w68NhO6%2BHkwc3MQWKKN3yLGk2hYY0%2BBkcpwxs9DIhJCsH34JB6ZZ4GO74Pw%3D%3D)

How to get those loaded?

**Comment by stempler** [comment]
My suggestion would be downloading the OF schema file and adding the missing imports to the schema (for each schema to import you need to provide its namespace and location, similar to the import that is already in there). Then try the local, fixed version of the schema with deegree CLI.

You could check if someone else had this issue in the INSPIRE Thematic Cluster. If so, maybe they provided an adapted schema there already. If not you could raise the problem there so at some point we might get a fixed official schema.

**Comment by tfr42** [comment]
@gannebamm Can we close this issue? I consider this as an question which has been answered. Please use the mailing list for questions and discussion.

Please have a look on our https://github.com/deegree/deegree3/wiki/Bug-Report-writing-Guidelines and https://github.com/deegree/deegree3/wiki/Community-Support-Guidelines for further information.

**Comment by gannebamm** [comment]
I haven´t tried the above mentioned suggestion but nonetheless understood the issue - which is not related to deegree.
Therefore it can be closed. Thanks for the insights.
