### ISSUE TITLE
Replace Website with github pages

### ISSUE THREAD

**Issue by stephanr** [deegree/deegree3#967]
The following activities have to be done to replace the old website with github pages:
(Aggreated from the TMC meeting https://github.com/deegree/deegree3/wiki/tmc-meeting-minutes-20190329)

- content releated tasks
  - [x] fill or remove the placeholder text
    - [x] use first paragraph of startpage for About this site
  - [x] final enhancements in layout and colour
  - [x] remove rss and atom links (~~including the backend functions~~)
  - [x] hide sitemap.xml link in the footer
  - [x] migrating blog entries to wiki or web page
  - [x] add https://gis.stackexchange.com/questions/tagged/deegree
  - [x] add gisoverflow to website links
  - [x] add remark to README.md regaring local development
  - [x] re-enable analytics 

- administrative tasks
  - [x] transfern website repository to deegree organisation on github (from http://github.com/stephanr/deegree-website/)
  - [x] Prepare use of deegree.org domain name: https://help.github.com/en/articles/using-a-custom-domain-with-github-pages
  - [x] open an issue in OSGeo SAC trac to change the DNS entry (Trac to OSGeo SAC - https://trac.osgeo.org/osgeo)
- post migration tasks
  - [ ] review issue #482 
  - [ ] review if analytics  are working correctly
  - [x] disable joomla
  - [x] correct dehydrated / letsencrypt list of domains handled on plaza (/etc/dehydrated/domains.txt on plaza)
  - [ ] check if the "fork me on github bage" can be restored

After processing this issue, the following issues are no longer relevant:
- #515 
- #493
- #831

The previous evaluation was done in Issue #906

**Comment by stephanr** [comment]
I replaced the master branch on https://github.com/deegree/deegree.github.io with the squashed version of the prepared jekyll based one.

This version is now available at http://deegree.github.io/.

I've also prepared the use of www.deegree.org / deegree.org via the Github page settings, so we can trigger the DNS changes tomorrow if there are no new change requests to the page in the TMC meeting tomorrow.

**Comment by stephanr** [comment]
To test the website, you must access it via http until the DNS is updated.
It is also necessary to add the following entry to the local hosts file:

```
# deegree.org testing
185.199.109.153 deegree.github.io www.deegree.org deegree.org
```

**Comment by stephanr** [comment]
The required changes would be:
```
@                        IN CNAME          deegree.github.io.
www                      IN CNAME          deegree.github.io.
```

**Comment by tfr42** [comment]
Issue for OSGeo SAC created https://trac.osgeo.org/osgeo/ticket/2272

**Comment by stephanr** [comment]
The DNS change took place on the weekend, so the website address had to be changed in the configuration to avoid HTTPS warnings.

This was done in commit https://github.com/deegree/deegree.github.io/commit/4b76d0fc0b2badff58ce701ecc54ab26f1634a8d.

**Comment by stephanr** [comment]
I reopended the sac issue at https://trac.osgeo.org/osgeo/ticket/2272#comment:5 as it looks like other entries have been changed.

**Comment by stephanr** [comment]
Due to the dns problems we have decided to continue redirecting from deegree. org to www.deegree.org via plaza. (https://trac.osgeo.org/osgeo/ticket/2272#comment:12)

I also disabled the jommla site on plaza.

**Comment by stephanr** [comment]
In today's TMC Metting from 24.05. we agreed to continue the still open items as separate issues, accordingly this issue will be closed.
