### ISSUE TITLE
GetFeatureInfo does not work; postgis extension in another db scheme

### ISSUE THREAD

**Issue by MaChriSchmi** [deegree/deegree3#968]
Deegree Vers. 3.4.5

Hello,

I installed the postgis extension on an own scheme(postgis) on my Postgresql DB.
The  search_path variable includ the postgis and public scheme.
The FeatureStore points on an db view on his source.
Now I have the problem that the GetFeatureInfo request does not work.

catalina.out
`WARN: [FeatureLayerData] Data could not be fetched from the feature store. The error was 'Error performing query by operator filter: FEHLER: Operation on mixed SRID geometries'.`

postgresql-9.6-main.log
`2019-04-03 09:44:10.778 CEST [3124] *****@***** FEHLER:  Operation on mixed SRID geometries`

`2019-04-03_ 09:44:10.778 CEST [3124] *****@***** ANWEISUNG:  SELECT X1.attr_gml_id,ST_AsEWKB(X1.ps_geometry_value),X1.ps_designationscheme,X1.ps_designation,X1.ps_siteprotectionclassification FROM gdz.v_ps_protectedsites_default X1 WHERE (( (X1.ps_geometry_value && ST_SetSRID(ST_GeomFromWKB($1),0) AND ST_Intersects(X1.ps_geometry_value,ST_SetSRID(ST_GeomFromWKB($2),0))) AND X1.ps_siteprotectionclassification = $3) AND ST_Intersects(X1.ps_geometry_value,ST_SetSRID(ST_GeomFromWKB($4),0)))`

`2019-04-03 09:44:10.779 CEST [3124] *****@***** FEHLER:  aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert`

When I reload the workspace, I receive the following lines on the postgresql log.

`2019-04-03 09:49:15.506 CEST [29063] *****@***** ANWEISUNG:  SELECT coord_dimension,srid,type FROM public.geometry_columns WHERE f_table_schema='gdz' AND f_table_name='v_ps_protectedsites_default' AND f_geometry_column='ps_geometry_value'
`
`2019-04-03 09:49:21.487 CEST [29063] *****@***** FEHLER:  Relation »public.geometry_columns« existiert nicht bei Zeichen 39
`
I found the following file on the repository.

[PostGISDialect.java](https://github.com/deegree/deegree3/blob/51cdd20dd335715e045c89dd351b668e112edec2/deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/src/main/java/org/deegree/sqldialect/postgis/PostGISDialect.java)

You can see in the file, that the select statement of the geometryMetadata methode supposed the geometry in the public scheme.
I could not find in the documentation of the project, that the extension must be installed on the public scheme of the db 

When the FeatureStoreXml was created with the command line utility 'deegree-cli-utility', then works the GetFeatureInfo request although the extension was installed on the postgis scheme.

Did I make an fault on configuration?

with kind regards

Manuel

---

Feature Store  view [INSPIRE_ProtectedSites_WMS.xml](https://gist.github.com/MaChriSchmi/d6061716e6b9375dad5c9b2cb55853ff)
Feature Store [INSPIRE_ProtectedSites](https://gist.github.com/MaChriSchmi/3cd975ec2a7ed76d4c1cb8b5827b8ea1)

**Comment by tfr42** [comment]
Please note that for community support we recommend to use the mailing list or https://gis.stackexchange.com/questions/tagged/deegree. See more information about community support in our http://www.deegree.org/community/guidelines/.

For bug reports please read https://github.com/deegree/deegree3/wiki/Bug-Report-writing-Guidelines.

**Comment by tfr42** [comment]
In the future please ask questions on the mailing list or GIS stackexchange. As mentioned in the [guidelines for contributing](https://github.com/deegree/deegree3/blob/master/CONTRIB.md#getting-in-contact), we prefer to use GitHub issues only for [bugs and enhancements](https://github.com/deegree/deegree3/wiki/Bug-or-Feature).
Please read further in our [community support guideline](https://github.com/deegree/deegree3/wiki/Community-Support-Guidelines).
