### ISSUE TITLE
Package and upload GML schema file to deegree repository

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#975]
Re-enable the module https://github.com/deegree/deegree3/blob/master/uncoupled/deegree-ogcschemas/pom.xml
and add a Jenkins job to run this with every release build

**Comment by MrSnyder** [comment]
I just tried to build the mentioned module and found that it was quite easy to get it going again (I just had to change the version and adapt the deegree parent version).

**Comment by MrSnyder** [comment]
Do I understand correctly that you want the ogcschemas JAR to follow normal deegree version semantics (e.g. 3.4.6)? And you do not intend to build the JAR for SNAPSHOT versions (we probably shouldn't, as the build downloads ~40M every time)?

If so, how do we best deal with the missing dependency when building a SNAPSHOT (e.g. by a developer or by the GitHub CI)?

**Comment by tfr42** [comment]
From todays TMC meeting:
We will create a new project https://github.com/deegree/ogc-schemas
Then move the https://github.com/deegree/deegree3/blob/master/uncoupled/deegree-ogcschemas/pom.xml to this repo.
And add a jenkins build job http://buildserver.deegree.org/job/ to create it manual.

**Comment by tfr42** [comment]
Repo created

- [ ] Repo created: https://github.com/deegree/ogc-schemas

- [ ] Build job created: http://buildserver.deegree.org/view/misc/job/upload-ogc-schema/

- [ ] Maven Pom moved: https://github.com/deegree/ogc-schemas/blob/master/pom.xml , removed in https://github.com/deegree/deegree3/tree/master/uncoupled/deegree-ogcschemas

- [ ] Job executed: http://buildserver.deegree.org/view/misc/job/upload-ogc-schema/3/

- [ ] Artifact is available in Nexus: http://repo.deegree.org/content/repositories/releases/org/deegree/deegree-ogcschemas/20191108/
