### ISSUE TITLE
Disable GML reference resolver for WFS-T

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#989]
The deegree WFS-T shall support a configuration to skip the GML reference resolving when using WFS-T INSERT or UPDATE actions.

This enhancement shall extend the existing behaviour of #749, #787 and support #743.

**Comment by stempler** [comment]
I had done an attempt on that [here](https://github.com/stempler/deegree3/tree/feature/skip-resolving), when it was said that such a change is not desired in deegree. Maybe that can be used as a starting point. Does not include any configuration via the configuration file and AFAIK only targets the SQL feature store.

**Comment by tfr42** [comment]
@stempler Thanks for the link and hint. The feature request hasn't been discussed so far as I know. Can you point me to that statment you are refering to?

**Comment by stempler** [comment]
Well, my information that a customer's request for this was rejected is only verbal, so it's hard for me to post a link here.
I'm aware that this is more of a work-around and that it needs to be combined with other measures to ensure that the data is consistent in the end, but in respect to the effort needed to solve the underlying problem in different ways it comes quite cheap I think.

**Comment by tfr42** [comment]
Well, the [OSGeo project deegree has only users](https://github.com/deegree/deegree3/blob/master/CONTRIB.md#overview), no customers.  What has been discussed with solution providers is out of scope of this issue tracker.
Anyhow let's stay focused on the requirements and possible solutions. Again, contributions are welcome and in case you would like to contribute, please follow our [Contribution Guidelines](https://github.com/deegree/deegree3/blob/master/CONTRIB.md#legal).

**Comment by tfr42** [comment]
PR #1055 fixes this issue.

**Comment by lgoltz** [comment]
PR #1055 is already merged.
