### ISSUE TITLE
Upgrade to JSF 2.2 and related dependencies

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#991]
Currently used in deegree:
- com.sun.faces:jsf-api:2.1.19
- com.sun.faces:jsf-impl:2.1.19
- org.primefaces:primefaces:4.0

deegree shall use JSF 2.2 (was part of Java EE 7), see https://javaee.github.io/javaserverfaces-spec/

**Comment by tfr42** [comment]
Minimum requirement for Servlet Container is Java EE 7 APIs available, see list of API versions in https://jcp.org/en/jsr/detail?id=342

**Comment by tfr42** [comment]
Primefaces Version supporting JSF 2.0, 2.1, 2.2 and 2.3 and JDK 8 is 8.0, see https://primefaces.github.io/primefaces/8_0/#/gettingstarted/dependencies.
Upgrade to Primeface 8.0 is required.

**Comment by julianzz98** [comment]
After the upgrade https://github.com/deegree/deegree3/pull/1022 should be tested again.

**Comment by tfr42** [comment]
Upgrade to Primefaces 11.0 (https://primefaces.github.io/primefaces/11_0_0/#/gettingstarted/dependencies) required for resolving security issues.

**Comment by tfr42** [comment]
Upgrade to JSF 2.2 and Primefaces 11.0 done with PR #991.
